// Code generated by ent, DO NOT EDIT.

package doffing

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the doffing type in the database.
	Label = "doffing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSpinningLineID holds the string denoting the spinning_line_id field in the database.
	FieldSpinningLineID = "spinning_line_id"
	// FieldSpinningPosition holds the string denoting the spinning_position field in the database.
	FieldSpinningPosition = "spinning_position"
	// FieldLotID holds the string denoting the lot_id field in the database.
	FieldLotID = "lot_id"
	// FieldOperatorID holds the string denoting the operator_id field in the database.
	FieldOperatorID = "operator_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBobbinNumber holds the string denoting the bobbin_number field in the database.
	FieldBobbinNumber = "bobbin_number"
	// FieldActualWeight holds the string denoting the actual_weight field in the database.
	FieldActualWeight = "actual_weight"
	// FieldGrade holds the string denoting the grade field in the database.
	FieldGrade = "grade"
	// FieldCancelReason holds the string denoting the cancel_reason field in the database.
	FieldCancelReason = "cancel_reason"
	// FieldDoffingTime holds the string denoting the doffing_time field in the database.
	FieldDoffingTime = "doffing_time"
	// FieldConfirmedAt holds the string denoting the confirmed_at field in the database.
	FieldConfirmedAt = "confirmed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeLot holds the string denoting the lot edge name in mutations.
	EdgeLot = "lot"
	// Table holds the table name of the doffing in the database.
	Table = "doffings"
	// LotTable is the table that holds the lot relation/edge.
	LotTable = "doffings"
	// LotInverseTable is the table name for the Lot entity.
	// It exists in this package in order to avoid circular dependency with the "lot" package.
	LotInverseTable = "lots"
	// LotColumn is the table column denoting the lot relation/edge.
	LotColumn = "lot_id"
)

// Columns holds all SQL columns for doffing fields.
var Columns = []string{
	FieldID,
	FieldSpinningLineID,
	FieldSpinningPosition,
	FieldLotID,
	FieldOperatorID,
	FieldStatus,
	FieldBobbinNumber,
	FieldActualWeight,
	FieldGrade,
	FieldCancelReason,
	FieldDoffingTime,
	FieldConfirmedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SpinningPositionValidator is a validator for the "spinning_position" field. It is called by the builders before save.
	SpinningPositionValidator func(int) error
	// BobbinNumberValidator is a validator for the "bobbin_number" field. It is called by the builders before save.
	BobbinNumberValidator func(string) error
	// ActualWeightValidator is a validator for the "actual_weight" field. It is called by the builders before save.
	ActualWeightValidator func(float64) error
	// GradeValidator is a validator for the "grade" field. It is called by the builders before save.
	GradeValidator func(string) error
	// DefaultDoffingTime holds the default value on creation for the "doffing_time" field.
	DefaultDoffingTime func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusConfirmed Status = "confirmed"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusConfirmed, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("doffing: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Doffing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySpinningLineID orders the results by the spinning_line_id field.
func BySpinningLineID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpinningLineID, opts...).ToFunc()
}

// BySpinningPosition orders the results by the spinning_position field.
func BySpinningPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpinningPosition, opts...).ToFunc()
}

// ByLotID orders the results by the lot_id field.
func ByLotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLotID, opts...).ToFunc()
}

// ByOperatorID orders the results by the operator_id field.
func ByOperatorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBobbinNumber orders the results by the bobbin_number field.
func ByBobbinNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBobbinNumber, opts...).ToFunc()
}

// ByActualWeight orders the results by the actual_weight field.
func ByActualWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualWeight, opts...).ToFunc()
}

// ByGrade orders the results by the grade field.
func ByGrade(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrade, opts...).ToFunc()
}

// ByCancelReason orders the results by the cancel_reason field.
func ByCancelReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelReason, opts...).ToFunc()
}

// ByDoffingTime orders the results by the doffing_time field.
func ByDoffingTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDoffingTime, opts...).ToFunc()
}

// ByConfirmedAt orders the results by the confirmed_at field.
func ByConfirmedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLotField orders the results by lot field.
func ByLotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLotStep(), sql.OrderByField(field, opts...))
	}
}
func newLotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LotTable, LotColumn),
	)
}
