// Code generated by ent, DO NOT EDIT.

package project

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectNumber holds the string denoting the project_number field in the database.
	FieldProjectNumber = "project_number"
	// FieldProjectName holds the string denoting the project_name field in the database.
	FieldProjectName = "project_name"
	// FieldProductType holds the string denoting the product_type field in the database.
	FieldProductType = "product_type"
	// FieldProductSpec holds the string denoting the product_spec field in the database.
	FieldProductSpec = "product_spec"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPlannedQuantity holds the string denoting the planned_quantity field in the database.
	FieldPlannedQuantity = "planned_quantity"
	// FieldActualQuantity holds the string denoting the actual_quantity field in the database.
	FieldActualQuantity = "actual_quantity"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// Table holds the table name of the project in the database.
	Table = "projects"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "orders"
	// OrdersInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrdersInverseTable = "orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "project_id"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldProjectNumber,
	FieldProjectName,
	FieldProductType,
	FieldProductSpec,
	FieldStatus,
	FieldPlannedQuantity,
	FieldActualQuantity,
	FieldStartDate,
	FieldEndDate,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProjectNumberValidator is a validator for the "project_number" field. It is called by the builders before save.
	ProjectNumberValidator func(string) error
	// ProjectNameValidator is a validator for the "project_name" field. It is called by the builders before save.
	ProjectNameValidator func(string) error
	// ProductSpecValidator is a validator for the "product_spec" field. It is called by the builders before save.
	ProductSpecValidator func(string) error
	// PlannedQuantityValidator is a validator for the "planned_quantity" field. It is called by the builders before save.
	PlannedQuantityValidator func(int) error
	// DefaultActualQuantity holds the default value on creation for the "actual_quantity" field.
	DefaultActualQuantity int
	// ActualQuantityValidator is a validator for the "actual_quantity" field. It is called by the builders before save.
	ActualQuantityValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ProductType defines the type for the "product_type" enum field.
type ProductType string

// ProductType values.
const (
	ProductTypeFDY ProductType = "FDY"
	ProductTypePOY ProductType = "POY"
	ProductTypeDTY ProductType = "DTY"
)

func (pt ProductType) String() string {
	return string(pt)
}

// ProductTypeValidator is a validator for the "product_type" field enum values. It is called by the builders before save.
func ProductTypeValidator(pt ProductType) error {
	switch pt {
	case ProductTypeFDY, ProductTypePOY, ProductTypeDTY:
		return nil
	default:
		return fmt.Errorf("project: invalid enum value for product_type field: %q", pt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPlanning is the default value of the Status enum.
const DefaultStatus = StatusPlanning

// Status values.
const (
	StatusPlanning   Status = "planning"
	StatusInProgress Status = "in_progress"
	StatusCompleted  Status = "completed"
	StatusCancelled  Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPlanning, StatusInProgress, StatusCompleted, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("project: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Project queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectNumber orders the results by the project_number field.
func ByProjectNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectNumber, opts...).ToFunc()
}

// ByProjectName orders the results by the project_name field.
func ByProjectName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectName, opts...).ToFunc()
}

// ByProductType orders the results by the product_type field.
func ByProductType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductType, opts...).ToFunc()
}

// ByProductSpec orders the results by the product_spec field.
func ByProductSpec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductSpec, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPlannedQuantity orders the results by the planned_quantity field.
func ByPlannedQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlannedQuantity, opts...).ToFunc()
}

// ByActualQuantity orders the results by the actual_quantity field.
func ByActualQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualQuantity, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrdersCount orders the results by orders count.
func ByOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrdersStep(), opts...)
	}
}

// ByOrders orders the results by orders terms.
func ByOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
	)
}
