// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BobbinsColumns holds the columns for the "bobbins" table.
	BobbinsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "bobbin_number", Type: field.TypeString, Unique: true, Size: 50},
		{Name: "spinning_position", Type: field.TypeInt},
		{Name: "gross_weight", Type: field.TypeFloat64},
		{Name: "net_weight", Type: field.TypeFloat64},
		{Name: "tare_weight", Type: field.TypeFloat64, Nullable: true},
		{Name: "grade", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"producing", "completed", "packed", "shipped"}, Default: "producing"},
		{Name: "label_printed", Type: field.TypeBool, Default: false},
		{Name: "printed_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "synced", Type: field.TypeBool, Default: false},
		{Name: "synced_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "lot_id", Type: field.TypeUUID},
	}
	// BobbinsTable holds the schema information for the "bobbins" table.
	BobbinsTable = &schema.Table{
		Name:       "bobbins",
		Columns:    BobbinsColumns,
		PrimaryKey: []*schema.Column{BobbinsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bobbins_lots_bobbins",
				Columns:    []*schema.Column{BobbinsColumns[15]},
				RefColumns: []*schema.Column{LotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "bobbin_lot_id",
				Unique:  false,
				Columns: []*schema.Column{BobbinsColumns[15]},
			},
			{
				Name:    "bobbin_spinning_position",
				Unique:  false,
				Columns: []*schema.Column{BobbinsColumns[2]},
			},
			{
				Name:    "bobbin_status",
				Unique:  false,
				Columns: []*schema.Column{BobbinsColumns[7]},
			},
			{
				Name:    "bobbin_synced",
				Unique:  false,
				Columns: []*schema.Column{BobbinsColumns[11]},
			},
			{
				Name:    "bobbin_lot_id_spinning_position",
				Unique:  false,
				Columns: []*schema.Column{BobbinsColumns[15], BobbinsColumns[2]},
			},
		},
	}
	// LotsColumns holds the columns for the "lots" table.
	LotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "lot_number", Type: field.TypeString, Unique: true, Size: 50},
		{Name: "order_id", Type: field.TypeUUID},
		{Name: "product_type", Type: field.TypeEnum, Enums: []string{"FDY", "POY", "DTY"}},
		{Name: "product_spec", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "planned_quantity", Type: field.TypeInt},
		{Name: "actual_quantity", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"in_progress", "paused", "completed", "cancelled"}, Default: "in_progress"},
		{Name: "start_time", Type: field.TypeTime, Nullable: true},
		{Name: "end_time", Type: field.TypeTime, Nullable: true},
		{Name: "synced", Type: field.TypeBool, Default: false},
		{Name: "synced_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// LotsTable holds the schema information for the "lots" table.
	LotsTable = &schema.Table{
		Name:       "lots",
		Columns:    LotsColumns,
		PrimaryKey: []*schema.Column{LotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "lot_status",
				Unique:  false,
				Columns: []*schema.Column{LotsColumns[7]},
			},
			{
				Name:    "lot_synced",
				Unique:  false,
				Columns: []*schema.Column{LotsColumns[10]},
			},
			{
				Name:    "lot_created_at",
				Unique:  false,
				Columns: []*schema.Column{LotsColumns[12]},
			},
		},
	}
	// SyncLogsColumns holds the columns for the "sync_logs" table.
	SyncLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "entity_type", Type: field.TypeEnum, Enums: []string{"lot", "bobbin", "bobbin_grade"}},
		{Name: "entity_id", Type: field.TypeUUID},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"create", "update", "delete"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "success", "failed", "conflict"}, Default: "pending"},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "data_snapshot", Type: field.TypeJSON, Nullable: true},
		{Name: "synced_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SyncLogsTable holds the schema information for the "sync_logs" table.
	SyncLogsTable = &schema.Table{
		Name:       "sync_logs",
		Columns:    SyncLogsColumns,
		PrimaryKey: []*schema.Column{SyncLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "synclog_entity_type",
				Unique:  false,
				Columns: []*schema.Column{SyncLogsColumns[1]},
			},
			{
				Name:    "synclog_entity_id",
				Unique:  false,
				Columns: []*schema.Column{SyncLogsColumns[2]},
			},
			{
				Name:    "synclog_status",
				Unique:  false,
				Columns: []*schema.Column{SyncLogsColumns[4]},
			},
			{
				Name:    "synclog_created_at",
				Unique:  false,
				Columns: []*schema.Column{SyncLogsColumns[9]},
			},
			{
				Name:    "synclog_entity_type_entity_id",
				Unique:  false,
				Columns: []*schema.Column{SyncLogsColumns[1], SyncLogsColumns[2]},
			},
			{
				Name:    "synclog_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{SyncLogsColumns[4], SyncLogsColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BobbinsTable,
		LotsTable,
		SyncLogsTable,
	}
)

func init() {
	BobbinsTable.ForeignKeys[0].RefTable = LotsTable
}
