// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bobbin is the predicate function for bobbin builders.
type Bobbin func(*sql.Selector)

// Carton is the predicate function for carton builders.
type Carton func(*sql.Selector)

// Doffing is the predicate function for doffing builders.
type Doffing func(*sql.Selector)

// Lot is the predicate function for lot builders.
type Lot func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Pallet is the predicate function for pallet builders.
type Pallet func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// SpinningLine is the predicate function for spinningline builders.
type SpinningLine func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
