// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/bobbin"
	"github.com/yourusername/igh-silkroad/internal/database/ent/carton"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
)

// CartonUpdate is the builder for updating Carton entities.
type CartonUpdate struct {
	config
	hooks    []Hook
	mutation *CartonMutation
}

// Where appends a list predicates to the CartonUpdate builder.
func (_u *CartonUpdate) Where(ps ...predicate.Carton) *CartonUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCartonNumber sets the "carton_number" field.
func (_u *CartonUpdate) SetCartonNumber(v string) *CartonUpdate {
	_u.mutation.SetCartonNumber(v)
	return _u
}

// SetNillableCartonNumber sets the "carton_number" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableCartonNumber(v *string) *CartonUpdate {
	if v != nil {
		_u.SetCartonNumber(*v)
	}
	return _u
}

// SetEdgeID sets the "edge_id" field.
func (_u *CartonUpdate) SetEdgeID(v uuid.UUID) *CartonUpdate {
	_u.mutation.SetEdgeID(v)
	return _u
}

// SetNillableEdgeID sets the "edge_id" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableEdgeID(v *uuid.UUID) *CartonUpdate {
	if v != nil {
		_u.SetEdgeID(*v)
	}
	return _u
}

// ClearEdgeID clears the value of the "edge_id" field.
func (_u *CartonUpdate) ClearEdgeID() *CartonUpdate {
	_u.mutation.ClearEdgeID()
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *CartonUpdate) SetLotID(v uuid.UUID) *CartonUpdate {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableLotID(v *uuid.UUID) *CartonUpdate {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// ClearLotID clears the value of the "lot_id" field.
func (_u *CartonUpdate) ClearLotID() *CartonUpdate {
	_u.mutation.ClearLotID()
	return _u
}

// SetBobbinCount sets the "bobbin_count" field.
func (_u *CartonUpdate) SetBobbinCount(v int) *CartonUpdate {
	_u.mutation.ResetBobbinCount()
	_u.mutation.SetBobbinCount(v)
	return _u
}

// SetNillableBobbinCount sets the "bobbin_count" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableBobbinCount(v *int) *CartonUpdate {
	if v != nil {
		_u.SetBobbinCount(*v)
	}
	return _u
}

// AddBobbinCount adds value to the "bobbin_count" field.
func (_u *CartonUpdate) AddBobbinCount(v int) *CartonUpdate {
	_u.mutation.AddBobbinCount(v)
	return _u
}

// SetTotalWeight sets the "total_weight" field.
func (_u *CartonUpdate) SetTotalWeight(v float64) *CartonUpdate {
	_u.mutation.ResetTotalWeight()
	_u.mutation.SetTotalWeight(v)
	return _u
}

// SetNillableTotalWeight sets the "total_weight" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableTotalWeight(v *float64) *CartonUpdate {
	if v != nil {
		_u.SetTotalWeight(*v)
	}
	return _u
}

// AddTotalWeight adds value to the "total_weight" field.
func (_u *CartonUpdate) AddTotalWeight(v float64) *CartonUpdate {
	_u.mutation.AddTotalWeight(v)
	return _u
}

// ClearTotalWeight clears the value of the "total_weight" field.
func (_u *CartonUpdate) ClearTotalWeight() *CartonUpdate {
	_u.mutation.ClearTotalWeight()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CartonUpdate) SetStatus(v carton.Status) *CartonUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableStatus(v *carton.Status) *CartonUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLabelPrinted sets the "label_printed" field.
func (_u *CartonUpdate) SetLabelPrinted(v bool) *CartonUpdate {
	_u.mutation.SetLabelPrinted(v)
	return _u
}

// SetNillableLabelPrinted sets the "label_printed" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableLabelPrinted(v *bool) *CartonUpdate {
	if v != nil {
		_u.SetLabelPrinted(*v)
	}
	return _u
}

// SetPrintedAt sets the "printed_at" field.
func (_u *CartonUpdate) SetPrintedAt(v time.Time) *CartonUpdate {
	_u.mutation.SetPrintedAt(v)
	return _u
}

// SetNillablePrintedAt sets the "printed_at" field if the given value is not nil.
func (_u *CartonUpdate) SetNillablePrintedAt(v *time.Time) *CartonUpdate {
	if v != nil {
		_u.SetPrintedAt(*v)
	}
	return _u
}

// ClearPrintedAt clears the value of the "printed_at" field.
func (_u *CartonUpdate) ClearPrintedAt() *CartonUpdate {
	_u.mutation.ClearPrintedAt()
	return _u
}

// SetPackedAt sets the "packed_at" field.
func (_u *CartonUpdate) SetPackedAt(v time.Time) *CartonUpdate {
	_u.mutation.SetPackedAt(v)
	return _u
}

// SetNillablePackedAt sets the "packed_at" field if the given value is not nil.
func (_u *CartonUpdate) SetNillablePackedAt(v *time.Time) *CartonUpdate {
	if v != nil {
		_u.SetPackedAt(*v)
	}
	return _u
}

// ClearPackedAt clears the value of the "packed_at" field.
func (_u *CartonUpdate) ClearPackedAt() *CartonUpdate {
	_u.mutation.ClearPackedAt()
	return _u
}

// SetSyncStatus sets the "sync_status" field.
func (_u *CartonUpdate) SetSyncStatus(v carton.SyncStatus) *CartonUpdate {
	_u.mutation.SetSyncStatus(v)
	return _u
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableSyncStatus(v *carton.SyncStatus) *CartonUpdate {
	if v != nil {
		_u.SetSyncStatus(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *CartonUpdate) SetSyncedAt(v time.Time) *CartonUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableSyncedAt(v *time.Time) *CartonUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *CartonUpdate) ClearSyncedAt() *CartonUpdate {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetSyncRetryCount sets the "sync_retry_count" field.
func (_u *CartonUpdate) SetSyncRetryCount(v int) *CartonUpdate {
	_u.mutation.ResetSyncRetryCount()
	_u.mutation.SetSyncRetryCount(v)
	return _u
}

// SetNillableSyncRetryCount sets the "sync_retry_count" field if the given value is not nil.
func (_u *CartonUpdate) SetNillableSyncRetryCount(v *int) *CartonUpdate {
	if v != nil {
		_u.SetSyncRetryCount(*v)
	}
	return _u
}

// AddSyncRetryCount adds value to the "sync_retry_count" field.
func (_u *CartonUpdate) AddSyncRetryCount(v int) *CartonUpdate {
	_u.mutation.AddSyncRetryCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CartonUpdate) SetUpdatedAt(v time.Time) *CartonUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddBobbinIDs adds the "bobbins" edge to the Bobbin entity by IDs.
func (_u *CartonUpdate) AddBobbinIDs(ids ...uuid.UUID) *CartonUpdate {
	_u.mutation.AddBobbinIDs(ids...)
	return _u
}

// AddBobbins adds the "bobbins" edges to the Bobbin entity.
func (_u *CartonUpdate) AddBobbins(v ...*Bobbin) *CartonUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBobbinIDs(ids...)
}

// Mutation returns the CartonMutation object of the builder.
func (_u *CartonUpdate) Mutation() *CartonMutation {
	return _u.mutation
}

// ClearBobbins clears all "bobbins" edges to the Bobbin entity.
func (_u *CartonUpdate) ClearBobbins() *CartonUpdate {
	_u.mutation.ClearBobbins()
	return _u
}

// RemoveBobbinIDs removes the "bobbins" edge to Bobbin entities by IDs.
func (_u *CartonUpdate) RemoveBobbinIDs(ids ...uuid.UUID) *CartonUpdate {
	_u.mutation.RemoveBobbinIDs(ids...)
	return _u
}

// RemoveBobbins removes "bobbins" edges to Bobbin entities.
func (_u *CartonUpdate) RemoveBobbins(v ...*Bobbin) *CartonUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBobbinIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CartonUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartonUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CartonUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartonUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CartonUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carton.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CartonUpdate) check() error {
	if v, ok := _u.mutation.CartonNumber(); ok {
		if err := carton.CartonNumberValidator(v); err != nil {
			return &ValidationError{Name: "carton_number", err: fmt.Errorf(`ent: validator failed for field "Carton.carton_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BobbinCount(); ok {
		if err := carton.BobbinCountValidator(v); err != nil {
			return &ValidationError{Name: "bobbin_count", err: fmt.Errorf(`ent: validator failed for field "Carton.bobbin_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalWeight(); ok {
		if err := carton.TotalWeightValidator(v); err != nil {
			return &ValidationError{Name: "total_weight", err: fmt.Errorf(`ent: validator failed for field "Carton.total_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := carton.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Carton.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncStatus(); ok {
		if err := carton.SyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "sync_status", err: fmt.Errorf(`ent: validator failed for field "Carton.sync_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncRetryCount(); ok {
		if err := carton.SyncRetryCountValidator(v); err != nil {
			return &ValidationError{Name: "sync_retry_count", err: fmt.Errorf(`ent: validator failed for field "Carton.sync_retry_count": %w`, err)}
		}
	}
	return nil
}

func (_u *CartonUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carton.Table, carton.Columns, sqlgraph.NewFieldSpec(carton.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CartonNumber(); ok {
		_spec.SetField(carton.FieldCartonNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.EdgeID(); ok {
		_spec.SetField(carton.FieldEdgeID, field.TypeUUID, value)
	}
	if _u.mutation.EdgeIDCleared() {
		_spec.ClearField(carton.FieldEdgeID, field.TypeUUID)
	}
	if value, ok := _u.mutation.LotID(); ok {
		_spec.SetField(carton.FieldLotID, field.TypeUUID, value)
	}
	if _u.mutation.LotIDCleared() {
		_spec.ClearField(carton.FieldLotID, field.TypeUUID)
	}
	if value, ok := _u.mutation.BobbinCount(); ok {
		_spec.SetField(carton.FieldBobbinCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBobbinCount(); ok {
		_spec.AddField(carton.FieldBobbinCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalWeight(); ok {
		_spec.SetField(carton.FieldTotalWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalWeight(); ok {
		_spec.AddField(carton.FieldTotalWeight, field.TypeFloat64, value)
	}
	if _u.mutation.TotalWeightCleared() {
		_spec.ClearField(carton.FieldTotalWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(carton.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LabelPrinted(); ok {
		_spec.SetField(carton.FieldLabelPrinted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PrintedAt(); ok {
		_spec.SetField(carton.FieldPrintedAt, field.TypeTime, value)
	}
	if _u.mutation.PrintedAtCleared() {
		_spec.ClearField(carton.FieldPrintedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PackedAt(); ok {
		_spec.SetField(carton.FieldPackedAt, field.TypeTime, value)
	}
	if _u.mutation.PackedAtCleared() {
		_spec.ClearField(carton.FieldPackedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SyncStatus(); ok {
		_spec.SetField(carton.FieldSyncStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(carton.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(carton.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SyncRetryCount(); ok {
		_spec.SetField(carton.FieldSyncRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSyncRetryCount(); ok {
		_spec.AddField(carton.FieldSyncRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carton.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carton.BobbinsTable,
			Columns: []string{carton.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBobbinsIDs(); len(nodes) > 0 && !_u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carton.BobbinsTable,
			Columns: []string{carton.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BobbinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carton.BobbinsTable,
			Columns: []string{carton.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carton.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CartonUpdateOne is the builder for updating a single Carton entity.
type CartonUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CartonMutation
}

// SetCartonNumber sets the "carton_number" field.
func (_u *CartonUpdateOne) SetCartonNumber(v string) *CartonUpdateOne {
	_u.mutation.SetCartonNumber(v)
	return _u
}

// SetNillableCartonNumber sets the "carton_number" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableCartonNumber(v *string) *CartonUpdateOne {
	if v != nil {
		_u.SetCartonNumber(*v)
	}
	return _u
}

// SetEdgeID sets the "edge_id" field.
func (_u *CartonUpdateOne) SetEdgeID(v uuid.UUID) *CartonUpdateOne {
	_u.mutation.SetEdgeID(v)
	return _u
}

// SetNillableEdgeID sets the "edge_id" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableEdgeID(v *uuid.UUID) *CartonUpdateOne {
	if v != nil {
		_u.SetEdgeID(*v)
	}
	return _u
}

// ClearEdgeID clears the value of the "edge_id" field.
func (_u *CartonUpdateOne) ClearEdgeID() *CartonUpdateOne {
	_u.mutation.ClearEdgeID()
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *CartonUpdateOne) SetLotID(v uuid.UUID) *CartonUpdateOne {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableLotID(v *uuid.UUID) *CartonUpdateOne {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// ClearLotID clears the value of the "lot_id" field.
func (_u *CartonUpdateOne) ClearLotID() *CartonUpdateOne {
	_u.mutation.ClearLotID()
	return _u
}

// SetBobbinCount sets the "bobbin_count" field.
func (_u *CartonUpdateOne) SetBobbinCount(v int) *CartonUpdateOne {
	_u.mutation.ResetBobbinCount()
	_u.mutation.SetBobbinCount(v)
	return _u
}

// SetNillableBobbinCount sets the "bobbin_count" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableBobbinCount(v *int) *CartonUpdateOne {
	if v != nil {
		_u.SetBobbinCount(*v)
	}
	return _u
}

// AddBobbinCount adds value to the "bobbin_count" field.
func (_u *CartonUpdateOne) AddBobbinCount(v int) *CartonUpdateOne {
	_u.mutation.AddBobbinCount(v)
	return _u
}

// SetTotalWeight sets the "total_weight" field.
func (_u *CartonUpdateOne) SetTotalWeight(v float64) *CartonUpdateOne {
	_u.mutation.ResetTotalWeight()
	_u.mutation.SetTotalWeight(v)
	return _u
}

// SetNillableTotalWeight sets the "total_weight" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableTotalWeight(v *float64) *CartonUpdateOne {
	if v != nil {
		_u.SetTotalWeight(*v)
	}
	return _u
}

// AddTotalWeight adds value to the "total_weight" field.
func (_u *CartonUpdateOne) AddTotalWeight(v float64) *CartonUpdateOne {
	_u.mutation.AddTotalWeight(v)
	return _u
}

// ClearTotalWeight clears the value of the "total_weight" field.
func (_u *CartonUpdateOne) ClearTotalWeight() *CartonUpdateOne {
	_u.mutation.ClearTotalWeight()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CartonUpdateOne) SetStatus(v carton.Status) *CartonUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableStatus(v *carton.Status) *CartonUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLabelPrinted sets the "label_printed" field.
func (_u *CartonUpdateOne) SetLabelPrinted(v bool) *CartonUpdateOne {
	_u.mutation.SetLabelPrinted(v)
	return _u
}

// SetNillableLabelPrinted sets the "label_printed" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableLabelPrinted(v *bool) *CartonUpdateOne {
	if v != nil {
		_u.SetLabelPrinted(*v)
	}
	return _u
}

// SetPrintedAt sets the "printed_at" field.
func (_u *CartonUpdateOne) SetPrintedAt(v time.Time) *CartonUpdateOne {
	_u.mutation.SetPrintedAt(v)
	return _u
}

// SetNillablePrintedAt sets the "printed_at" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillablePrintedAt(v *time.Time) *CartonUpdateOne {
	if v != nil {
		_u.SetPrintedAt(*v)
	}
	return _u
}

// ClearPrintedAt clears the value of the "printed_at" field.
func (_u *CartonUpdateOne) ClearPrintedAt() *CartonUpdateOne {
	_u.mutation.ClearPrintedAt()
	return _u
}

// SetPackedAt sets the "packed_at" field.
func (_u *CartonUpdateOne) SetPackedAt(v time.Time) *CartonUpdateOne {
	_u.mutation.SetPackedAt(v)
	return _u
}

// SetNillablePackedAt sets the "packed_at" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillablePackedAt(v *time.Time) *CartonUpdateOne {
	if v != nil {
		_u.SetPackedAt(*v)
	}
	return _u
}

// ClearPackedAt clears the value of the "packed_at" field.
func (_u *CartonUpdateOne) ClearPackedAt() *CartonUpdateOne {
	_u.mutation.ClearPackedAt()
	return _u
}

// SetSyncStatus sets the "sync_status" field.
func (_u *CartonUpdateOne) SetSyncStatus(v carton.SyncStatus) *CartonUpdateOne {
	_u.mutation.SetSyncStatus(v)
	return _u
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableSyncStatus(v *carton.SyncStatus) *CartonUpdateOne {
	if v != nil {
		_u.SetSyncStatus(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *CartonUpdateOne) SetSyncedAt(v time.Time) *CartonUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableSyncedAt(v *time.Time) *CartonUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *CartonUpdateOne) ClearSyncedAt() *CartonUpdateOne {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetSyncRetryCount sets the "sync_retry_count" field.
func (_u *CartonUpdateOne) SetSyncRetryCount(v int) *CartonUpdateOne {
	_u.mutation.ResetSyncRetryCount()
	_u.mutation.SetSyncRetryCount(v)
	return _u
}

// SetNillableSyncRetryCount sets the "sync_retry_count" field if the given value is not nil.
func (_u *CartonUpdateOne) SetNillableSyncRetryCount(v *int) *CartonUpdateOne {
	if v != nil {
		_u.SetSyncRetryCount(*v)
	}
	return _u
}

// AddSyncRetryCount adds value to the "sync_retry_count" field.
func (_u *CartonUpdateOne) AddSyncRetryCount(v int) *CartonUpdateOne {
	_u.mutation.AddSyncRetryCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CartonUpdateOne) SetUpdatedAt(v time.Time) *CartonUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddBobbinIDs adds the "bobbins" edge to the Bobbin entity by IDs.
func (_u *CartonUpdateOne) AddBobbinIDs(ids ...uuid.UUID) *CartonUpdateOne {
	_u.mutation.AddBobbinIDs(ids...)
	return _u
}

// AddBobbins adds the "bobbins" edges to the Bobbin entity.
func (_u *CartonUpdateOne) AddBobbins(v ...*Bobbin) *CartonUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBobbinIDs(ids...)
}

// Mutation returns the CartonMutation object of the builder.
func (_u *CartonUpdateOne) Mutation() *CartonMutation {
	return _u.mutation
}

// ClearBobbins clears all "bobbins" edges to the Bobbin entity.
func (_u *CartonUpdateOne) ClearBobbins() *CartonUpdateOne {
	_u.mutation.ClearBobbins()
	return _u
}

// RemoveBobbinIDs removes the "bobbins" edge to Bobbin entities by IDs.
func (_u *CartonUpdateOne) RemoveBobbinIDs(ids ...uuid.UUID) *CartonUpdateOne {
	_u.mutation.RemoveBobbinIDs(ids...)
	return _u
}

// RemoveBobbins removes "bobbins" edges to Bobbin entities.
func (_u *CartonUpdateOne) RemoveBobbins(v ...*Bobbin) *CartonUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBobbinIDs(ids...)
}

// Where appends a list predicates to the CartonUpdate builder.
func (_u *CartonUpdateOne) Where(ps ...predicate.Carton) *CartonUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CartonUpdateOne) Select(field string, fields ...string) *CartonUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Carton entity.
func (_u *CartonUpdateOne) Save(ctx context.Context) (*Carton, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartonUpdateOne) SaveX(ctx context.Context) *Carton {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CartonUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartonUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CartonUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := carton.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CartonUpdateOne) check() error {
	if v, ok := _u.mutation.CartonNumber(); ok {
		if err := carton.CartonNumberValidator(v); err != nil {
			return &ValidationError{Name: "carton_number", err: fmt.Errorf(`ent: validator failed for field "Carton.carton_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BobbinCount(); ok {
		if err := carton.BobbinCountValidator(v); err != nil {
			return &ValidationError{Name: "bobbin_count", err: fmt.Errorf(`ent: validator failed for field "Carton.bobbin_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalWeight(); ok {
		if err := carton.TotalWeightValidator(v); err != nil {
			return &ValidationError{Name: "total_weight", err: fmt.Errorf(`ent: validator failed for field "Carton.total_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := carton.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Carton.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncStatus(); ok {
		if err := carton.SyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "sync_status", err: fmt.Errorf(`ent: validator failed for field "Carton.sync_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncRetryCount(); ok {
		if err := carton.SyncRetryCountValidator(v); err != nil {
			return &ValidationError{Name: "sync_retry_count", err: fmt.Errorf(`ent: validator failed for field "Carton.sync_retry_count": %w`, err)}
		}
	}
	return nil
}

func (_u *CartonUpdateOne) sqlSave(ctx context.Context) (_node *Carton, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carton.Table, carton.Columns, sqlgraph.NewFieldSpec(carton.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Carton.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carton.FieldID)
		for _, f := range fields {
			if !carton.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != carton.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CartonNumber(); ok {
		_spec.SetField(carton.FieldCartonNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.EdgeID(); ok {
		_spec.SetField(carton.FieldEdgeID, field.TypeUUID, value)
	}
	if _u.mutation.EdgeIDCleared() {
		_spec.ClearField(carton.FieldEdgeID, field.TypeUUID)
	}
	if value, ok := _u.mutation.LotID(); ok {
		_spec.SetField(carton.FieldLotID, field.TypeUUID, value)
	}
	if _u.mutation.LotIDCleared() {
		_spec.ClearField(carton.FieldLotID, field.TypeUUID)
	}
	if value, ok := _u.mutation.BobbinCount(); ok {
		_spec.SetField(carton.FieldBobbinCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBobbinCount(); ok {
		_spec.AddField(carton.FieldBobbinCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalWeight(); ok {
		_spec.SetField(carton.FieldTotalWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalWeight(); ok {
		_spec.AddField(carton.FieldTotalWeight, field.TypeFloat64, value)
	}
	if _u.mutation.TotalWeightCleared() {
		_spec.ClearField(carton.FieldTotalWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(carton.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LabelPrinted(); ok {
		_spec.SetField(carton.FieldLabelPrinted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PrintedAt(); ok {
		_spec.SetField(carton.FieldPrintedAt, field.TypeTime, value)
	}
	if _u.mutation.PrintedAtCleared() {
		_spec.ClearField(carton.FieldPrintedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PackedAt(); ok {
		_spec.SetField(carton.FieldPackedAt, field.TypeTime, value)
	}
	if _u.mutation.PackedAtCleared() {
		_spec.ClearField(carton.FieldPackedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SyncStatus(); ok {
		_spec.SetField(carton.FieldSyncStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(carton.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(carton.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SyncRetryCount(); ok {
		_spec.SetField(carton.FieldSyncRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSyncRetryCount(); ok {
		_spec.AddField(carton.FieldSyncRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(carton.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carton.BobbinsTable,
			Columns: []string{carton.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBobbinsIDs(); len(nodes) > 0 && !_u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carton.BobbinsTable,
			Columns: []string{carton.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BobbinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carton.BobbinsTable,
			Columns: []string{carton.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Carton{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carton.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
