// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/edge"
	"github.com/yourusername/igh-silkroad/internal/database/ent/lot"
	"github.com/yourusername/igh-silkroad/internal/database/ent/spinningline"
)

// EdgeCreate is the builder for creating a Edge entity.
type EdgeCreate struct {
	config
	mutation *EdgeMutation
	hooks    []Hook
}

// SetEdgeCode sets the "edge_code" field.
func (_c *EdgeCreate) SetEdgeCode(v string) *EdgeCreate {
	_c.mutation.SetEdgeCode(v)
	return _c
}

// SetEdgeName sets the "edge_name" field.
func (_c *EdgeCreate) SetEdgeName(v string) *EdgeCreate {
	_c.mutation.SetEdgeName(v)
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *EdgeCreate) SetIPAddress(v string) *EdgeCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableIPAddress(v *string) *EdgeCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EdgeCreate) SetStatus(v edge.Status) *EdgeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableStatus(v *edge.Status) *EdgeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *EdgeCreate) SetLastSeen(v time.Time) *EdgeCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableLastSeen(v *time.Time) *EdgeCreate {
	if v != nil {
		_c.SetLastSeen(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *EdgeCreate) SetVersion(v string) *EdgeCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableVersion(v *string) *EdgeCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *EdgeCreate) SetConfig(v map[string]interface{}) *EdgeCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *EdgeCreate) SetNotes(v string) *EdgeCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableNotes(v *string) *EdgeCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EdgeCreate) SetCreatedAt(v time.Time) *EdgeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableCreatedAt(v *time.Time) *EdgeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EdgeCreate) SetUpdatedAt(v time.Time) *EdgeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableUpdatedAt(v *time.Time) *EdgeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EdgeCreate) SetID(v uuid.UUID) *EdgeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EdgeCreate) SetNillableID(v *uuid.UUID) *EdgeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddSpinningLineIDs adds the "spinning_lines" edge to the SpinningLine entity by IDs.
func (_c *EdgeCreate) AddSpinningLineIDs(ids ...uuid.UUID) *EdgeCreate {
	_c.mutation.AddSpinningLineIDs(ids...)
	return _c
}

// AddSpinningLines adds the "spinning_lines" edges to the SpinningLine entity.
func (_c *EdgeCreate) AddSpinningLines(v ...*SpinningLine) *EdgeCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSpinningLineIDs(ids...)
}

// AddLotIDs adds the "lots" edge to the Lot entity by IDs.
func (_c *EdgeCreate) AddLotIDs(ids ...uuid.UUID) *EdgeCreate {
	_c.mutation.AddLotIDs(ids...)
	return _c
}

// AddLots adds the "lots" edges to the Lot entity.
func (_c *EdgeCreate) AddLots(v ...*Lot) *EdgeCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLotIDs(ids...)
}

// Mutation returns the EdgeMutation object of the builder.
func (_c *EdgeCreate) Mutation() *EdgeMutation {
	return _c.mutation
}

// Save creates the Edge in the database.
func (_c *EdgeCreate) Save(ctx context.Context) (*Edge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EdgeCreate) SaveX(ctx context.Context) *Edge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EdgeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EdgeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EdgeCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := edge.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := edge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := edge.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := edge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EdgeCreate) check() error {
	if _, ok := _c.mutation.EdgeCode(); !ok {
		return &ValidationError{Name: "edge_code", err: errors.New(`ent: missing required field "Edge.edge_code"`)}
	}
	if v, ok := _c.mutation.EdgeCode(); ok {
		if err := edge.EdgeCodeValidator(v); err != nil {
			return &ValidationError{Name: "edge_code", err: fmt.Errorf(`ent: validator failed for field "Edge.edge_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EdgeName(); !ok {
		return &ValidationError{Name: "edge_name", err: errors.New(`ent: missing required field "Edge.edge_name"`)}
	}
	if v, ok := _c.mutation.EdgeName(); ok {
		if err := edge.EdgeNameValidator(v); err != nil {
			return &ValidationError{Name: "edge_name", err: fmt.Errorf(`ent: validator failed for field "Edge.edge_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := edge.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "Edge.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Edge.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := edge.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Edge.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := edge.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Edge.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Edge.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Edge.updated_at"`)}
	}
	return nil
}

func (_c *EdgeCreate) sqlSave(ctx context.Context) (*Edge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EdgeCreate) createSpec() (*Edge, *sqlgraph.CreateSpec) {
	var (
		_node = &Edge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(edge.Table, sqlgraph.NewFieldSpec(edge.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.EdgeCode(); ok {
		_spec.SetField(edge.FieldEdgeCode, field.TypeString, value)
		_node.EdgeCode = value
	}
	if value, ok := _c.mutation.EdgeName(); ok {
		_spec.SetField(edge.FieldEdgeName, field.TypeString, value)
		_node.EdgeName = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(edge.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(edge.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(edge.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(edge.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(edge.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(edge.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(edge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(edge.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SpinningLinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   edge.SpinningLinesTable,
			Columns: []string{edge.SpinningLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spinningline.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   edge.LotsTable,
			Columns: []string{edge.LotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lot.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EdgeCreateBulk is the builder for creating many Edge entities in bulk.
type EdgeCreateBulk struct {
	config
	err      error
	builders []*EdgeCreate
}

// Save creates the Edge entities in the database.
func (_c *EdgeCreateBulk) Save(ctx context.Context) ([]*Edge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Edge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EdgeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EdgeCreateBulk) SaveX(ctx context.Context) []*Edge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EdgeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EdgeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
