// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourusername/igh-silkroad/internal/database/ent/grade"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
)

// GradeUpdate is the builder for updating Grade entities.
type GradeUpdate struct {
	config
	hooks    []Hook
	mutation *GradeMutation
}

// Where appends a list predicates to the GradeUpdate builder.
func (_u *GradeUpdate) Where(ps ...predicate.Grade) *GradeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGradeType sets the "grade_type" field.
func (_u *GradeUpdate) SetGradeType(v grade.GradeType) *GradeUpdate {
	_u.mutation.SetGradeType(v)
	return _u
}

// SetNillableGradeType sets the "grade_type" field if the given value is not nil.
func (_u *GradeUpdate) SetNillableGradeType(v *grade.GradeType) *GradeUpdate {
	if v != nil {
		_u.SetGradeType(*v)
	}
	return _u
}

// SetGradeCode sets the "grade_code" field.
func (_u *GradeUpdate) SetGradeCode(v string) *GradeUpdate {
	_u.mutation.SetGradeCode(v)
	return _u
}

// SetNillableGradeCode sets the "grade_code" field if the given value is not nil.
func (_u *GradeUpdate) SetNillableGradeCode(v *string) *GradeUpdate {
	if v != nil {
		_u.SetGradeCode(*v)
	}
	return _u
}

// SetGradeName sets the "grade_name" field.
func (_u *GradeUpdate) SetGradeName(v string) *GradeUpdate {
	_u.mutation.SetGradeName(v)
	return _u
}

// SetNillableGradeName sets the "grade_name" field if the given value is not nil.
func (_u *GradeUpdate) SetNillableGradeName(v *string) *GradeUpdate {
	if v != nil {
		_u.SetGradeName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GradeUpdate) SetDescription(v string) *GradeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GradeUpdate) SetNillableDescription(v *string) *GradeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GradeUpdate) ClearDescription() *GradeUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *GradeUpdate) SetSortOrder(v int) *GradeUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *GradeUpdate) SetNillableSortOrder(v *int) *GradeUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *GradeUpdate) AddSortOrder(v int) *GradeUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *GradeUpdate) SetIsActive(v bool) *GradeUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *GradeUpdate) SetNillableIsActive(v *bool) *GradeUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GradeUpdate) SetUpdatedAt(v time.Time) *GradeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GradeMutation object of the builder.
func (_u *GradeUpdate) Mutation() *GradeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GradeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GradeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GradeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GradeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GradeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grade.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GradeUpdate) check() error {
	if v, ok := _u.mutation.GradeType(); ok {
		if err := grade.GradeTypeValidator(v); err != nil {
			return &ValidationError{Name: "grade_type", err: fmt.Errorf(`ent: validator failed for field "Grade.grade_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GradeCode(); ok {
		if err := grade.GradeCodeValidator(v); err != nil {
			return &ValidationError{Name: "grade_code", err: fmt.Errorf(`ent: validator failed for field "Grade.grade_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GradeName(); ok {
		if err := grade.GradeNameValidator(v); err != nil {
			return &ValidationError{Name: "grade_name", err: fmt.Errorf(`ent: validator failed for field "Grade.grade_name": %w`, err)}
		}
	}
	return nil
}

func (_u *GradeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grade.Table, grade.Columns, sqlgraph.NewFieldSpec(grade.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GradeType(); ok {
		_spec.SetField(grade.FieldGradeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GradeCode(); ok {
		_spec.SetField(grade.FieldGradeCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.GradeName(); ok {
		_spec.SetField(grade.FieldGradeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(grade.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(grade.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(grade.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(grade.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(grade.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grade.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grade.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GradeUpdateOne is the builder for updating a single Grade entity.
type GradeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GradeMutation
}

// SetGradeType sets the "grade_type" field.
func (_u *GradeUpdateOne) SetGradeType(v grade.GradeType) *GradeUpdateOne {
	_u.mutation.SetGradeType(v)
	return _u
}

// SetNillableGradeType sets the "grade_type" field if the given value is not nil.
func (_u *GradeUpdateOne) SetNillableGradeType(v *grade.GradeType) *GradeUpdateOne {
	if v != nil {
		_u.SetGradeType(*v)
	}
	return _u
}

// SetGradeCode sets the "grade_code" field.
func (_u *GradeUpdateOne) SetGradeCode(v string) *GradeUpdateOne {
	_u.mutation.SetGradeCode(v)
	return _u
}

// SetNillableGradeCode sets the "grade_code" field if the given value is not nil.
func (_u *GradeUpdateOne) SetNillableGradeCode(v *string) *GradeUpdateOne {
	if v != nil {
		_u.SetGradeCode(*v)
	}
	return _u
}

// SetGradeName sets the "grade_name" field.
func (_u *GradeUpdateOne) SetGradeName(v string) *GradeUpdateOne {
	_u.mutation.SetGradeName(v)
	return _u
}

// SetNillableGradeName sets the "grade_name" field if the given value is not nil.
func (_u *GradeUpdateOne) SetNillableGradeName(v *string) *GradeUpdateOne {
	if v != nil {
		_u.SetGradeName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GradeUpdateOne) SetDescription(v string) *GradeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GradeUpdateOne) SetNillableDescription(v *string) *GradeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GradeUpdateOne) ClearDescription() *GradeUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *GradeUpdateOne) SetSortOrder(v int) *GradeUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *GradeUpdateOne) SetNillableSortOrder(v *int) *GradeUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *GradeUpdateOne) AddSortOrder(v int) *GradeUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *GradeUpdateOne) SetIsActive(v bool) *GradeUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *GradeUpdateOne) SetNillableIsActive(v *bool) *GradeUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GradeUpdateOne) SetUpdatedAt(v time.Time) *GradeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GradeMutation object of the builder.
func (_u *GradeUpdateOne) Mutation() *GradeMutation {
	return _u.mutation
}

// Where appends a list predicates to the GradeUpdate builder.
func (_u *GradeUpdateOne) Where(ps ...predicate.Grade) *GradeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GradeUpdateOne) Select(field string, fields ...string) *GradeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Grade entity.
func (_u *GradeUpdateOne) Save(ctx context.Context) (*Grade, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GradeUpdateOne) SaveX(ctx context.Context) *Grade {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GradeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GradeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GradeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grade.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GradeUpdateOne) check() error {
	if v, ok := _u.mutation.GradeType(); ok {
		if err := grade.GradeTypeValidator(v); err != nil {
			return &ValidationError{Name: "grade_type", err: fmt.Errorf(`ent: validator failed for field "Grade.grade_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GradeCode(); ok {
		if err := grade.GradeCodeValidator(v); err != nil {
			return &ValidationError{Name: "grade_code", err: fmt.Errorf(`ent: validator failed for field "Grade.grade_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GradeName(); ok {
		if err := grade.GradeNameValidator(v); err != nil {
			return &ValidationError{Name: "grade_name", err: fmt.Errorf(`ent: validator failed for field "Grade.grade_name": %w`, err)}
		}
	}
	return nil
}

func (_u *GradeUpdateOne) sqlSave(ctx context.Context) (_node *Grade, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grade.Table, grade.Columns, sqlgraph.NewFieldSpec(grade.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Grade.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grade.FieldID)
		for _, f := range fields {
			if !grade.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grade.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GradeType(); ok {
		_spec.SetField(grade.FieldGradeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GradeCode(); ok {
		_spec.SetField(grade.FieldGradeCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.GradeName(); ok {
		_spec.SetField(grade.FieldGradeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(grade.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(grade.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(grade.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(grade.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(grade.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grade.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Grade{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grade.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
