// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/module"
)

// Module is the model entity for the Module schema.
type Module struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// 吊车编号
	ModuleNumber string `json:"module_number,omitempty"`
	// 第一个落纱桶ID
	Barrel1ID uuid.UUID `json:"barrel1_id,omitempty"`
	// 第二个落纱桶ID
	Barrel2ID uuid.UUID `json:"barrel2_id,omitempty"`
	// 吊车状态
	Status module.Status `json:"status,omitempty"`
	// RFID标签
	Rfid string `json:"rfid,omitempty"`
	// 当前位置
	CurrentLocation string `json:"current_location,omitempty"`
	// 同步状态
	SyncStatus module.SyncStatus `json:"sync_status,omitempty"`
	// 同步时间
	SyncedAt time.Time `json:"synced_at,omitempty"`
	// 同步重试次数
	SyncRetryCount int `json:"sync_retry_count,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Module) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case module.FieldSyncRetryCount:
			values[i] = new(sql.NullInt64)
		case module.FieldModuleNumber, module.FieldStatus, module.FieldRfid, module.FieldCurrentLocation, module.FieldSyncStatus:
			values[i] = new(sql.NullString)
		case module.FieldSyncedAt, module.FieldCreatedAt, module.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case module.FieldID, module.FieldBarrel1ID, module.FieldBarrel2ID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Module fields.
func (_m *Module) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case module.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case module.FieldModuleNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module_number", values[i])
			} else if value.Valid {
				_m.ModuleNumber = value.String
			}
		case module.FieldBarrel1ID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field barrel1_id", values[i])
			} else if value != nil {
				_m.Barrel1ID = *value
			}
		case module.FieldBarrel2ID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field barrel2_id", values[i])
			} else if value != nil {
				_m.Barrel2ID = *value
			}
		case module.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = module.Status(value.String)
			}
		case module.FieldRfid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rfid", values[i])
			} else if value.Valid {
				_m.Rfid = value.String
			}
		case module.FieldCurrentLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_location", values[i])
			} else if value.Valid {
				_m.CurrentLocation = value.String
			}
		case module.FieldSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_status", values[i])
			} else if value.Valid {
				_m.SyncStatus = module.SyncStatus(value.String)
			}
		case module.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = value.Time
			}
		case module.FieldSyncRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sync_retry_count", values[i])
			} else if value.Valid {
				_m.SyncRetryCount = int(value.Int64)
			}
		case module.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case module.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Module.
// This includes values selected through modifiers, order, etc.
func (_m *Module) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Module.
// Note that you need to call Module.Unwrap() before calling this method if this Module
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Module) Update() *ModuleUpdateOne {
	return NewModuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Module entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Module) Unwrap() *Module {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Module is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Module) String() string {
	var builder strings.Builder
	builder.WriteString("Module(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("module_number=")
	builder.WriteString(_m.ModuleNumber)
	builder.WriteString(", ")
	builder.WriteString("barrel1_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.Barrel1ID))
	builder.WriteString(", ")
	builder.WriteString("barrel2_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.Barrel2ID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("rfid=")
	builder.WriteString(_m.Rfid)
	builder.WriteString(", ")
	builder.WriteString("current_location=")
	builder.WriteString(_m.CurrentLocation)
	builder.WriteString(", ")
	builder.WriteString("sync_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncStatus))
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(_m.SyncedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sync_retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncRetryCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Modules is a parsable slice of Module.
type Modules []*Module
