// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/lot"
	"github.com/yourusername/igh-silkroad/internal/database/ent/order"
	"github.com/yourusername/igh-silkroad/internal/database/ent/project"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
}

// SetOrderNumber sets the "order_number" field.
func (_c *OrderCreate) SetOrderNumber(v string) *OrderCreate {
	_c.mutation.SetOrderNumber(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *OrderCreate) SetProjectID(v uuid.UUID) *OrderCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *OrderCreate) SetNillableProjectID(v *uuid.UUID) *OrderCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetProductType sets the "product_type" field.
func (_c *OrderCreate) SetProductType(v order.ProductType) *OrderCreate {
	_c.mutation.SetProductType(v)
	return _c
}

// SetProductSpec sets the "product_spec" field.
func (_c *OrderCreate) SetProductSpec(v string) *OrderCreate {
	_c.mutation.SetProductSpec(v)
	return _c
}

// SetNillableProductSpec sets the "product_spec" field if the given value is not nil.
func (_c *OrderCreate) SetNillableProductSpec(v *string) *OrderCreate {
	if v != nil {
		_c.SetProductSpec(*v)
	}
	return _c
}

// SetTargetQuantity sets the "target_quantity" field.
func (_c *OrderCreate) SetTargetQuantity(v int) *OrderCreate {
	_c.mutation.SetTargetQuantity(v)
	return _c
}

// SetActualQuantity sets the "actual_quantity" field.
func (_c *OrderCreate) SetActualQuantity(v int) *OrderCreate {
	_c.mutation.SetActualQuantity(v)
	return _c
}

// SetNillableActualQuantity sets the "actual_quantity" field if the given value is not nil.
func (_c *OrderCreate) SetNillableActualQuantity(v *int) *OrderCreate {
	if v != nil {
		_c.SetActualQuantity(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrderCreate) SetStatus(v order.Status) *OrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrderCreate) SetNillableStatus(v *order.Status) *OrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *OrderCreate) SetPriority(v int) *OrderCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *OrderCreate) SetNillablePriority(v *int) *OrderCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetDeliveryDate sets the "delivery_date" field.
func (_c *OrderCreate) SetDeliveryDate(v time.Time) *OrderCreate {
	_c.mutation.SetDeliveryDate(v)
	return _c
}

// SetNillableDeliveryDate sets the "delivery_date" field if the given value is not nil.
func (_c *OrderCreate) SetNillableDeliveryDate(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetDeliveryDate(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *OrderCreate) SetNotes(v string) *OrderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *OrderCreate) SetNillableNotes(v *string) *OrderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderCreate) SetCreatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableCreatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrderCreate) SetUpdatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableUpdatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrderCreate) SetID(v uuid.UUID) *OrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OrderCreate) SetNillableID(v *uuid.UUID) *OrderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *OrderCreate) SetProject(v *Project) *OrderCreate {
	return _c.SetProjectID(v.ID)
}

// AddLotIDs adds the "lots" edge to the Lot entity by IDs.
func (_c *OrderCreate) AddLotIDs(ids ...uuid.UUID) *OrderCreate {
	_c.mutation.AddLotIDs(ids...)
	return _c
}

// AddLots adds the "lots" edges to the Lot entity.
func (_c *OrderCreate) AddLots(v ...*Lot) *OrderCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLotIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_c *OrderCreate) Mutation() *OrderMutation {
	return _c.mutation
}

// Save creates the Order in the database.
func (_c *OrderCreate) Save(ctx context.Context) (*Order, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderCreate) defaults() {
	if _, ok := _c.mutation.ActualQuantity(); !ok {
		v := order.DefaultActualQuantity
		_c.mutation.SetActualQuantity(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := order.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := order.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := order.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := order.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := order.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCreate) check() error {
	if _, ok := _c.mutation.OrderNumber(); !ok {
		return &ValidationError{Name: "order_number", err: errors.New(`ent: missing required field "Order.order_number"`)}
	}
	if v, ok := _c.mutation.OrderNumber(); ok {
		if err := order.OrderNumberValidator(v); err != nil {
			return &ValidationError{Name: "order_number", err: fmt.Errorf(`ent: validator failed for field "Order.order_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductType(); !ok {
		return &ValidationError{Name: "product_type", err: errors.New(`ent: missing required field "Order.product_type"`)}
	}
	if v, ok := _c.mutation.ProductType(); ok {
		if err := order.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "Order.product_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProductSpec(); ok {
		if err := order.ProductSpecValidator(v); err != nil {
			return &ValidationError{Name: "product_spec", err: fmt.Errorf(`ent: validator failed for field "Order.product_spec": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetQuantity(); !ok {
		return &ValidationError{Name: "target_quantity", err: errors.New(`ent: missing required field "Order.target_quantity"`)}
	}
	if v, ok := _c.mutation.TargetQuantity(); ok {
		if err := order.TargetQuantityValidator(v); err != nil {
			return &ValidationError{Name: "target_quantity", err: fmt.Errorf(`ent: validator failed for field "Order.target_quantity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActualQuantity(); !ok {
		return &ValidationError{Name: "actual_quantity", err: errors.New(`ent: missing required field "Order.actual_quantity"`)}
	}
	if v, ok := _c.mutation.ActualQuantity(); ok {
		if err := order.ActualQuantityValidator(v); err != nil {
			return &ValidationError{Name: "actual_quantity", err: fmt.Errorf(`ent: validator failed for field "Order.actual_quantity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Order.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Order.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Order.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Order.updated_at"`)}
	}
	return nil
}

func (_c *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OrderNumber(); ok {
		_spec.SetField(order.FieldOrderNumber, field.TypeString, value)
		_node.OrderNumber = value
	}
	if value, ok := _c.mutation.ProductType(); ok {
		_spec.SetField(order.FieldProductType, field.TypeEnum, value)
		_node.ProductType = value
	}
	if value, ok := _c.mutation.ProductSpec(); ok {
		_spec.SetField(order.FieldProductSpec, field.TypeString, value)
		_node.ProductSpec = value
	}
	if value, ok := _c.mutation.TargetQuantity(); ok {
		_spec.SetField(order.FieldTargetQuantity, field.TypeInt, value)
		_node.TargetQuantity = value
	}
	if value, ok := _c.mutation.ActualQuantity(); ok {
		_spec.SetField(order.FieldActualQuantity, field.TypeInt, value)
		_node.ActualQuantity = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(order.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.DeliveryDate(); ok {
		_spec.SetField(order.FieldDeliveryDate, field.TypeTime, value)
		_node.DeliveryDate = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(order.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProjectTable,
			Columns: []string{order.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.LotsTable,
			Columns: []string{order.LotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lot.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
}

// Save creates the Order entities in the database.
func (_c *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Order, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
