// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/order"
	"github.com/yourusername/igh-silkroad/internal/database/ent/project"
)

// Order is the model entity for the Order schema.
type Order struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// 订单编号
	OrderNumber string `json:"order_number,omitempty"`
	// 关联项目ID
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// 客户名称
	CustomerName string `json:"customer_name,omitempty"`
	// 客户编码
	CustomerCode string `json:"customer_code,omitempty"`
	// 产品类型
	ProductType order.ProductType `json:"product_type,omitempty"`
	// 产品规格
	ProductSpec string `json:"product_spec,omitempty"`
	// 订单数量（锭）
	OrderQuantity int `json:"order_quantity,omitempty"`
	// 已生产数量（锭）
	ProducedQuantity int `json:"produced_quantity,omitempty"`
	// 订单状态
	Status order.Status `json:"status,omitempty"`
	// 交货日期
	DeliveryDate time.Time `json:"delivery_date,omitempty"`
	// 备注信息
	Notes string `json:"notes,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderQuery when eager-loading is set.
	Edges        OrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrderEdges holds the relations/edges for other nodes in the graph.
type OrderEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Lots holds the value of the lots edge.
	Lots []*Lot `json:"lots,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// LotsOrErr returns the Lots value or an error if the edge
// was not loaded in eager-loading.
func (e OrderEdges) LotsOrErr() ([]*Lot, error) {
	if e.loadedTypes[1] {
		return e.Lots, nil
	}
	return nil, &NotLoadedError{edge: "lots"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Order) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case order.FieldOrderQuantity, order.FieldProducedQuantity:
			values[i] = new(sql.NullInt64)
		case order.FieldOrderNumber, order.FieldCustomerName, order.FieldCustomerCode, order.FieldProductType, order.FieldProductSpec, order.FieldStatus, order.FieldNotes:
			values[i] = new(sql.NullString)
		case order.FieldDeliveryDate, order.FieldCreatedAt, order.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case order.FieldID, order.FieldProjectID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Order fields.
func (_m *Order) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case order.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case order.FieldOrderNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_number", values[i])
			} else if value.Valid {
				_m.OrderNumber = value.String
			}
		case order.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case order.FieldCustomerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_name", values[i])
			} else if value.Valid {
				_m.CustomerName = value.String
			}
		case order.FieldCustomerCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_code", values[i])
			} else if value.Valid {
				_m.CustomerCode = value.String
			}
		case order.FieldProductType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_type", values[i])
			} else if value.Valid {
				_m.ProductType = order.ProductType(value.String)
			}
		case order.FieldProductSpec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_spec", values[i])
			} else if value.Valid {
				_m.ProductSpec = value.String
			}
		case order.FieldOrderQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_quantity", values[i])
			} else if value.Valid {
				_m.OrderQuantity = int(value.Int64)
			}
		case order.FieldProducedQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field produced_quantity", values[i])
			} else if value.Valid {
				_m.ProducedQuantity = int(value.Int64)
			}
		case order.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = order.Status(value.String)
			}
		case order.FieldDeliveryDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_date", values[i])
			} else if value.Valid {
				_m.DeliveryDate = value.Time
			}
		case order.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case order.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case order.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Order.
// This includes values selected through modifiers, order, etc.
func (_m *Order) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Order entity.
func (_m *Order) QueryProject() *ProjectQuery {
	return NewOrderClient(_m.config).QueryProject(_m)
}

// QueryLots queries the "lots" edge of the Order entity.
func (_m *Order) QueryLots() *LotQuery {
	return NewOrderClient(_m.config).QueryLots(_m)
}

// Update returns a builder for updating this Order.
// Note that you need to call Order.Unwrap() before calling this method if this Order
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Order) Update() *OrderUpdateOne {
	return NewOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Order entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Order) Unwrap() *Order {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Order is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Order) String() string {
	var builder strings.Builder
	builder.WriteString("Order(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_number=")
	builder.WriteString(_m.OrderNumber)
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("customer_name=")
	builder.WriteString(_m.CustomerName)
	builder.WriteString(", ")
	builder.WriteString("customer_code=")
	builder.WriteString(_m.CustomerCode)
	builder.WriteString(", ")
	builder.WriteString("product_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductType))
	builder.WriteString(", ")
	builder.WriteString("product_spec=")
	builder.WriteString(_m.ProductSpec)
	builder.WriteString(", ")
	builder.WriteString("order_quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderQuantity))
	builder.WriteString(", ")
	builder.WriteString("produced_quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProducedQuantity))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("delivery_date=")
	builder.WriteString(_m.DeliveryDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Orders is a parsable slice of Order.
type Orders []*Order
