// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/bobbin"
	"github.com/yourusername/igh-silkroad/internal/database/ent/pallet"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
)

// PalletUpdate is the builder for updating Pallet entities.
type PalletUpdate struct {
	config
	hooks    []Hook
	mutation *PalletMutation
}

// Where appends a list predicates to the PalletUpdate builder.
func (_u *PalletUpdate) Where(ps ...predicate.Pallet) *PalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPalletNumber sets the "pallet_number" field.
func (_u *PalletUpdate) SetPalletNumber(v string) *PalletUpdate {
	_u.mutation.SetPalletNumber(v)
	return _u
}

// SetNillablePalletNumber sets the "pallet_number" field if the given value is not nil.
func (_u *PalletUpdate) SetNillablePalletNumber(v *string) *PalletUpdate {
	if v != nil {
		_u.SetPalletNumber(*v)
	}
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *PalletUpdate) SetLotID(v uuid.UUID) *PalletUpdate {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableLotID(v *uuid.UUID) *PalletUpdate {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// ClearLotID clears the value of the "lot_id" field.
func (_u *PalletUpdate) ClearLotID() *PalletUpdate {
	_u.mutation.ClearLotID()
	return _u
}

// SetBobbinCount sets the "bobbin_count" field.
func (_u *PalletUpdate) SetBobbinCount(v int) *PalletUpdate {
	_u.mutation.ResetBobbinCount()
	_u.mutation.SetBobbinCount(v)
	return _u
}

// SetNillableBobbinCount sets the "bobbin_count" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableBobbinCount(v *int) *PalletUpdate {
	if v != nil {
		_u.SetBobbinCount(*v)
	}
	return _u
}

// AddBobbinCount adds value to the "bobbin_count" field.
func (_u *PalletUpdate) AddBobbinCount(v int) *PalletUpdate {
	_u.mutation.AddBobbinCount(v)
	return _u
}

// SetTotalWeight sets the "total_weight" field.
func (_u *PalletUpdate) SetTotalWeight(v float64) *PalletUpdate {
	_u.mutation.ResetTotalWeight()
	_u.mutation.SetTotalWeight(v)
	return _u
}

// SetNillableTotalWeight sets the "total_weight" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableTotalWeight(v *float64) *PalletUpdate {
	if v != nil {
		_u.SetTotalWeight(*v)
	}
	return _u
}

// AddTotalWeight adds value to the "total_weight" field.
func (_u *PalletUpdate) AddTotalWeight(v float64) *PalletUpdate {
	_u.mutation.AddTotalWeight(v)
	return _u
}

// ClearTotalWeight clears the value of the "total_weight" field.
func (_u *PalletUpdate) ClearTotalWeight() *PalletUpdate {
	_u.mutation.ClearTotalWeight()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PalletUpdate) SetStatus(v pallet.Status) *PalletUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableStatus(v *pallet.Status) *PalletUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLabelPrinted sets the "label_printed" field.
func (_u *PalletUpdate) SetLabelPrinted(v bool) *PalletUpdate {
	_u.mutation.SetLabelPrinted(v)
	return _u
}

// SetNillableLabelPrinted sets the "label_printed" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableLabelPrinted(v *bool) *PalletUpdate {
	if v != nil {
		_u.SetLabelPrinted(*v)
	}
	return _u
}

// SetPrintedAt sets the "printed_at" field.
func (_u *PalletUpdate) SetPrintedAt(v time.Time) *PalletUpdate {
	_u.mutation.SetPrintedAt(v)
	return _u
}

// SetNillablePrintedAt sets the "printed_at" field if the given value is not nil.
func (_u *PalletUpdate) SetNillablePrintedAt(v *time.Time) *PalletUpdate {
	if v != nil {
		_u.SetPrintedAt(*v)
	}
	return _u
}

// ClearPrintedAt clears the value of the "printed_at" field.
func (_u *PalletUpdate) ClearPrintedAt() *PalletUpdate {
	_u.mutation.ClearPrintedAt()
	return _u
}

// SetPackedAt sets the "packed_at" field.
func (_u *PalletUpdate) SetPackedAt(v time.Time) *PalletUpdate {
	_u.mutation.SetPackedAt(v)
	return _u
}

// SetNillablePackedAt sets the "packed_at" field if the given value is not nil.
func (_u *PalletUpdate) SetNillablePackedAt(v *time.Time) *PalletUpdate {
	if v != nil {
		_u.SetPackedAt(*v)
	}
	return _u
}

// ClearPackedAt clears the value of the "packed_at" field.
func (_u *PalletUpdate) ClearPackedAt() *PalletUpdate {
	_u.mutation.ClearPackedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PalletUpdate) SetUpdatedAt(v time.Time) *PalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddBobbinIDs adds the "bobbins" edge to the Bobbin entity by IDs.
func (_u *PalletUpdate) AddBobbinIDs(ids ...uuid.UUID) *PalletUpdate {
	_u.mutation.AddBobbinIDs(ids...)
	return _u
}

// AddBobbins adds the "bobbins" edges to the Bobbin entity.
func (_u *PalletUpdate) AddBobbins(v ...*Bobbin) *PalletUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBobbinIDs(ids...)
}

// Mutation returns the PalletMutation object of the builder.
func (_u *PalletUpdate) Mutation() *PalletMutation {
	return _u.mutation
}

// ClearBobbins clears all "bobbins" edges to the Bobbin entity.
func (_u *PalletUpdate) ClearBobbins() *PalletUpdate {
	_u.mutation.ClearBobbins()
	return _u
}

// RemoveBobbinIDs removes the "bobbins" edge to Bobbin entities by IDs.
func (_u *PalletUpdate) RemoveBobbinIDs(ids ...uuid.UUID) *PalletUpdate {
	_u.mutation.RemoveBobbinIDs(ids...)
	return _u
}

// RemoveBobbins removes "bobbins" edges to Bobbin entities.
func (_u *PalletUpdate) RemoveBobbins(v ...*Bobbin) *PalletUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBobbinIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PalletUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PalletUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PalletUpdate) check() error {
	if v, ok := _u.mutation.PalletNumber(); ok {
		if err := pallet.PalletNumberValidator(v); err != nil {
			return &ValidationError{Name: "pallet_number", err: fmt.Errorf(`ent: validator failed for field "Pallet.pallet_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BobbinCount(); ok {
		if err := pallet.BobbinCountValidator(v); err != nil {
			return &ValidationError{Name: "bobbin_count", err: fmt.Errorf(`ent: validator failed for field "Pallet.bobbin_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalWeight(); ok {
		if err := pallet.TotalWeightValidator(v); err != nil {
			return &ValidationError{Name: "total_weight", err: fmt.Errorf(`ent: validator failed for field "Pallet.total_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pallet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Pallet.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pallet.Table, pallet.Columns, sqlgraph.NewFieldSpec(pallet.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PalletNumber(); ok {
		_spec.SetField(pallet.FieldPalletNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.LotID(); ok {
		_spec.SetField(pallet.FieldLotID, field.TypeUUID, value)
	}
	if _u.mutation.LotIDCleared() {
		_spec.ClearField(pallet.FieldLotID, field.TypeUUID)
	}
	if value, ok := _u.mutation.BobbinCount(); ok {
		_spec.SetField(pallet.FieldBobbinCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBobbinCount(); ok {
		_spec.AddField(pallet.FieldBobbinCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalWeight(); ok {
		_spec.SetField(pallet.FieldTotalWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalWeight(); ok {
		_spec.AddField(pallet.FieldTotalWeight, field.TypeFloat64, value)
	}
	if _u.mutation.TotalWeightCleared() {
		_spec.ClearField(pallet.FieldTotalWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pallet.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LabelPrinted(); ok {
		_spec.SetField(pallet.FieldLabelPrinted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PrintedAt(); ok {
		_spec.SetField(pallet.FieldPrintedAt, field.TypeTime, value)
	}
	if _u.mutation.PrintedAtCleared() {
		_spec.ClearField(pallet.FieldPrintedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PackedAt(); ok {
		_spec.SetField(pallet.FieldPackedAt, field.TypeTime, value)
	}
	if _u.mutation.PackedAtCleared() {
		_spec.ClearField(pallet.FieldPackedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBobbinsIDs(); len(nodes) > 0 && !_u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BobbinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PalletUpdateOne is the builder for updating a single Pallet entity.
type PalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PalletMutation
}

// SetPalletNumber sets the "pallet_number" field.
func (_u *PalletUpdateOne) SetPalletNumber(v string) *PalletUpdateOne {
	_u.mutation.SetPalletNumber(v)
	return _u
}

// SetNillablePalletNumber sets the "pallet_number" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillablePalletNumber(v *string) *PalletUpdateOne {
	if v != nil {
		_u.SetPalletNumber(*v)
	}
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *PalletUpdateOne) SetLotID(v uuid.UUID) *PalletUpdateOne {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableLotID(v *uuid.UUID) *PalletUpdateOne {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// ClearLotID clears the value of the "lot_id" field.
func (_u *PalletUpdateOne) ClearLotID() *PalletUpdateOne {
	_u.mutation.ClearLotID()
	return _u
}

// SetBobbinCount sets the "bobbin_count" field.
func (_u *PalletUpdateOne) SetBobbinCount(v int) *PalletUpdateOne {
	_u.mutation.ResetBobbinCount()
	_u.mutation.SetBobbinCount(v)
	return _u
}

// SetNillableBobbinCount sets the "bobbin_count" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableBobbinCount(v *int) *PalletUpdateOne {
	if v != nil {
		_u.SetBobbinCount(*v)
	}
	return _u
}

// AddBobbinCount adds value to the "bobbin_count" field.
func (_u *PalletUpdateOne) AddBobbinCount(v int) *PalletUpdateOne {
	_u.mutation.AddBobbinCount(v)
	return _u
}

// SetTotalWeight sets the "total_weight" field.
func (_u *PalletUpdateOne) SetTotalWeight(v float64) *PalletUpdateOne {
	_u.mutation.ResetTotalWeight()
	_u.mutation.SetTotalWeight(v)
	return _u
}

// SetNillableTotalWeight sets the "total_weight" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableTotalWeight(v *float64) *PalletUpdateOne {
	if v != nil {
		_u.SetTotalWeight(*v)
	}
	return _u
}

// AddTotalWeight adds value to the "total_weight" field.
func (_u *PalletUpdateOne) AddTotalWeight(v float64) *PalletUpdateOne {
	_u.mutation.AddTotalWeight(v)
	return _u
}

// ClearTotalWeight clears the value of the "total_weight" field.
func (_u *PalletUpdateOne) ClearTotalWeight() *PalletUpdateOne {
	_u.mutation.ClearTotalWeight()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PalletUpdateOne) SetStatus(v pallet.Status) *PalletUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableStatus(v *pallet.Status) *PalletUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLabelPrinted sets the "label_printed" field.
func (_u *PalletUpdateOne) SetLabelPrinted(v bool) *PalletUpdateOne {
	_u.mutation.SetLabelPrinted(v)
	return _u
}

// SetNillableLabelPrinted sets the "label_printed" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableLabelPrinted(v *bool) *PalletUpdateOne {
	if v != nil {
		_u.SetLabelPrinted(*v)
	}
	return _u
}

// SetPrintedAt sets the "printed_at" field.
func (_u *PalletUpdateOne) SetPrintedAt(v time.Time) *PalletUpdateOne {
	_u.mutation.SetPrintedAt(v)
	return _u
}

// SetNillablePrintedAt sets the "printed_at" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillablePrintedAt(v *time.Time) *PalletUpdateOne {
	if v != nil {
		_u.SetPrintedAt(*v)
	}
	return _u
}

// ClearPrintedAt clears the value of the "printed_at" field.
func (_u *PalletUpdateOne) ClearPrintedAt() *PalletUpdateOne {
	_u.mutation.ClearPrintedAt()
	return _u
}

// SetPackedAt sets the "packed_at" field.
func (_u *PalletUpdateOne) SetPackedAt(v time.Time) *PalletUpdateOne {
	_u.mutation.SetPackedAt(v)
	return _u
}

// SetNillablePackedAt sets the "packed_at" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillablePackedAt(v *time.Time) *PalletUpdateOne {
	if v != nil {
		_u.SetPackedAt(*v)
	}
	return _u
}

// ClearPackedAt clears the value of the "packed_at" field.
func (_u *PalletUpdateOne) ClearPackedAt() *PalletUpdateOne {
	_u.mutation.ClearPackedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PalletUpdateOne) SetUpdatedAt(v time.Time) *PalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddBobbinIDs adds the "bobbins" edge to the Bobbin entity by IDs.
func (_u *PalletUpdateOne) AddBobbinIDs(ids ...uuid.UUID) *PalletUpdateOne {
	_u.mutation.AddBobbinIDs(ids...)
	return _u
}

// AddBobbins adds the "bobbins" edges to the Bobbin entity.
func (_u *PalletUpdateOne) AddBobbins(v ...*Bobbin) *PalletUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBobbinIDs(ids...)
}

// Mutation returns the PalletMutation object of the builder.
func (_u *PalletUpdateOne) Mutation() *PalletMutation {
	return _u.mutation
}

// ClearBobbins clears all "bobbins" edges to the Bobbin entity.
func (_u *PalletUpdateOne) ClearBobbins() *PalletUpdateOne {
	_u.mutation.ClearBobbins()
	return _u
}

// RemoveBobbinIDs removes the "bobbins" edge to Bobbin entities by IDs.
func (_u *PalletUpdateOne) RemoveBobbinIDs(ids ...uuid.UUID) *PalletUpdateOne {
	_u.mutation.RemoveBobbinIDs(ids...)
	return _u
}

// RemoveBobbins removes "bobbins" edges to Bobbin entities.
func (_u *PalletUpdateOne) RemoveBobbins(v ...*Bobbin) *PalletUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBobbinIDs(ids...)
}

// Where appends a list predicates to the PalletUpdate builder.
func (_u *PalletUpdateOne) Where(ps ...predicate.Pallet) *PalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PalletUpdateOne) Select(field string, fields ...string) *PalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pallet entity.
func (_u *PalletUpdateOne) Save(ctx context.Context) (*Pallet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PalletUpdateOne) SaveX(ctx context.Context) *Pallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PalletUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PalletUpdateOne) check() error {
	if v, ok := _u.mutation.PalletNumber(); ok {
		if err := pallet.PalletNumberValidator(v); err != nil {
			return &ValidationError{Name: "pallet_number", err: fmt.Errorf(`ent: validator failed for field "Pallet.pallet_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BobbinCount(); ok {
		if err := pallet.BobbinCountValidator(v); err != nil {
			return &ValidationError{Name: "bobbin_count", err: fmt.Errorf(`ent: validator failed for field "Pallet.bobbin_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalWeight(); ok {
		if err := pallet.TotalWeightValidator(v); err != nil {
			return &ValidationError{Name: "total_weight", err: fmt.Errorf(`ent: validator failed for field "Pallet.total_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pallet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Pallet.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PalletUpdateOne) sqlSave(ctx context.Context) (_node *Pallet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pallet.Table, pallet.Columns, sqlgraph.NewFieldSpec(pallet.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pallet.FieldID)
		for _, f := range fields {
			if !pallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PalletNumber(); ok {
		_spec.SetField(pallet.FieldPalletNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.LotID(); ok {
		_spec.SetField(pallet.FieldLotID, field.TypeUUID, value)
	}
	if _u.mutation.LotIDCleared() {
		_spec.ClearField(pallet.FieldLotID, field.TypeUUID)
	}
	if value, ok := _u.mutation.BobbinCount(); ok {
		_spec.SetField(pallet.FieldBobbinCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBobbinCount(); ok {
		_spec.AddField(pallet.FieldBobbinCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalWeight(); ok {
		_spec.SetField(pallet.FieldTotalWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalWeight(); ok {
		_spec.AddField(pallet.FieldTotalWeight, field.TypeFloat64, value)
	}
	if _u.mutation.TotalWeightCleared() {
		_spec.ClearField(pallet.FieldTotalWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pallet.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LabelPrinted(); ok {
		_spec.SetField(pallet.FieldLabelPrinted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PrintedAt(); ok {
		_spec.SetField(pallet.FieldPrintedAt, field.TypeTime, value)
	}
	if _u.mutation.PrintedAtCleared() {
		_spec.ClearField(pallet.FieldPrintedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PackedAt(); ok {
		_spec.SetField(pallet.FieldPackedAt, field.TypeTime, value)
	}
	if _u.mutation.PackedAtCleared() {
		_spec.ClearField(pallet.FieldPackedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBobbinsIDs(); len(nodes) > 0 && !_u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BobbinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
