// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/bobbin"
	"github.com/yourusername/igh-silkroad/internal/database/ent/pallet"
)

// PalletCreate is the builder for creating a Pallet entity.
type PalletCreate struct {
	config
	mutation *PalletMutation
	hooks    []Hook
}

// SetPalletNumber sets the "pallet_number" field.
func (_c *PalletCreate) SetPalletNumber(v string) *PalletCreate {
	_c.mutation.SetPalletNumber(v)
	return _c
}

// SetLotID sets the "lot_id" field.
func (_c *PalletCreate) SetLotID(v uuid.UUID) *PalletCreate {
	_c.mutation.SetLotID(v)
	return _c
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_c *PalletCreate) SetNillableLotID(v *uuid.UUID) *PalletCreate {
	if v != nil {
		_c.SetLotID(*v)
	}
	return _c
}

// SetBobbinCount sets the "bobbin_count" field.
func (_c *PalletCreate) SetBobbinCount(v int) *PalletCreate {
	_c.mutation.SetBobbinCount(v)
	return _c
}

// SetNillableBobbinCount sets the "bobbin_count" field if the given value is not nil.
func (_c *PalletCreate) SetNillableBobbinCount(v *int) *PalletCreate {
	if v != nil {
		_c.SetBobbinCount(*v)
	}
	return _c
}

// SetTotalWeight sets the "total_weight" field.
func (_c *PalletCreate) SetTotalWeight(v float64) *PalletCreate {
	_c.mutation.SetTotalWeight(v)
	return _c
}

// SetNillableTotalWeight sets the "total_weight" field if the given value is not nil.
func (_c *PalletCreate) SetNillableTotalWeight(v *float64) *PalletCreate {
	if v != nil {
		_c.SetTotalWeight(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PalletCreate) SetStatus(v pallet.Status) *PalletCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PalletCreate) SetNillableStatus(v *pallet.Status) *PalletCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLabelPrinted sets the "label_printed" field.
func (_c *PalletCreate) SetLabelPrinted(v bool) *PalletCreate {
	_c.mutation.SetLabelPrinted(v)
	return _c
}

// SetNillableLabelPrinted sets the "label_printed" field if the given value is not nil.
func (_c *PalletCreate) SetNillableLabelPrinted(v *bool) *PalletCreate {
	if v != nil {
		_c.SetLabelPrinted(*v)
	}
	return _c
}

// SetPrintedAt sets the "printed_at" field.
func (_c *PalletCreate) SetPrintedAt(v time.Time) *PalletCreate {
	_c.mutation.SetPrintedAt(v)
	return _c
}

// SetNillablePrintedAt sets the "printed_at" field if the given value is not nil.
func (_c *PalletCreate) SetNillablePrintedAt(v *time.Time) *PalletCreate {
	if v != nil {
		_c.SetPrintedAt(*v)
	}
	return _c
}

// SetPackedAt sets the "packed_at" field.
func (_c *PalletCreate) SetPackedAt(v time.Time) *PalletCreate {
	_c.mutation.SetPackedAt(v)
	return _c
}

// SetNillablePackedAt sets the "packed_at" field if the given value is not nil.
func (_c *PalletCreate) SetNillablePackedAt(v *time.Time) *PalletCreate {
	if v != nil {
		_c.SetPackedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PalletCreate) SetCreatedAt(v time.Time) *PalletCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PalletCreate) SetNillableCreatedAt(v *time.Time) *PalletCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PalletCreate) SetUpdatedAt(v time.Time) *PalletCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PalletCreate) SetNillableUpdatedAt(v *time.Time) *PalletCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PalletCreate) SetID(v uuid.UUID) *PalletCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PalletCreate) SetNillableID(v *uuid.UUID) *PalletCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddBobbinIDs adds the "bobbins" edge to the Bobbin entity by IDs.
func (_c *PalletCreate) AddBobbinIDs(ids ...uuid.UUID) *PalletCreate {
	_c.mutation.AddBobbinIDs(ids...)
	return _c
}

// AddBobbins adds the "bobbins" edges to the Bobbin entity.
func (_c *PalletCreate) AddBobbins(v ...*Bobbin) *PalletCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBobbinIDs(ids...)
}

// Mutation returns the PalletMutation object of the builder.
func (_c *PalletCreate) Mutation() *PalletMutation {
	return _c.mutation
}

// Save creates the Pallet in the database.
func (_c *PalletCreate) Save(ctx context.Context) (*Pallet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PalletCreate) SaveX(ctx context.Context) *Pallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PalletCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PalletCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PalletCreate) defaults() {
	if _, ok := _c.mutation.BobbinCount(); !ok {
		v := pallet.DefaultBobbinCount
		_c.mutation.SetBobbinCount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := pallet.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.LabelPrinted(); !ok {
		v := pallet.DefaultLabelPrinted
		_c.mutation.SetLabelPrinted(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pallet.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pallet.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pallet.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PalletCreate) check() error {
	if _, ok := _c.mutation.PalletNumber(); !ok {
		return &ValidationError{Name: "pallet_number", err: errors.New(`ent: missing required field "Pallet.pallet_number"`)}
	}
	if v, ok := _c.mutation.PalletNumber(); ok {
		if err := pallet.PalletNumberValidator(v); err != nil {
			return &ValidationError{Name: "pallet_number", err: fmt.Errorf(`ent: validator failed for field "Pallet.pallet_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BobbinCount(); !ok {
		return &ValidationError{Name: "bobbin_count", err: errors.New(`ent: missing required field "Pallet.bobbin_count"`)}
	}
	if v, ok := _c.mutation.BobbinCount(); ok {
		if err := pallet.BobbinCountValidator(v); err != nil {
			return &ValidationError{Name: "bobbin_count", err: fmt.Errorf(`ent: validator failed for field "Pallet.bobbin_count": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TotalWeight(); ok {
		if err := pallet.TotalWeightValidator(v); err != nil {
			return &ValidationError{Name: "total_weight", err: fmt.Errorf(`ent: validator failed for field "Pallet.total_weight": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Pallet.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := pallet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Pallet.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LabelPrinted(); !ok {
		return &ValidationError{Name: "label_printed", err: errors.New(`ent: missing required field "Pallet.label_printed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Pallet.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Pallet.updated_at"`)}
	}
	return nil
}

func (_c *PalletCreate) sqlSave(ctx context.Context) (*Pallet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PalletCreate) createSpec() (*Pallet, *sqlgraph.CreateSpec) {
	var (
		_node = &Pallet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pallet.Table, sqlgraph.NewFieldSpec(pallet.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PalletNumber(); ok {
		_spec.SetField(pallet.FieldPalletNumber, field.TypeString, value)
		_node.PalletNumber = value
	}
	if value, ok := _c.mutation.LotID(); ok {
		_spec.SetField(pallet.FieldLotID, field.TypeUUID, value)
		_node.LotID = value
	}
	if value, ok := _c.mutation.BobbinCount(); ok {
		_spec.SetField(pallet.FieldBobbinCount, field.TypeInt, value)
		_node.BobbinCount = value
	}
	if value, ok := _c.mutation.TotalWeight(); ok {
		_spec.SetField(pallet.FieldTotalWeight, field.TypeFloat64, value)
		_node.TotalWeight = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(pallet.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LabelPrinted(); ok {
		_spec.SetField(pallet.FieldLabelPrinted, field.TypeBool, value)
		_node.LabelPrinted = value
	}
	if value, ok := _c.mutation.PrintedAt(); ok {
		_spec.SetField(pallet.FieldPrintedAt, field.TypeTime, value)
		_node.PrintedAt = value
	}
	if value, ok := _c.mutation.PackedAt(); ok {
		_spec.SetField(pallet.FieldPackedAt, field.TypeTime, value)
		_node.PackedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pallet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pallet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.BobbinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PalletCreateBulk is the builder for creating many Pallet entities in bulk.
type PalletCreateBulk struct {
	config
	err      error
	builders []*PalletCreate
}

// Save creates the Pallet entities in the database.
func (_c *PalletCreateBulk) Save(ctx context.Context) ([]*Pallet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Pallet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PalletMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PalletCreateBulk) SaveX(ctx context.Context) []*Pallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PalletCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PalletCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
