// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/bobbin"
	"github.com/yourusername/igh-silkroad/internal/database/ent/lot"
	"github.com/yourusername/igh-silkroad/internal/database/ent/pallet"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
)

// PalletUpdate is the builder for updating Pallet entities.
type PalletUpdate struct {
	config
	hooks    []Hook
	mutation *PalletMutation
}

// Where appends a list predicates to the PalletUpdate builder.
func (_u *PalletUpdate) Where(ps ...predicate.Pallet) *PalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPalletCode sets the "pallet_code" field.
func (_u *PalletUpdate) SetPalletCode(v string) *PalletUpdate {
	_u.mutation.SetPalletCode(v)
	return _u
}

// SetNillablePalletCode sets the "pallet_code" field if the given value is not nil.
func (_u *PalletUpdate) SetNillablePalletCode(v *string) *PalletUpdate {
	if v != nil {
		_u.SetPalletCode(*v)
	}
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *PalletUpdate) SetLotID(v uuid.UUID) *PalletUpdate {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableLotID(v *uuid.UUID) *PalletUpdate {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *PalletUpdate) SetLevel(v int) *PalletUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableLevel(v *int) *PalletUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *PalletUpdate) AddLevel(v int) *PalletUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetBobbinsCount sets the "bobbins_count" field.
func (_u *PalletUpdate) SetBobbinsCount(v int) *PalletUpdate {
	_u.mutation.ResetBobbinsCount()
	_u.mutation.SetBobbinsCount(v)
	return _u
}

// SetNillableBobbinsCount sets the "bobbins_count" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableBobbinsCount(v *int) *PalletUpdate {
	if v != nil {
		_u.SetBobbinsCount(*v)
	}
	return _u
}

// AddBobbinsCount adds value to the "bobbins_count" field.
func (_u *PalletUpdate) AddBobbinsCount(v int) *PalletUpdate {
	_u.mutation.AddBobbinsCount(v)
	return _u
}

// SetNetWeight sets the "net_weight" field.
func (_u *PalletUpdate) SetNetWeight(v float64) *PalletUpdate {
	_u.mutation.ResetNetWeight()
	_u.mutation.SetNetWeight(v)
	return _u
}

// SetNillableNetWeight sets the "net_weight" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableNetWeight(v *float64) *PalletUpdate {
	if v != nil {
		_u.SetNetWeight(*v)
	}
	return _u
}

// AddNetWeight adds value to the "net_weight" field.
func (_u *PalletUpdate) AddNetWeight(v float64) *PalletUpdate {
	_u.mutation.AddNetWeight(v)
	return _u
}

// ClearNetWeight clears the value of the "net_weight" field.
func (_u *PalletUpdate) ClearNetWeight() *PalletUpdate {
	_u.mutation.ClearNetWeight()
	return _u
}

// SetGrossWeight sets the "gross_weight" field.
func (_u *PalletUpdate) SetGrossWeight(v float64) *PalletUpdate {
	_u.mutation.ResetGrossWeight()
	_u.mutation.SetGrossWeight(v)
	return _u
}

// SetNillableGrossWeight sets the "gross_weight" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableGrossWeight(v *float64) *PalletUpdate {
	if v != nil {
		_u.SetGrossWeight(*v)
	}
	return _u
}

// AddGrossWeight adds value to the "gross_weight" field.
func (_u *PalletUpdate) AddGrossWeight(v float64) *PalletUpdate {
	_u.mutation.AddGrossWeight(v)
	return _u
}

// ClearGrossWeight clears the value of the "gross_weight" field.
func (_u *PalletUpdate) ClearGrossWeight() *PalletUpdate {
	_u.mutation.ClearGrossWeight()
	return _u
}

// SetTareWeight sets the "tare_weight" field.
func (_u *PalletUpdate) SetTareWeight(v float64) *PalletUpdate {
	_u.mutation.ResetTareWeight()
	_u.mutation.SetTareWeight(v)
	return _u
}

// SetNillableTareWeight sets the "tare_weight" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableTareWeight(v *float64) *PalletUpdate {
	if v != nil {
		_u.SetTareWeight(*v)
	}
	return _u
}

// AddTareWeight adds value to the "tare_weight" field.
func (_u *PalletUpdate) AddTareWeight(v float64) *PalletUpdate {
	_u.mutation.AddTareWeight(v)
	return _u
}

// ClearTareWeight clears the value of the "tare_weight" field.
func (_u *PalletUpdate) ClearTareWeight() *PalletUpdate {
	_u.mutation.ClearTareWeight()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PalletUpdate) SetStatus(v pallet.Status) *PalletUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableStatus(v *pallet.Status) *PalletUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPalletizerID sets the "palletizer_id" field.
func (_u *PalletUpdate) SetPalletizerID(v uuid.UUID) *PalletUpdate {
	_u.mutation.SetPalletizerID(v)
	return _u
}

// SetNillablePalletizerID sets the "palletizer_id" field if the given value is not nil.
func (_u *PalletUpdate) SetNillablePalletizerID(v *uuid.UUID) *PalletUpdate {
	if v != nil {
		_u.SetPalletizerID(*v)
	}
	return _u
}

// ClearPalletizerID clears the value of the "palletizer_id" field.
func (_u *PalletUpdate) ClearPalletizerID() *PalletUpdate {
	_u.mutation.ClearPalletizerID()
	return _u
}

// SetPrinted sets the "printed" field.
func (_u *PalletUpdate) SetPrinted(v bool) *PalletUpdate {
	_u.mutation.SetPrinted(v)
	return _u
}

// SetNillablePrinted sets the "printed" field if the given value is not nil.
func (_u *PalletUpdate) SetNillablePrinted(v *bool) *PalletUpdate {
	if v != nil {
		_u.SetPrinted(*v)
	}
	return _u
}

// SetPrintedAt sets the "printed_at" field.
func (_u *PalletUpdate) SetPrintedAt(v time.Time) *PalletUpdate {
	_u.mutation.SetPrintedAt(v)
	return _u
}

// SetNillablePrintedAt sets the "printed_at" field if the given value is not nil.
func (_u *PalletUpdate) SetNillablePrintedAt(v *time.Time) *PalletUpdate {
	if v != nil {
		_u.SetPrintedAt(*v)
	}
	return _u
}

// ClearPrintedAt clears the value of the "printed_at" field.
func (_u *PalletUpdate) ClearPrintedAt() *PalletUpdate {
	_u.mutation.ClearPrintedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PalletUpdate) SetCompletedAt(v time.Time) *PalletUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PalletUpdate) SetNillableCompletedAt(v *time.Time) *PalletUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PalletUpdate) ClearCompletedAt() *PalletUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PalletUpdate) SetUpdatedAt(v time.Time) *PalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLot sets the "lot" edge to the Lot entity.
func (_u *PalletUpdate) SetLot(v *Lot) *PalletUpdate {
	return _u.SetLotID(v.ID)
}

// AddBobbinIDs adds the "bobbins" edge to the Bobbin entity by IDs.
func (_u *PalletUpdate) AddBobbinIDs(ids ...uuid.UUID) *PalletUpdate {
	_u.mutation.AddBobbinIDs(ids...)
	return _u
}

// AddBobbins adds the "bobbins" edges to the Bobbin entity.
func (_u *PalletUpdate) AddBobbins(v ...*Bobbin) *PalletUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBobbinIDs(ids...)
}

// Mutation returns the PalletMutation object of the builder.
func (_u *PalletUpdate) Mutation() *PalletMutation {
	return _u.mutation
}

// ClearLot clears the "lot" edge to the Lot entity.
func (_u *PalletUpdate) ClearLot() *PalletUpdate {
	_u.mutation.ClearLot()
	return _u
}

// ClearBobbins clears all "bobbins" edges to the Bobbin entity.
func (_u *PalletUpdate) ClearBobbins() *PalletUpdate {
	_u.mutation.ClearBobbins()
	return _u
}

// RemoveBobbinIDs removes the "bobbins" edge to Bobbin entities by IDs.
func (_u *PalletUpdate) RemoveBobbinIDs(ids ...uuid.UUID) *PalletUpdate {
	_u.mutation.RemoveBobbinIDs(ids...)
	return _u
}

// RemoveBobbins removes "bobbins" edges to Bobbin entities.
func (_u *PalletUpdate) RemoveBobbins(v ...*Bobbin) *PalletUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBobbinIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PalletUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PalletUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PalletUpdate) check() error {
	if v, ok := _u.mutation.PalletCode(); ok {
		if err := pallet.PalletCodeValidator(v); err != nil {
			return &ValidationError{Name: "pallet_code", err: fmt.Errorf(`ent: validator failed for field "Pallet.pallet_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := pallet.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Pallet.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BobbinsCount(); ok {
		if err := pallet.BobbinsCountValidator(v); err != nil {
			return &ValidationError{Name: "bobbins_count", err: fmt.Errorf(`ent: validator failed for field "Pallet.bobbins_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NetWeight(); ok {
		if err := pallet.NetWeightValidator(v); err != nil {
			return &ValidationError{Name: "net_weight", err: fmt.Errorf(`ent: validator failed for field "Pallet.net_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrossWeight(); ok {
		if err := pallet.GrossWeightValidator(v); err != nil {
			return &ValidationError{Name: "gross_weight", err: fmt.Errorf(`ent: validator failed for field "Pallet.gross_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TareWeight(); ok {
		if err := pallet.TareWeightValidator(v); err != nil {
			return &ValidationError{Name: "tare_weight", err: fmt.Errorf(`ent: validator failed for field "Pallet.tare_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pallet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Pallet.status": %w`, err)}
		}
	}
	if _u.mutation.LotCleared() && len(_u.mutation.LotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pallet.lot"`)
	}
	return nil
}

func (_u *PalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pallet.Table, pallet.Columns, sqlgraph.NewFieldSpec(pallet.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PalletCode(); ok {
		_spec.SetField(pallet.FieldPalletCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(pallet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(pallet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BobbinsCount(); ok {
		_spec.SetField(pallet.FieldBobbinsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBobbinsCount(); ok {
		_spec.AddField(pallet.FieldBobbinsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NetWeight(); ok {
		_spec.SetField(pallet.FieldNetWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNetWeight(); ok {
		_spec.AddField(pallet.FieldNetWeight, field.TypeFloat64, value)
	}
	if _u.mutation.NetWeightCleared() {
		_spec.ClearField(pallet.FieldNetWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GrossWeight(); ok {
		_spec.SetField(pallet.FieldGrossWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrossWeight(); ok {
		_spec.AddField(pallet.FieldGrossWeight, field.TypeFloat64, value)
	}
	if _u.mutation.GrossWeightCleared() {
		_spec.ClearField(pallet.FieldGrossWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TareWeight(); ok {
		_spec.SetField(pallet.FieldTareWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTareWeight(); ok {
		_spec.AddField(pallet.FieldTareWeight, field.TypeFloat64, value)
	}
	if _u.mutation.TareWeightCleared() {
		_spec.ClearField(pallet.FieldTareWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pallet.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PalletizerID(); ok {
		_spec.SetField(pallet.FieldPalletizerID, field.TypeUUID, value)
	}
	if _u.mutation.PalletizerIDCleared() {
		_spec.ClearField(pallet.FieldPalletizerID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Printed(); ok {
		_spec.SetField(pallet.FieldPrinted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PrintedAt(); ok {
		_spec.SetField(pallet.FieldPrintedAt, field.TypeTime, value)
	}
	if _u.mutation.PrintedAtCleared() {
		_spec.ClearField(pallet.FieldPrintedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(pallet.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(pallet.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pallet.LotTable,
			Columns: []string{pallet.LotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lot.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pallet.LotTable,
			Columns: []string{pallet.LotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lot.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBobbinsIDs(); len(nodes) > 0 && !_u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BobbinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PalletUpdateOne is the builder for updating a single Pallet entity.
type PalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PalletMutation
}

// SetPalletCode sets the "pallet_code" field.
func (_u *PalletUpdateOne) SetPalletCode(v string) *PalletUpdateOne {
	_u.mutation.SetPalletCode(v)
	return _u
}

// SetNillablePalletCode sets the "pallet_code" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillablePalletCode(v *string) *PalletUpdateOne {
	if v != nil {
		_u.SetPalletCode(*v)
	}
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *PalletUpdateOne) SetLotID(v uuid.UUID) *PalletUpdateOne {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableLotID(v *uuid.UUID) *PalletUpdateOne {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *PalletUpdateOne) SetLevel(v int) *PalletUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableLevel(v *int) *PalletUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *PalletUpdateOne) AddLevel(v int) *PalletUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetBobbinsCount sets the "bobbins_count" field.
func (_u *PalletUpdateOne) SetBobbinsCount(v int) *PalletUpdateOne {
	_u.mutation.ResetBobbinsCount()
	_u.mutation.SetBobbinsCount(v)
	return _u
}

// SetNillableBobbinsCount sets the "bobbins_count" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableBobbinsCount(v *int) *PalletUpdateOne {
	if v != nil {
		_u.SetBobbinsCount(*v)
	}
	return _u
}

// AddBobbinsCount adds value to the "bobbins_count" field.
func (_u *PalletUpdateOne) AddBobbinsCount(v int) *PalletUpdateOne {
	_u.mutation.AddBobbinsCount(v)
	return _u
}

// SetNetWeight sets the "net_weight" field.
func (_u *PalletUpdateOne) SetNetWeight(v float64) *PalletUpdateOne {
	_u.mutation.ResetNetWeight()
	_u.mutation.SetNetWeight(v)
	return _u
}

// SetNillableNetWeight sets the "net_weight" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableNetWeight(v *float64) *PalletUpdateOne {
	if v != nil {
		_u.SetNetWeight(*v)
	}
	return _u
}

// AddNetWeight adds value to the "net_weight" field.
func (_u *PalletUpdateOne) AddNetWeight(v float64) *PalletUpdateOne {
	_u.mutation.AddNetWeight(v)
	return _u
}

// ClearNetWeight clears the value of the "net_weight" field.
func (_u *PalletUpdateOne) ClearNetWeight() *PalletUpdateOne {
	_u.mutation.ClearNetWeight()
	return _u
}

// SetGrossWeight sets the "gross_weight" field.
func (_u *PalletUpdateOne) SetGrossWeight(v float64) *PalletUpdateOne {
	_u.mutation.ResetGrossWeight()
	_u.mutation.SetGrossWeight(v)
	return _u
}

// SetNillableGrossWeight sets the "gross_weight" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableGrossWeight(v *float64) *PalletUpdateOne {
	if v != nil {
		_u.SetGrossWeight(*v)
	}
	return _u
}

// AddGrossWeight adds value to the "gross_weight" field.
func (_u *PalletUpdateOne) AddGrossWeight(v float64) *PalletUpdateOne {
	_u.mutation.AddGrossWeight(v)
	return _u
}

// ClearGrossWeight clears the value of the "gross_weight" field.
func (_u *PalletUpdateOne) ClearGrossWeight() *PalletUpdateOne {
	_u.mutation.ClearGrossWeight()
	return _u
}

// SetTareWeight sets the "tare_weight" field.
func (_u *PalletUpdateOne) SetTareWeight(v float64) *PalletUpdateOne {
	_u.mutation.ResetTareWeight()
	_u.mutation.SetTareWeight(v)
	return _u
}

// SetNillableTareWeight sets the "tare_weight" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableTareWeight(v *float64) *PalletUpdateOne {
	if v != nil {
		_u.SetTareWeight(*v)
	}
	return _u
}

// AddTareWeight adds value to the "tare_weight" field.
func (_u *PalletUpdateOne) AddTareWeight(v float64) *PalletUpdateOne {
	_u.mutation.AddTareWeight(v)
	return _u
}

// ClearTareWeight clears the value of the "tare_weight" field.
func (_u *PalletUpdateOne) ClearTareWeight() *PalletUpdateOne {
	_u.mutation.ClearTareWeight()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PalletUpdateOne) SetStatus(v pallet.Status) *PalletUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableStatus(v *pallet.Status) *PalletUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPalletizerID sets the "palletizer_id" field.
func (_u *PalletUpdateOne) SetPalletizerID(v uuid.UUID) *PalletUpdateOne {
	_u.mutation.SetPalletizerID(v)
	return _u
}

// SetNillablePalletizerID sets the "palletizer_id" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillablePalletizerID(v *uuid.UUID) *PalletUpdateOne {
	if v != nil {
		_u.SetPalletizerID(*v)
	}
	return _u
}

// ClearPalletizerID clears the value of the "palletizer_id" field.
func (_u *PalletUpdateOne) ClearPalletizerID() *PalletUpdateOne {
	_u.mutation.ClearPalletizerID()
	return _u
}

// SetPrinted sets the "printed" field.
func (_u *PalletUpdateOne) SetPrinted(v bool) *PalletUpdateOne {
	_u.mutation.SetPrinted(v)
	return _u
}

// SetNillablePrinted sets the "printed" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillablePrinted(v *bool) *PalletUpdateOne {
	if v != nil {
		_u.SetPrinted(*v)
	}
	return _u
}

// SetPrintedAt sets the "printed_at" field.
func (_u *PalletUpdateOne) SetPrintedAt(v time.Time) *PalletUpdateOne {
	_u.mutation.SetPrintedAt(v)
	return _u
}

// SetNillablePrintedAt sets the "printed_at" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillablePrintedAt(v *time.Time) *PalletUpdateOne {
	if v != nil {
		_u.SetPrintedAt(*v)
	}
	return _u
}

// ClearPrintedAt clears the value of the "printed_at" field.
func (_u *PalletUpdateOne) ClearPrintedAt() *PalletUpdateOne {
	_u.mutation.ClearPrintedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PalletUpdateOne) SetCompletedAt(v time.Time) *PalletUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PalletUpdateOne) SetNillableCompletedAt(v *time.Time) *PalletUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PalletUpdateOne) ClearCompletedAt() *PalletUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PalletUpdateOne) SetUpdatedAt(v time.Time) *PalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLot sets the "lot" edge to the Lot entity.
func (_u *PalletUpdateOne) SetLot(v *Lot) *PalletUpdateOne {
	return _u.SetLotID(v.ID)
}

// AddBobbinIDs adds the "bobbins" edge to the Bobbin entity by IDs.
func (_u *PalletUpdateOne) AddBobbinIDs(ids ...uuid.UUID) *PalletUpdateOne {
	_u.mutation.AddBobbinIDs(ids...)
	return _u
}

// AddBobbins adds the "bobbins" edges to the Bobbin entity.
func (_u *PalletUpdateOne) AddBobbins(v ...*Bobbin) *PalletUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBobbinIDs(ids...)
}

// Mutation returns the PalletMutation object of the builder.
func (_u *PalletUpdateOne) Mutation() *PalletMutation {
	return _u.mutation
}

// ClearLot clears the "lot" edge to the Lot entity.
func (_u *PalletUpdateOne) ClearLot() *PalletUpdateOne {
	_u.mutation.ClearLot()
	return _u
}

// ClearBobbins clears all "bobbins" edges to the Bobbin entity.
func (_u *PalletUpdateOne) ClearBobbins() *PalletUpdateOne {
	_u.mutation.ClearBobbins()
	return _u
}

// RemoveBobbinIDs removes the "bobbins" edge to Bobbin entities by IDs.
func (_u *PalletUpdateOne) RemoveBobbinIDs(ids ...uuid.UUID) *PalletUpdateOne {
	_u.mutation.RemoveBobbinIDs(ids...)
	return _u
}

// RemoveBobbins removes "bobbins" edges to Bobbin entities.
func (_u *PalletUpdateOne) RemoveBobbins(v ...*Bobbin) *PalletUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBobbinIDs(ids...)
}

// Where appends a list predicates to the PalletUpdate builder.
func (_u *PalletUpdateOne) Where(ps ...predicate.Pallet) *PalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PalletUpdateOne) Select(field string, fields ...string) *PalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pallet entity.
func (_u *PalletUpdateOne) Save(ctx context.Context) (*Pallet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PalletUpdateOne) SaveX(ctx context.Context) *Pallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PalletUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PalletUpdateOne) check() error {
	if v, ok := _u.mutation.PalletCode(); ok {
		if err := pallet.PalletCodeValidator(v); err != nil {
			return &ValidationError{Name: "pallet_code", err: fmt.Errorf(`ent: validator failed for field "Pallet.pallet_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := pallet.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Pallet.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BobbinsCount(); ok {
		if err := pallet.BobbinsCountValidator(v); err != nil {
			return &ValidationError{Name: "bobbins_count", err: fmt.Errorf(`ent: validator failed for field "Pallet.bobbins_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NetWeight(); ok {
		if err := pallet.NetWeightValidator(v); err != nil {
			return &ValidationError{Name: "net_weight", err: fmt.Errorf(`ent: validator failed for field "Pallet.net_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrossWeight(); ok {
		if err := pallet.GrossWeightValidator(v); err != nil {
			return &ValidationError{Name: "gross_weight", err: fmt.Errorf(`ent: validator failed for field "Pallet.gross_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TareWeight(); ok {
		if err := pallet.TareWeightValidator(v); err != nil {
			return &ValidationError{Name: "tare_weight", err: fmt.Errorf(`ent: validator failed for field "Pallet.tare_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pallet.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Pallet.status": %w`, err)}
		}
	}
	if _u.mutation.LotCleared() && len(_u.mutation.LotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pallet.lot"`)
	}
	return nil
}

func (_u *PalletUpdateOne) sqlSave(ctx context.Context) (_node *Pallet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pallet.Table, pallet.Columns, sqlgraph.NewFieldSpec(pallet.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pallet.FieldID)
		for _, f := range fields {
			if !pallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PalletCode(); ok {
		_spec.SetField(pallet.FieldPalletCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(pallet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(pallet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BobbinsCount(); ok {
		_spec.SetField(pallet.FieldBobbinsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBobbinsCount(); ok {
		_spec.AddField(pallet.FieldBobbinsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NetWeight(); ok {
		_spec.SetField(pallet.FieldNetWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNetWeight(); ok {
		_spec.AddField(pallet.FieldNetWeight, field.TypeFloat64, value)
	}
	if _u.mutation.NetWeightCleared() {
		_spec.ClearField(pallet.FieldNetWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GrossWeight(); ok {
		_spec.SetField(pallet.FieldGrossWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrossWeight(); ok {
		_spec.AddField(pallet.FieldGrossWeight, field.TypeFloat64, value)
	}
	if _u.mutation.GrossWeightCleared() {
		_spec.ClearField(pallet.FieldGrossWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TareWeight(); ok {
		_spec.SetField(pallet.FieldTareWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTareWeight(); ok {
		_spec.AddField(pallet.FieldTareWeight, field.TypeFloat64, value)
	}
	if _u.mutation.TareWeightCleared() {
		_spec.ClearField(pallet.FieldTareWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pallet.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PalletizerID(); ok {
		_spec.SetField(pallet.FieldPalletizerID, field.TypeUUID, value)
	}
	if _u.mutation.PalletizerIDCleared() {
		_spec.ClearField(pallet.FieldPalletizerID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Printed(); ok {
		_spec.SetField(pallet.FieldPrinted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PrintedAt(); ok {
		_spec.SetField(pallet.FieldPrintedAt, field.TypeTime, value)
	}
	if _u.mutation.PrintedAtCleared() {
		_spec.ClearField(pallet.FieldPrintedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(pallet.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(pallet.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pallet.LotTable,
			Columns: []string{pallet.LotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lot.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pallet.LotTable,
			Columns: []string{pallet.LotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lot.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBobbinsIDs(); len(nodes) > 0 && !_u.mutation.BobbinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BobbinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pallet.BobbinsTable,
			Columns: []string{pallet.BobbinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bobbin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
