// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/order"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
	"github.com/yourusername/igh-silkroad/internal/database/ent/project"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectNumber sets the "project_number" field.
func (_u *ProjectUpdate) SetProjectNumber(v string) *ProjectUpdate {
	_u.mutation.SetProjectNumber(v)
	return _u
}

// SetNillableProjectNumber sets the "project_number" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableProjectNumber(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetProjectNumber(*v)
	}
	return _u
}

// SetProjectName sets the "project_name" field.
func (_u *ProjectUpdate) SetProjectName(v string) *ProjectUpdate {
	_u.mutation.SetProjectName(v)
	return _u
}

// SetNillableProjectName sets the "project_name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableProjectName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetProjectName(*v)
	}
	return _u
}

// SetProductType sets the "product_type" field.
func (_u *ProjectUpdate) SetProductType(v project.ProductType) *ProjectUpdate {
	_u.mutation.SetProductType(v)
	return _u
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableProductType(v *project.ProductType) *ProjectUpdate {
	if v != nil {
		_u.SetProductType(*v)
	}
	return _u
}

// SetProductSpec sets the "product_spec" field.
func (_u *ProjectUpdate) SetProductSpec(v string) *ProjectUpdate {
	_u.mutation.SetProductSpec(v)
	return _u
}

// SetNillableProductSpec sets the "product_spec" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableProductSpec(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetProductSpec(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProjectUpdate) SetStatus(v project.Status) *ProjectUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableStatus(v *project.Status) *ProjectUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPlannedQuantity sets the "planned_quantity" field.
func (_u *ProjectUpdate) SetPlannedQuantity(v int) *ProjectUpdate {
	_u.mutation.ResetPlannedQuantity()
	_u.mutation.SetPlannedQuantity(v)
	return _u
}

// SetNillablePlannedQuantity sets the "planned_quantity" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillablePlannedQuantity(v *int) *ProjectUpdate {
	if v != nil {
		_u.SetPlannedQuantity(*v)
	}
	return _u
}

// AddPlannedQuantity adds value to the "planned_quantity" field.
func (_u *ProjectUpdate) AddPlannedQuantity(v int) *ProjectUpdate {
	_u.mutation.AddPlannedQuantity(v)
	return _u
}

// ClearPlannedQuantity clears the value of the "planned_quantity" field.
func (_u *ProjectUpdate) ClearPlannedQuantity() *ProjectUpdate {
	_u.mutation.ClearPlannedQuantity()
	return _u
}

// SetActualQuantity sets the "actual_quantity" field.
func (_u *ProjectUpdate) SetActualQuantity(v int) *ProjectUpdate {
	_u.mutation.ResetActualQuantity()
	_u.mutation.SetActualQuantity(v)
	return _u
}

// SetNillableActualQuantity sets the "actual_quantity" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableActualQuantity(v *int) *ProjectUpdate {
	if v != nil {
		_u.SetActualQuantity(*v)
	}
	return _u
}

// AddActualQuantity adds value to the "actual_quantity" field.
func (_u *ProjectUpdate) AddActualQuantity(v int) *ProjectUpdate {
	_u.mutation.AddActualQuantity(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ProjectUpdate) SetStartDate(v time.Time) *ProjectUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableStartDate(v *time.Time) *ProjectUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *ProjectUpdate) ClearStartDate() *ProjectUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ProjectUpdate) SetEndDate(v time.Time) *ProjectUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableEndDate(v *time.Time) *ProjectUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ProjectUpdate) ClearEndDate() *ProjectUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ProjectUpdate) SetNotes(v string) *ProjectUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableNotes(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ProjectUpdate) ClearNotes() *ProjectUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdate) SetUpdatedAt(v time.Time) *ProjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_u *ProjectUpdate) AddOrderIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the Order entity.
func (_u *ProjectUpdate) AddOrders(v ...*Order) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearOrders clears all "orders" edges to the Order entity.
func (_u *ProjectUpdate) ClearOrders() *ProjectUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to Order entities by IDs.
func (_u *ProjectUpdate) RemoveOrderIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to Order entities.
func (_u *ProjectUpdate) RemoveOrders(v ...*Order) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.ProjectNumber(); ok {
		if err := project.ProjectNumberValidator(v); err != nil {
			return &ValidationError{Name: "project_number", err: fmt.Errorf(`ent: validator failed for field "Project.project_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProjectName(); ok {
		if err := project.ProjectNameValidator(v); err != nil {
			return &ValidationError{Name: "project_name", err: fmt.Errorf(`ent: validator failed for field "Project.project_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductType(); ok {
		if err := project.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "Project.product_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductSpec(); ok {
		if err := project.ProductSpecValidator(v); err != nil {
			return &ValidationError{Name: "product_spec", err: fmt.Errorf(`ent: validator failed for field "Project.product_spec": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := project.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Project.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlannedQuantity(); ok {
		if err := project.PlannedQuantityValidator(v); err != nil {
			return &ValidationError{Name: "planned_quantity", err: fmt.Errorf(`ent: validator failed for field "Project.planned_quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualQuantity(); ok {
		if err := project.ActualQuantityValidator(v); err != nil {
			return &ValidationError{Name: "actual_quantity", err: fmt.Errorf(`ent: validator failed for field "Project.actual_quantity": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectNumber(); ok {
		_spec.SetField(project.FieldProjectNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectName(); ok {
		_spec.SetField(project.FieldProjectName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductType(); ok {
		_spec.SetField(project.FieldProductType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProductSpec(); ok {
		_spec.SetField(project.FieldProductSpec, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(project.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PlannedQuantity(); ok {
		_spec.SetField(project.FieldPlannedQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlannedQuantity(); ok {
		_spec.AddField(project.FieldPlannedQuantity, field.TypeInt, value)
	}
	if _u.mutation.PlannedQuantityCleared() {
		_spec.ClearField(project.FieldPlannedQuantity, field.TypeInt)
	}
	if value, ok := _u.mutation.ActualQuantity(); ok {
		_spec.SetField(project.FieldActualQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActualQuantity(); ok {
		_spec.AddField(project.FieldActualQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(project.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(project.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(project.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(project.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(project.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(project.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.OrdersTable,
			Columns: []string{project.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.OrdersTable,
			Columns: []string{project.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.OrdersTable,
			Columns: []string{project.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetProjectNumber sets the "project_number" field.
func (_u *ProjectUpdateOne) SetProjectNumber(v string) *ProjectUpdateOne {
	_u.mutation.SetProjectNumber(v)
	return _u
}

// SetNillableProjectNumber sets the "project_number" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableProjectNumber(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetProjectNumber(*v)
	}
	return _u
}

// SetProjectName sets the "project_name" field.
func (_u *ProjectUpdateOne) SetProjectName(v string) *ProjectUpdateOne {
	_u.mutation.SetProjectName(v)
	return _u
}

// SetNillableProjectName sets the "project_name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableProjectName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetProjectName(*v)
	}
	return _u
}

// SetProductType sets the "product_type" field.
func (_u *ProjectUpdateOne) SetProductType(v project.ProductType) *ProjectUpdateOne {
	_u.mutation.SetProductType(v)
	return _u
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableProductType(v *project.ProductType) *ProjectUpdateOne {
	if v != nil {
		_u.SetProductType(*v)
	}
	return _u
}

// SetProductSpec sets the "product_spec" field.
func (_u *ProjectUpdateOne) SetProductSpec(v string) *ProjectUpdateOne {
	_u.mutation.SetProductSpec(v)
	return _u
}

// SetNillableProductSpec sets the "product_spec" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableProductSpec(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetProductSpec(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProjectUpdateOne) SetStatus(v project.Status) *ProjectUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableStatus(v *project.Status) *ProjectUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPlannedQuantity sets the "planned_quantity" field.
func (_u *ProjectUpdateOne) SetPlannedQuantity(v int) *ProjectUpdateOne {
	_u.mutation.ResetPlannedQuantity()
	_u.mutation.SetPlannedQuantity(v)
	return _u
}

// SetNillablePlannedQuantity sets the "planned_quantity" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillablePlannedQuantity(v *int) *ProjectUpdateOne {
	if v != nil {
		_u.SetPlannedQuantity(*v)
	}
	return _u
}

// AddPlannedQuantity adds value to the "planned_quantity" field.
func (_u *ProjectUpdateOne) AddPlannedQuantity(v int) *ProjectUpdateOne {
	_u.mutation.AddPlannedQuantity(v)
	return _u
}

// ClearPlannedQuantity clears the value of the "planned_quantity" field.
func (_u *ProjectUpdateOne) ClearPlannedQuantity() *ProjectUpdateOne {
	_u.mutation.ClearPlannedQuantity()
	return _u
}

// SetActualQuantity sets the "actual_quantity" field.
func (_u *ProjectUpdateOne) SetActualQuantity(v int) *ProjectUpdateOne {
	_u.mutation.ResetActualQuantity()
	_u.mutation.SetActualQuantity(v)
	return _u
}

// SetNillableActualQuantity sets the "actual_quantity" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableActualQuantity(v *int) *ProjectUpdateOne {
	if v != nil {
		_u.SetActualQuantity(*v)
	}
	return _u
}

// AddActualQuantity adds value to the "actual_quantity" field.
func (_u *ProjectUpdateOne) AddActualQuantity(v int) *ProjectUpdateOne {
	_u.mutation.AddActualQuantity(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ProjectUpdateOne) SetStartDate(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableStartDate(v *time.Time) *ProjectUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *ProjectUpdateOne) ClearStartDate() *ProjectUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ProjectUpdateOne) SetEndDate(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableEndDate(v *time.Time) *ProjectUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ProjectUpdateOne) ClearEndDate() *ProjectUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ProjectUpdateOne) SetNotes(v string) *ProjectUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableNotes(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ProjectUpdateOne) ClearNotes() *ProjectUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdateOne) SetUpdatedAt(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_u *ProjectUpdateOne) AddOrderIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the Order entity.
func (_u *ProjectUpdateOne) AddOrders(v ...*Order) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearOrders clears all "orders" edges to the Order entity.
func (_u *ProjectUpdateOne) ClearOrders() *ProjectUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to Order entities by IDs.
func (_u *ProjectUpdateOne) RemoveOrderIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to Order entities.
func (_u *ProjectUpdateOne) RemoveOrders(v ...*Order) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.ProjectNumber(); ok {
		if err := project.ProjectNumberValidator(v); err != nil {
			return &ValidationError{Name: "project_number", err: fmt.Errorf(`ent: validator failed for field "Project.project_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProjectName(); ok {
		if err := project.ProjectNameValidator(v); err != nil {
			return &ValidationError{Name: "project_name", err: fmt.Errorf(`ent: validator failed for field "Project.project_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductType(); ok {
		if err := project.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "Project.product_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductSpec(); ok {
		if err := project.ProductSpecValidator(v); err != nil {
			return &ValidationError{Name: "product_spec", err: fmt.Errorf(`ent: validator failed for field "Project.product_spec": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := project.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Project.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlannedQuantity(); ok {
		if err := project.PlannedQuantityValidator(v); err != nil {
			return &ValidationError{Name: "planned_quantity", err: fmt.Errorf(`ent: validator failed for field "Project.planned_quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualQuantity(); ok {
		if err := project.ActualQuantityValidator(v); err != nil {
			return &ValidationError{Name: "actual_quantity", err: fmt.Errorf(`ent: validator failed for field "Project.actual_quantity": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectNumber(); ok {
		_spec.SetField(project.FieldProjectNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectName(); ok {
		_spec.SetField(project.FieldProjectName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductType(); ok {
		_spec.SetField(project.FieldProductType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProductSpec(); ok {
		_spec.SetField(project.FieldProductSpec, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(project.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PlannedQuantity(); ok {
		_spec.SetField(project.FieldPlannedQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlannedQuantity(); ok {
		_spec.AddField(project.FieldPlannedQuantity, field.TypeInt, value)
	}
	if _u.mutation.PlannedQuantityCleared() {
		_spec.ClearField(project.FieldPlannedQuantity, field.TypeInt)
	}
	if value, ok := _u.mutation.ActualQuantity(); ok {
		_spec.SetField(project.FieldActualQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActualQuantity(); ok {
		_spec.AddField(project.FieldActualQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(project.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(project.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(project.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(project.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(project.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(project.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.OrdersTable,
			Columns: []string{project.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.OrdersTable,
			Columns: []string{project.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.OrdersTable,
			Columns: []string{project.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
