// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/bobbin"
	"github.com/yourusername/igh-silkroad/internal/database/ent/carton"
	"github.com/yourusername/igh-silkroad/internal/database/ent/doffing"
	"github.com/yourusername/igh-silkroad/internal/database/ent/lot"
	"github.com/yourusername/igh-silkroad/internal/database/ent/order"
	"github.com/yourusername/igh-silkroad/internal/database/ent/pallet"
	"github.com/yourusername/igh-silkroad/internal/database/ent/project"
	"github.com/yourusername/igh-silkroad/internal/database/ent/schema"
	"github.com/yourusername/igh-silkroad/internal/database/ent/spinningline"
	"github.com/yourusername/igh-silkroad/internal/database/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bobbinFields := schema.Bobbin{}.Fields()
	_ = bobbinFields
	// bobbinDescBobbinNumber is the schema descriptor for bobbin_number field.
	bobbinDescBobbinNumber := bobbinFields[1].Descriptor()
	// bobbin.BobbinNumberValidator is a validator for the "bobbin_number" field. It is called by the builders before save.
	bobbin.BobbinNumberValidator = func() func(string) error {
		validators := bobbinDescBobbinNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(bobbin_number string) error {
			for _, fn := range fns {
				if err := fn(bobbin_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bobbinDescSpinningPosition is the schema descriptor for spinning_position field.
	bobbinDescSpinningPosition := bobbinFields[3].Descriptor()
	// bobbin.SpinningPositionValidator is a validator for the "spinning_position" field. It is called by the builders before save.
	bobbin.SpinningPositionValidator = bobbinDescSpinningPosition.Validators[0].(func(int) error)
	// bobbinDescGrossWeight is the schema descriptor for gross_weight field.
	bobbinDescGrossWeight := bobbinFields[4].Descriptor()
	// bobbin.GrossWeightValidator is a validator for the "gross_weight" field. It is called by the builders before save.
	bobbin.GrossWeightValidator = bobbinDescGrossWeight.Validators[0].(func(float64) error)
	// bobbinDescNetWeight is the schema descriptor for net_weight field.
	bobbinDescNetWeight := bobbinFields[5].Descriptor()
	// bobbin.NetWeightValidator is a validator for the "net_weight" field. It is called by the builders before save.
	bobbin.NetWeightValidator = bobbinDescNetWeight.Validators[0].(func(float64) error)
	// bobbinDescTareWeight is the schema descriptor for tare_weight field.
	bobbinDescTareWeight := bobbinFields[6].Descriptor()
	// bobbin.TareWeightValidator is a validator for the "tare_weight" field. It is called by the builders before save.
	bobbin.TareWeightValidator = bobbinDescTareWeight.Validators[0].(func(float64) error)
	// bobbinDescGrade is the schema descriptor for grade field.
	bobbinDescGrade := bobbinFields[7].Descriptor()
	// bobbin.GradeValidator is a validator for the "grade" field. It is called by the builders before save.
	bobbin.GradeValidator = bobbinDescGrade.Validators[0].(func(string) error)
	// bobbinDescLabelPrinted is the schema descriptor for label_printed field.
	bobbinDescLabelPrinted := bobbinFields[11].Descriptor()
	// bobbin.DefaultLabelPrinted holds the default value on creation for the label_printed field.
	bobbin.DefaultLabelPrinted = bobbinDescLabelPrinted.Default.(bool)
	// bobbinDescCreatedAt is the schema descriptor for created_at field.
	bobbinDescCreatedAt := bobbinFields[14].Descriptor()
	// bobbin.DefaultCreatedAt holds the default value on creation for the created_at field.
	bobbin.DefaultCreatedAt = bobbinDescCreatedAt.Default.(func() time.Time)
	// bobbinDescUpdatedAt is the schema descriptor for updated_at field.
	bobbinDescUpdatedAt := bobbinFields[15].Descriptor()
	// bobbin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bobbin.DefaultUpdatedAt = bobbinDescUpdatedAt.Default.(func() time.Time)
	// bobbin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bobbin.UpdateDefaultUpdatedAt = bobbinDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bobbinDescID is the schema descriptor for id field.
	bobbinDescID := bobbinFields[0].Descriptor()
	// bobbin.DefaultID holds the default value on creation for the id field.
	bobbin.DefaultID = bobbinDescID.Default.(func() uuid.UUID)
	cartonFields := schema.Carton{}.Fields()
	_ = cartonFields
	// cartonDescCartonNumber is the schema descriptor for carton_number field.
	cartonDescCartonNumber := cartonFields[1].Descriptor()
	// carton.CartonNumberValidator is a validator for the "carton_number" field. It is called by the builders before save.
	carton.CartonNumberValidator = func() func(string) error {
		validators := cartonDescCartonNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(carton_number string) error {
			for _, fn := range fns {
				if err := fn(carton_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// cartonDescBobbinCount is the schema descriptor for bobbin_count field.
	cartonDescBobbinCount := cartonFields[3].Descriptor()
	// carton.DefaultBobbinCount holds the default value on creation for the bobbin_count field.
	carton.DefaultBobbinCount = cartonDescBobbinCount.Default.(int)
	// carton.BobbinCountValidator is a validator for the "bobbin_count" field. It is called by the builders before save.
	carton.BobbinCountValidator = cartonDescBobbinCount.Validators[0].(func(int) error)
	// cartonDescTotalWeight is the schema descriptor for total_weight field.
	cartonDescTotalWeight := cartonFields[4].Descriptor()
	// carton.TotalWeightValidator is a validator for the "total_weight" field. It is called by the builders before save.
	carton.TotalWeightValidator = cartonDescTotalWeight.Validators[0].(func(float64) error)
	// cartonDescLabelPrinted is the schema descriptor for label_printed field.
	cartonDescLabelPrinted := cartonFields[6].Descriptor()
	// carton.DefaultLabelPrinted holds the default value on creation for the label_printed field.
	carton.DefaultLabelPrinted = cartonDescLabelPrinted.Default.(bool)
	// cartonDescCreatedAt is the schema descriptor for created_at field.
	cartonDescCreatedAt := cartonFields[9].Descriptor()
	// carton.DefaultCreatedAt holds the default value on creation for the created_at field.
	carton.DefaultCreatedAt = cartonDescCreatedAt.Default.(func() time.Time)
	// cartonDescUpdatedAt is the schema descriptor for updated_at field.
	cartonDescUpdatedAt := cartonFields[10].Descriptor()
	// carton.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	carton.DefaultUpdatedAt = cartonDescUpdatedAt.Default.(func() time.Time)
	// carton.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	carton.UpdateDefaultUpdatedAt = cartonDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cartonDescID is the schema descriptor for id field.
	cartonDescID := cartonFields[0].Descriptor()
	// carton.DefaultID holds the default value on creation for the id field.
	carton.DefaultID = cartonDescID.Default.(func() uuid.UUID)
	doffingFields := schema.Doffing{}.Fields()
	_ = doffingFields
	// doffingDescSpinningPosition is the schema descriptor for spinning_position field.
	doffingDescSpinningPosition := doffingFields[2].Descriptor()
	// doffing.SpinningPositionValidator is a validator for the "spinning_position" field. It is called by the builders before save.
	doffing.SpinningPositionValidator = doffingDescSpinningPosition.Validators[0].(func(int) error)
	// doffingDescBobbinNumber is the schema descriptor for bobbin_number field.
	doffingDescBobbinNumber := doffingFields[6].Descriptor()
	// doffing.BobbinNumberValidator is a validator for the "bobbin_number" field. It is called by the builders before save.
	doffing.BobbinNumberValidator = doffingDescBobbinNumber.Validators[0].(func(string) error)
	// doffingDescActualWeight is the schema descriptor for actual_weight field.
	doffingDescActualWeight := doffingFields[7].Descriptor()
	// doffing.ActualWeightValidator is a validator for the "actual_weight" field. It is called by the builders before save.
	doffing.ActualWeightValidator = doffingDescActualWeight.Validators[0].(func(float64) error)
	// doffingDescGrade is the schema descriptor for grade field.
	doffingDescGrade := doffingFields[8].Descriptor()
	// doffing.GradeValidator is a validator for the "grade" field. It is called by the builders before save.
	doffing.GradeValidator = doffingDescGrade.Validators[0].(func(string) error)
	// doffingDescDoffingTime is the schema descriptor for doffing_time field.
	doffingDescDoffingTime := doffingFields[10].Descriptor()
	// doffing.DefaultDoffingTime holds the default value on creation for the doffing_time field.
	doffing.DefaultDoffingTime = doffingDescDoffingTime.Default.(func() time.Time)
	// doffingDescCreatedAt is the schema descriptor for created_at field.
	doffingDescCreatedAt := doffingFields[12].Descriptor()
	// doffing.DefaultCreatedAt holds the default value on creation for the created_at field.
	doffing.DefaultCreatedAt = doffingDescCreatedAt.Default.(func() time.Time)
	// doffingDescUpdatedAt is the schema descriptor for updated_at field.
	doffingDescUpdatedAt := doffingFields[13].Descriptor()
	// doffing.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	doffing.DefaultUpdatedAt = doffingDescUpdatedAt.Default.(func() time.Time)
	// doffing.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	doffing.UpdateDefaultUpdatedAt = doffingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// doffingDescID is the schema descriptor for id field.
	doffingDescID := doffingFields[0].Descriptor()
	// doffing.DefaultID holds the default value on creation for the id field.
	doffing.DefaultID = doffingDescID.Default.(func() uuid.UUID)
	lotFields := schema.Lot{}.Fields()
	_ = lotFields
	// lotDescLotNumber is the schema descriptor for lot_number field.
	lotDescLotNumber := lotFields[1].Descriptor()
	// lot.LotNumberValidator is a validator for the "lot_number" field. It is called by the builders before save.
	lot.LotNumberValidator = func() func(string) error {
		validators := lotDescLotNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(lot_number string) error {
			for _, fn := range fns {
				if err := fn(lot_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// lotDescProductSpec is the schema descriptor for product_spec field.
	lotDescProductSpec := lotFields[4].Descriptor()
	// lot.ProductSpecValidator is a validator for the "product_spec" field. It is called by the builders before save.
	lot.ProductSpecValidator = lotDescProductSpec.Validators[0].(func(string) error)
	// lotDescPlannedQuantity is the schema descriptor for planned_quantity field.
	lotDescPlannedQuantity := lotFields[5].Descriptor()
	// lot.PlannedQuantityValidator is a validator for the "planned_quantity" field. It is called by the builders before save.
	lot.PlannedQuantityValidator = lotDescPlannedQuantity.Validators[0].(func(int) error)
	// lotDescActualQuantity is the schema descriptor for actual_quantity field.
	lotDescActualQuantity := lotFields[6].Descriptor()
	// lot.DefaultActualQuantity holds the default value on creation for the actual_quantity field.
	lot.DefaultActualQuantity = lotDescActualQuantity.Default.(int)
	// lot.ActualQuantityValidator is a validator for the "actual_quantity" field. It is called by the builders before save.
	lot.ActualQuantityValidator = lotDescActualQuantity.Validators[0].(func(int) error)
	// lotDescIsLocked is the schema descriptor for is_locked field.
	lotDescIsLocked := lotFields[10].Descriptor()
	// lot.DefaultIsLocked holds the default value on creation for the is_locked field.
	lot.DefaultIsLocked = lotDescIsLocked.Default.(bool)
	// lotDescCreatedAt is the schema descriptor for created_at field.
	lotDescCreatedAt := lotFields[11].Descriptor()
	// lot.DefaultCreatedAt holds the default value on creation for the created_at field.
	lot.DefaultCreatedAt = lotDescCreatedAt.Default.(func() time.Time)
	// lotDescUpdatedAt is the schema descriptor for updated_at field.
	lotDescUpdatedAt := lotFields[12].Descriptor()
	// lot.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	lot.DefaultUpdatedAt = lotDescUpdatedAt.Default.(func() time.Time)
	// lot.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	lot.UpdateDefaultUpdatedAt = lotDescUpdatedAt.UpdateDefault.(func() time.Time)
	// lotDescID is the schema descriptor for id field.
	lotDescID := lotFields[0].Descriptor()
	// lot.DefaultID holds the default value on creation for the id field.
	lot.DefaultID = lotDescID.Default.(func() uuid.UUID)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescOrderNumber is the schema descriptor for order_number field.
	orderDescOrderNumber := orderFields[1].Descriptor()
	// order.OrderNumberValidator is a validator for the "order_number" field. It is called by the builders before save.
	order.OrderNumberValidator = func() func(string) error {
		validators := orderDescOrderNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(order_number string) error {
			for _, fn := range fns {
				if err := fn(order_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// orderDescProductSpec is the schema descriptor for product_spec field.
	orderDescProductSpec := orderFields[4].Descriptor()
	// order.ProductSpecValidator is a validator for the "product_spec" field. It is called by the builders before save.
	order.ProductSpecValidator = orderDescProductSpec.Validators[0].(func(string) error)
	// orderDescTargetQuantity is the schema descriptor for target_quantity field.
	orderDescTargetQuantity := orderFields[5].Descriptor()
	// order.TargetQuantityValidator is a validator for the "target_quantity" field. It is called by the builders before save.
	order.TargetQuantityValidator = orderDescTargetQuantity.Validators[0].(func(int) error)
	// orderDescActualQuantity is the schema descriptor for actual_quantity field.
	orderDescActualQuantity := orderFields[6].Descriptor()
	// order.DefaultActualQuantity holds the default value on creation for the actual_quantity field.
	order.DefaultActualQuantity = orderDescActualQuantity.Default.(int)
	// order.ActualQuantityValidator is a validator for the "actual_quantity" field. It is called by the builders before save.
	order.ActualQuantityValidator = orderDescActualQuantity.Validators[0].(func(int) error)
	// orderDescPriority is the schema descriptor for priority field.
	orderDescPriority := orderFields[8].Descriptor()
	// order.DefaultPriority holds the default value on creation for the priority field.
	order.DefaultPriority = orderDescPriority.Default.(int)
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[11].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderFields[12].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.DefaultID holds the default value on creation for the id field.
	order.DefaultID = orderDescID.Default.(func() uuid.UUID)
	palletFields := schema.Pallet{}.Fields()
	_ = palletFields
	// palletDescPalletNumber is the schema descriptor for pallet_number field.
	palletDescPalletNumber := palletFields[1].Descriptor()
	// pallet.PalletNumberValidator is a validator for the "pallet_number" field. It is called by the builders before save.
	pallet.PalletNumberValidator = func() func(string) error {
		validators := palletDescPalletNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(pallet_number string) error {
			for _, fn := range fns {
				if err := fn(pallet_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// palletDescBobbinCount is the schema descriptor for bobbin_count field.
	palletDescBobbinCount := palletFields[3].Descriptor()
	// pallet.DefaultBobbinCount holds the default value on creation for the bobbin_count field.
	pallet.DefaultBobbinCount = palletDescBobbinCount.Default.(int)
	// pallet.BobbinCountValidator is a validator for the "bobbin_count" field. It is called by the builders before save.
	pallet.BobbinCountValidator = palletDescBobbinCount.Validators[0].(func(int) error)
	// palletDescTotalWeight is the schema descriptor for total_weight field.
	palletDescTotalWeight := palletFields[4].Descriptor()
	// pallet.TotalWeightValidator is a validator for the "total_weight" field. It is called by the builders before save.
	pallet.TotalWeightValidator = palletDescTotalWeight.Validators[0].(func(float64) error)
	// palletDescLabelPrinted is the schema descriptor for label_printed field.
	palletDescLabelPrinted := palletFields[6].Descriptor()
	// pallet.DefaultLabelPrinted holds the default value on creation for the label_printed field.
	pallet.DefaultLabelPrinted = palletDescLabelPrinted.Default.(bool)
	// palletDescCreatedAt is the schema descriptor for created_at field.
	palletDescCreatedAt := palletFields[9].Descriptor()
	// pallet.DefaultCreatedAt holds the default value on creation for the created_at field.
	pallet.DefaultCreatedAt = palletDescCreatedAt.Default.(func() time.Time)
	// palletDescUpdatedAt is the schema descriptor for updated_at field.
	palletDescUpdatedAt := palletFields[10].Descriptor()
	// pallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pallet.DefaultUpdatedAt = palletDescUpdatedAt.Default.(func() time.Time)
	// pallet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pallet.UpdateDefaultUpdatedAt = palletDescUpdatedAt.UpdateDefault.(func() time.Time)
	// palletDescID is the schema descriptor for id field.
	palletDescID := palletFields[0].Descriptor()
	// pallet.DefaultID holds the default value on creation for the id field.
	pallet.DefaultID = palletDescID.Default.(func() uuid.UUID)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescProjectName is the schema descriptor for project_name field.
	projectDescProjectName := projectFields[1].Descriptor()
	// project.ProjectNameValidator is a validator for the "project_name" field. It is called by the builders before save.
	project.ProjectNameValidator = func() func(string) error {
		validators := projectDescProjectName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(project_name string) error {
			for _, fn := range fns {
				if err := fn(project_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// projectDescCustomerName is the schema descriptor for customer_name field.
	projectDescCustomerName := projectFields[3].Descriptor()
	// project.CustomerNameValidator is a validator for the "customer_name" field. It is called by the builders before save.
	project.CustomerNameValidator = projectDescCustomerName.Validators[0].(func(string) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[7].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[8].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	spinninglineFields := schema.SpinningLine{}.Fields()
	_ = spinninglineFields
	// spinninglineDescLineName is the schema descriptor for line_name field.
	spinninglineDescLineName := spinninglineFields[1].Descriptor()
	// spinningline.LineNameValidator is a validator for the "line_name" field. It is called by the builders before save.
	spinningline.LineNameValidator = func() func(string) error {
		validators := spinninglineDescLineName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(line_name string) error {
			for _, fn := range fns {
				if err := fn(line_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// spinninglineDescLineNumber is the schema descriptor for line_number field.
	spinninglineDescLineNumber := spinninglineFields[2].Descriptor()
	// spinningline.LineNumberValidator is a validator for the "line_number" field. It is called by the builders before save.
	spinningline.LineNumberValidator = spinninglineDescLineNumber.Validators[0].(func(string) error)
	// spinninglineDescLocation is the schema descriptor for location field.
	spinninglineDescLocation := spinninglineFields[3].Descriptor()
	// spinningline.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	spinningline.LocationValidator = spinninglineDescLocation.Validators[0].(func(string) error)
	// spinninglineDescCapacity is the schema descriptor for capacity field.
	spinninglineDescCapacity := spinninglineFields[4].Descriptor()
	// spinningline.CapacityValidator is a validator for the "capacity" field. It is called by the builders before save.
	spinningline.CapacityValidator = spinninglineDescCapacity.Validators[0].(func(int) error)
	// spinninglineDescCreatedAt is the schema descriptor for created_at field.
	spinninglineDescCreatedAt := spinninglineFields[7].Descriptor()
	// spinningline.DefaultCreatedAt holds the default value on creation for the created_at field.
	spinningline.DefaultCreatedAt = spinninglineDescCreatedAt.Default.(func() time.Time)
	// spinninglineDescUpdatedAt is the schema descriptor for updated_at field.
	spinninglineDescUpdatedAt := spinninglineFields[8].Descriptor()
	// spinningline.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	spinningline.DefaultUpdatedAt = spinninglineDescUpdatedAt.Default.(func() time.Time)
	// spinningline.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	spinningline.UpdateDefaultUpdatedAt = spinninglineDescUpdatedAt.UpdateDefault.(func() time.Time)
	// spinninglineDescID is the schema descriptor for id field.
	spinninglineDescID := spinninglineFields[0].Descriptor()
	// spinningline.DefaultID holds the default value on creation for the id field.
	spinningline.DefaultID = spinninglineDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescFullName is the schema descriptor for full_name field.
	userDescFullName := userFields[3].Descriptor()
	// user.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	user.FullNameValidator = func() func(string) error {
		validators := userDescFullName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(full_name string) error {
			for _, fn := range fns {
				if err := fn(full_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmployeeID is the schema descriptor for employee_id field.
	userDescEmployeeID := userFields[5].Descriptor()
	// user.EmployeeIDValidator is a validator for the "employee_id" field. It is called by the builders before save.
	user.EmployeeIDValidator = userDescEmployeeID.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[6].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[7].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[8].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[11].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
