// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/edge"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
	"github.com/yourusername/igh-silkroad/internal/database/ent/spinningline"
)

// SpinningLineUpdate is the builder for updating SpinningLine entities.
type SpinningLineUpdate struct {
	config
	hooks    []Hook
	mutation *SpinningLineMutation
}

// Where appends a list predicates to the SpinningLineUpdate builder.
func (_u *SpinningLineUpdate) Where(ps ...predicate.SpinningLine) *SpinningLineUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLineName sets the "line_name" field.
func (_u *SpinningLineUpdate) SetLineName(v string) *SpinningLineUpdate {
	_u.mutation.SetLineName(v)
	return _u
}

// SetNillableLineName sets the "line_name" field if the given value is not nil.
func (_u *SpinningLineUpdate) SetNillableLineName(v *string) *SpinningLineUpdate {
	if v != nil {
		_u.SetLineName(*v)
	}
	return _u
}

// SetLineNumber sets the "line_number" field.
func (_u *SpinningLineUpdate) SetLineNumber(v string) *SpinningLineUpdate {
	_u.mutation.SetLineNumber(v)
	return _u
}

// SetNillableLineNumber sets the "line_number" field if the given value is not nil.
func (_u *SpinningLineUpdate) SetNillableLineNumber(v *string) *SpinningLineUpdate {
	if v != nil {
		_u.SetLineNumber(*v)
	}
	return _u
}

// ClearLineNumber clears the value of the "line_number" field.
func (_u *SpinningLineUpdate) ClearLineNumber() *SpinningLineUpdate {
	_u.mutation.ClearLineNumber()
	return _u
}

// SetEdgeID sets the "edge_id" field.
func (_u *SpinningLineUpdate) SetEdgeID(v uuid.UUID) *SpinningLineUpdate {
	_u.mutation.SetEdgeID(v)
	return _u
}

// SetNillableEdgeID sets the "edge_id" field if the given value is not nil.
func (_u *SpinningLineUpdate) SetNillableEdgeID(v *uuid.UUID) *SpinningLineUpdate {
	if v != nil {
		_u.SetEdgeID(*v)
	}
	return _u
}

// ClearEdgeID clears the value of the "edge_id" field.
func (_u *SpinningLineUpdate) ClearEdgeID() *SpinningLineUpdate {
	_u.mutation.ClearEdgeID()
	return _u
}

// SetLocation sets the "location" field.
func (_u *SpinningLineUpdate) SetLocation(v string) *SpinningLineUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *SpinningLineUpdate) SetNillableLocation(v *string) *SpinningLineUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *SpinningLineUpdate) ClearLocation() *SpinningLineUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetCapacity sets the "capacity" field.
func (_u *SpinningLineUpdate) SetCapacity(v int) *SpinningLineUpdate {
	_u.mutation.ResetCapacity()
	_u.mutation.SetCapacity(v)
	return _u
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_u *SpinningLineUpdate) SetNillableCapacity(v *int) *SpinningLineUpdate {
	if v != nil {
		_u.SetCapacity(*v)
	}
	return _u
}

// AddCapacity adds value to the "capacity" field.
func (_u *SpinningLineUpdate) AddCapacity(v int) *SpinningLineUpdate {
	_u.mutation.AddCapacity(v)
	return _u
}

// ClearCapacity clears the value of the "capacity" field.
func (_u *SpinningLineUpdate) ClearCapacity() *SpinningLineUpdate {
	_u.mutation.ClearCapacity()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SpinningLineUpdate) SetStatus(v spinningline.Status) *SpinningLineUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SpinningLineUpdate) SetNillableStatus(v *spinningline.Status) *SpinningLineUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentLotID sets the "current_lot_id" field.
func (_u *SpinningLineUpdate) SetCurrentLotID(v uuid.UUID) *SpinningLineUpdate {
	_u.mutation.SetCurrentLotID(v)
	return _u
}

// SetNillableCurrentLotID sets the "current_lot_id" field if the given value is not nil.
func (_u *SpinningLineUpdate) SetNillableCurrentLotID(v *uuid.UUID) *SpinningLineUpdate {
	if v != nil {
		_u.SetCurrentLotID(*v)
	}
	return _u
}

// ClearCurrentLotID clears the value of the "current_lot_id" field.
func (_u *SpinningLineUpdate) ClearCurrentLotID() *SpinningLineUpdate {
	_u.mutation.ClearCurrentLotID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SpinningLineUpdate) SetUpdatedAt(v time.Time) *SpinningLineUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEdge sets the "edge" edge to the Edge entity.
func (_u *SpinningLineUpdate) SetEdge(v *Edge) *SpinningLineUpdate {
	return _u.SetEdgeID(v.ID)
}

// Mutation returns the SpinningLineMutation object of the builder.
func (_u *SpinningLineUpdate) Mutation() *SpinningLineMutation {
	return _u.mutation
}

// ClearEdgeEdge clears the "edge" edge to the Edge entity.
func (_u *SpinningLineUpdate) ClearEdgeEdge() *SpinningLineUpdate {
	_u.mutation.ClearEdgeEdge()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SpinningLineUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpinningLineUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SpinningLineUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpinningLineUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SpinningLineUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := spinningline.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpinningLineUpdate) check() error {
	if v, ok := _u.mutation.LineName(); ok {
		if err := spinningline.LineNameValidator(v); err != nil {
			return &ValidationError{Name: "line_name", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.line_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LineNumber(); ok {
		if err := spinningline.LineNumberValidator(v); err != nil {
			return &ValidationError{Name: "line_number", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.line_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Location(); ok {
		if err := spinningline.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.location": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Capacity(); ok {
		if err := spinningline.CapacityValidator(v); err != nil {
			return &ValidationError{Name: "capacity", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.capacity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := spinningline.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SpinningLineUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(spinningline.Table, spinningline.Columns, sqlgraph.NewFieldSpec(spinningline.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LineName(); ok {
		_spec.SetField(spinningline.FieldLineName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LineNumber(); ok {
		_spec.SetField(spinningline.FieldLineNumber, field.TypeString, value)
	}
	if _u.mutation.LineNumberCleared() {
		_spec.ClearField(spinningline.FieldLineNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(spinningline.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(spinningline.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Capacity(); ok {
		_spec.SetField(spinningline.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacity(); ok {
		_spec.AddField(spinningline.FieldCapacity, field.TypeInt, value)
	}
	if _u.mutation.CapacityCleared() {
		_spec.ClearField(spinningline.FieldCapacity, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(spinningline.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentLotID(); ok {
		_spec.SetField(spinningline.FieldCurrentLotID, field.TypeUUID, value)
	}
	if _u.mutation.CurrentLotIDCleared() {
		_spec.ClearField(spinningline.FieldCurrentLotID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(spinningline.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EdgeEdgeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spinningline.EdgeTable,
			Columns: []string{spinningline.EdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spinningline.EdgeTable,
			Columns: []string{spinningline.EdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spinningline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SpinningLineUpdateOne is the builder for updating a single SpinningLine entity.
type SpinningLineUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpinningLineMutation
}

// SetLineName sets the "line_name" field.
func (_u *SpinningLineUpdateOne) SetLineName(v string) *SpinningLineUpdateOne {
	_u.mutation.SetLineName(v)
	return _u
}

// SetNillableLineName sets the "line_name" field if the given value is not nil.
func (_u *SpinningLineUpdateOne) SetNillableLineName(v *string) *SpinningLineUpdateOne {
	if v != nil {
		_u.SetLineName(*v)
	}
	return _u
}

// SetLineNumber sets the "line_number" field.
func (_u *SpinningLineUpdateOne) SetLineNumber(v string) *SpinningLineUpdateOne {
	_u.mutation.SetLineNumber(v)
	return _u
}

// SetNillableLineNumber sets the "line_number" field if the given value is not nil.
func (_u *SpinningLineUpdateOne) SetNillableLineNumber(v *string) *SpinningLineUpdateOne {
	if v != nil {
		_u.SetLineNumber(*v)
	}
	return _u
}

// ClearLineNumber clears the value of the "line_number" field.
func (_u *SpinningLineUpdateOne) ClearLineNumber() *SpinningLineUpdateOne {
	_u.mutation.ClearLineNumber()
	return _u
}

// SetEdgeID sets the "edge_id" field.
func (_u *SpinningLineUpdateOne) SetEdgeID(v uuid.UUID) *SpinningLineUpdateOne {
	_u.mutation.SetEdgeID(v)
	return _u
}

// SetNillableEdgeID sets the "edge_id" field if the given value is not nil.
func (_u *SpinningLineUpdateOne) SetNillableEdgeID(v *uuid.UUID) *SpinningLineUpdateOne {
	if v != nil {
		_u.SetEdgeID(*v)
	}
	return _u
}

// ClearEdgeID clears the value of the "edge_id" field.
func (_u *SpinningLineUpdateOne) ClearEdgeID() *SpinningLineUpdateOne {
	_u.mutation.ClearEdgeID()
	return _u
}

// SetLocation sets the "location" field.
func (_u *SpinningLineUpdateOne) SetLocation(v string) *SpinningLineUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *SpinningLineUpdateOne) SetNillableLocation(v *string) *SpinningLineUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *SpinningLineUpdateOne) ClearLocation() *SpinningLineUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetCapacity sets the "capacity" field.
func (_u *SpinningLineUpdateOne) SetCapacity(v int) *SpinningLineUpdateOne {
	_u.mutation.ResetCapacity()
	_u.mutation.SetCapacity(v)
	return _u
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_u *SpinningLineUpdateOne) SetNillableCapacity(v *int) *SpinningLineUpdateOne {
	if v != nil {
		_u.SetCapacity(*v)
	}
	return _u
}

// AddCapacity adds value to the "capacity" field.
func (_u *SpinningLineUpdateOne) AddCapacity(v int) *SpinningLineUpdateOne {
	_u.mutation.AddCapacity(v)
	return _u
}

// ClearCapacity clears the value of the "capacity" field.
func (_u *SpinningLineUpdateOne) ClearCapacity() *SpinningLineUpdateOne {
	_u.mutation.ClearCapacity()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SpinningLineUpdateOne) SetStatus(v spinningline.Status) *SpinningLineUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SpinningLineUpdateOne) SetNillableStatus(v *spinningline.Status) *SpinningLineUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentLotID sets the "current_lot_id" field.
func (_u *SpinningLineUpdateOne) SetCurrentLotID(v uuid.UUID) *SpinningLineUpdateOne {
	_u.mutation.SetCurrentLotID(v)
	return _u
}

// SetNillableCurrentLotID sets the "current_lot_id" field if the given value is not nil.
func (_u *SpinningLineUpdateOne) SetNillableCurrentLotID(v *uuid.UUID) *SpinningLineUpdateOne {
	if v != nil {
		_u.SetCurrentLotID(*v)
	}
	return _u
}

// ClearCurrentLotID clears the value of the "current_lot_id" field.
func (_u *SpinningLineUpdateOne) ClearCurrentLotID() *SpinningLineUpdateOne {
	_u.mutation.ClearCurrentLotID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SpinningLineUpdateOne) SetUpdatedAt(v time.Time) *SpinningLineUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEdge sets the "edge" edge to the Edge entity.
func (_u *SpinningLineUpdateOne) SetEdge(v *Edge) *SpinningLineUpdateOne {
	return _u.SetEdgeID(v.ID)
}

// Mutation returns the SpinningLineMutation object of the builder.
func (_u *SpinningLineUpdateOne) Mutation() *SpinningLineMutation {
	return _u.mutation
}

// ClearEdgeEdge clears the "edge" edge to the Edge entity.
func (_u *SpinningLineUpdateOne) ClearEdgeEdge() *SpinningLineUpdateOne {
	_u.mutation.ClearEdgeEdge()
	return _u
}

// Where appends a list predicates to the SpinningLineUpdate builder.
func (_u *SpinningLineUpdateOne) Where(ps ...predicate.SpinningLine) *SpinningLineUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SpinningLineUpdateOne) Select(field string, fields ...string) *SpinningLineUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SpinningLine entity.
func (_u *SpinningLineUpdateOne) Save(ctx context.Context) (*SpinningLine, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpinningLineUpdateOne) SaveX(ctx context.Context) *SpinningLine {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SpinningLineUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpinningLineUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SpinningLineUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := spinningline.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpinningLineUpdateOne) check() error {
	if v, ok := _u.mutation.LineName(); ok {
		if err := spinningline.LineNameValidator(v); err != nil {
			return &ValidationError{Name: "line_name", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.line_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LineNumber(); ok {
		if err := spinningline.LineNumberValidator(v); err != nil {
			return &ValidationError{Name: "line_number", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.line_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Location(); ok {
		if err := spinningline.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.location": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Capacity(); ok {
		if err := spinningline.CapacityValidator(v); err != nil {
			return &ValidationError{Name: "capacity", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.capacity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := spinningline.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SpinningLine.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SpinningLineUpdateOne) sqlSave(ctx context.Context) (_node *SpinningLine, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(spinningline.Table, spinningline.Columns, sqlgraph.NewFieldSpec(spinningline.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SpinningLine.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, spinningline.FieldID)
		for _, f := range fields {
			if !spinningline.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != spinningline.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LineName(); ok {
		_spec.SetField(spinningline.FieldLineName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LineNumber(); ok {
		_spec.SetField(spinningline.FieldLineNumber, field.TypeString, value)
	}
	if _u.mutation.LineNumberCleared() {
		_spec.ClearField(spinningline.FieldLineNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(spinningline.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(spinningline.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Capacity(); ok {
		_spec.SetField(spinningline.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacity(); ok {
		_spec.AddField(spinningline.FieldCapacity, field.TypeInt, value)
	}
	if _u.mutation.CapacityCleared() {
		_spec.ClearField(spinningline.FieldCapacity, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(spinningline.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentLotID(); ok {
		_spec.SetField(spinningline.FieldCurrentLotID, field.TypeUUID, value)
	}
	if _u.mutation.CurrentLotIDCleared() {
		_spec.ClearField(spinningline.FieldCurrentLotID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(spinningline.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EdgeEdgeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spinningline.EdgeTable,
			Columns: []string{spinningline.EdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spinningline.EdgeTable,
			Columns: []string{spinningline.EdgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(edge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SpinningLine{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spinningline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
