// Code generated by ent, DO NOT EDIT.

package spinningline

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the spinningline type in the database.
	Label = "spinning_line"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLineName holds the string denoting the line_name field in the database.
	FieldLineName = "line_name"
	// FieldLineNumber holds the string denoting the line_number field in the database.
	FieldLineNumber = "line_number"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldCapacity holds the string denoting the capacity field in the database.
	FieldCapacity = "capacity"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCurrentLotID holds the string denoting the current_lot_id field in the database.
	FieldCurrentLotID = "current_lot_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the spinningline in the database.
	Table = "spinning_lines"
)

// Columns holds all SQL columns for spinningline fields.
var Columns = []string{
	FieldID,
	FieldLineName,
	FieldLineNumber,
	FieldLocation,
	FieldCapacity,
	FieldStatus,
	FieldCurrentLotID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LineNameValidator is a validator for the "line_name" field. It is called by the builders before save.
	LineNameValidator func(string) error
	// LineNumberValidator is a validator for the "line_number" field. It is called by the builders before save.
	LineNumberValidator func(string) error
	// LocationValidator is a validator for the "location" field. It is called by the builders before save.
	LocationValidator func(string) error
	// CapacityValidator is a validator for the "capacity" field. It is called by the builders before save.
	CapacityValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusIdle is the default value of the Status enum.
const DefaultStatus = StatusIdle

// Status values.
const (
	StatusIdle        Status = "idle"
	StatusRunning     Status = "running"
	StatusMaintenance Status = "maintenance"
	StatusOffline     Status = "offline"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusIdle, StatusRunning, StatusMaintenance, StatusOffline:
		return nil
	default:
		return fmt.Errorf("spinningline: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the SpinningLine queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLineName orders the results by the line_name field.
func ByLineName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLineName, opts...).ToFunc()
}

// ByLineNumber orders the results by the line_number field.
func ByLineNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLineNumber, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByCapacity orders the results by the capacity field.
func ByCapacity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapacity, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCurrentLotID orders the results by the current_lot_id field.
func ByCurrentLotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentLotID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
