// Code generated by ent, DO NOT EDIT.

package spinningline

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the spinningline type in the database.
	Label = "spinning_line"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLineNumber holds the string denoting the line_number field in the database.
	FieldLineNumber = "line_number"
	// FieldLineName holds the string denoting the line_name field in the database.
	FieldLineName = "line_name"
	// FieldPositionCount holds the string denoting the position_count field in the database.
	FieldPositionCount = "position_count"
	// FieldWorkshopArea holds the string denoting the workshop_area field in the database.
	FieldWorkshopArea = "workshop_area"
	// FieldProductType holds the string denoting the product_type field in the database.
	FieldProductType = "product_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPlcIP holds the string denoting the plc_ip field in the database.
	FieldPlcIP = "plc_ip"
	// FieldPlcPort holds the string denoting the plc_port field in the database.
	FieldPlcPort = "plc_port"
	// FieldPlcProtocol holds the string denoting the plc_protocol field in the database.
	FieldPlcProtocol = "plc_protocol"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the spinningline in the database.
	Table = "spinning_lines"
)

// Columns holds all SQL columns for spinningline fields.
var Columns = []string{
	FieldID,
	FieldLineNumber,
	FieldLineName,
	FieldPositionCount,
	FieldWorkshopArea,
	FieldProductType,
	FieldStatus,
	FieldPlcIP,
	FieldPlcPort,
	FieldPlcProtocol,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LineNumberValidator is a validator for the "line_number" field. It is called by the builders before save.
	LineNumberValidator func(string) error
	// LineNameValidator is a validator for the "line_name" field. It is called by the builders before save.
	LineNameValidator func(string) error
	// PositionCountValidator is a validator for the "position_count" field. It is called by the builders before save.
	PositionCountValidator func(int) error
	// WorkshopAreaValidator is a validator for the "workshop_area" field. It is called by the builders before save.
	WorkshopAreaValidator func(string) error
	// PlcIPValidator is a validator for the "plc_ip" field. It is called by the builders before save.
	PlcIPValidator func(string) error
	// PlcPortValidator is a validator for the "plc_port" field. It is called by the builders before save.
	PlcPortValidator func(int) error
	// PlcProtocolValidator is a validator for the "plc_protocol" field. It is called by the builders before save.
	PlcProtocolValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ProductType defines the type for the "product_type" enum field.
type ProductType string

// ProductType values.
const (
	ProductTypeFDY ProductType = "FDY"
	ProductTypePOY ProductType = "POY"
	ProductTypeDTY ProductType = "DTY"
)

func (pt ProductType) String() string {
	return string(pt)
}

// ProductTypeValidator is a validator for the "product_type" field enum values. It is called by the builders before save.
func ProductTypeValidator(pt ProductType) error {
	switch pt {
	case ProductTypeFDY, ProductTypePOY, ProductTypeDTY:
		return nil
	default:
		return fmt.Errorf("spinningline: invalid enum value for product_type field: %q", pt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive      Status = "active"
	StatusMaintenance Status = "maintenance"
	StatusInactive    Status = "inactive"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusMaintenance, StatusInactive:
		return nil
	default:
		return fmt.Errorf("spinningline: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the SpinningLine queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLineNumber orders the results by the line_number field.
func ByLineNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLineNumber, opts...).ToFunc()
}

// ByLineName orders the results by the line_name field.
func ByLineName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLineName, opts...).ToFunc()
}

// ByPositionCount orders the results by the position_count field.
func ByPositionCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionCount, opts...).ToFunc()
}

// ByWorkshopArea orders the results by the workshop_area field.
func ByWorkshopArea(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkshopArea, opts...).ToFunc()
}

// ByProductType orders the results by the product_type field.
func ByProductType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPlcIP orders the results by the plc_ip field.
func ByPlcIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlcIP, opts...).ToFunc()
}

// ByPlcPort orders the results by the plc_port field.
func ByPlcPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlcPort, opts...).ToFunc()
}

// ByPlcProtocol orders the results by the plc_protocol field.
func ByPlcProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlcProtocol, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
