// Code generated by ent, DO NOT EDIT.

package spinningline

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldID, id))
}

// LineName applies equality check predicate on the "line_name" field. It's identical to LineNameEQ.
func LineName(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLineName, v))
}

// LineNumber applies equality check predicate on the "line_number" field. It's identical to LineNumberEQ.
func LineNumber(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLineNumber, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLocation, v))
}

// Capacity applies equality check predicate on the "capacity" field. It's identical to CapacityEQ.
func Capacity(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldCapacity, v))
}

// CurrentLotID applies equality check predicate on the "current_lot_id" field. It's identical to CurrentLotIDEQ.
func CurrentLotID(v uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldCurrentLotID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldUpdatedAt, v))
}

// LineNameEQ applies the EQ predicate on the "line_name" field.
func LineNameEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLineName, v))
}

// LineNameNEQ applies the NEQ predicate on the "line_name" field.
func LineNameNEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldLineName, v))
}

// LineNameIn applies the In predicate on the "line_name" field.
func LineNameIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldLineName, vs...))
}

// LineNameNotIn applies the NotIn predicate on the "line_name" field.
func LineNameNotIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldLineName, vs...))
}

// LineNameGT applies the GT predicate on the "line_name" field.
func LineNameGT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldLineName, v))
}

// LineNameGTE applies the GTE predicate on the "line_name" field.
func LineNameGTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldLineName, v))
}

// LineNameLT applies the LT predicate on the "line_name" field.
func LineNameLT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldLineName, v))
}

// LineNameLTE applies the LTE predicate on the "line_name" field.
func LineNameLTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldLineName, v))
}

// LineNameContains applies the Contains predicate on the "line_name" field.
func LineNameContains(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContains(FieldLineName, v))
}

// LineNameHasPrefix applies the HasPrefix predicate on the "line_name" field.
func LineNameHasPrefix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasPrefix(FieldLineName, v))
}

// LineNameHasSuffix applies the HasSuffix predicate on the "line_name" field.
func LineNameHasSuffix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasSuffix(FieldLineName, v))
}

// LineNameEqualFold applies the EqualFold predicate on the "line_name" field.
func LineNameEqualFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEqualFold(FieldLineName, v))
}

// LineNameContainsFold applies the ContainsFold predicate on the "line_name" field.
func LineNameContainsFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContainsFold(FieldLineName, v))
}

// LineNumberEQ applies the EQ predicate on the "line_number" field.
func LineNumberEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLineNumber, v))
}

// LineNumberNEQ applies the NEQ predicate on the "line_number" field.
func LineNumberNEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldLineNumber, v))
}

// LineNumberIn applies the In predicate on the "line_number" field.
func LineNumberIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldLineNumber, vs...))
}

// LineNumberNotIn applies the NotIn predicate on the "line_number" field.
func LineNumberNotIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldLineNumber, vs...))
}

// LineNumberGT applies the GT predicate on the "line_number" field.
func LineNumberGT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldLineNumber, v))
}

// LineNumberGTE applies the GTE predicate on the "line_number" field.
func LineNumberGTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldLineNumber, v))
}

// LineNumberLT applies the LT predicate on the "line_number" field.
func LineNumberLT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldLineNumber, v))
}

// LineNumberLTE applies the LTE predicate on the "line_number" field.
func LineNumberLTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldLineNumber, v))
}

// LineNumberContains applies the Contains predicate on the "line_number" field.
func LineNumberContains(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContains(FieldLineNumber, v))
}

// LineNumberHasPrefix applies the HasPrefix predicate on the "line_number" field.
func LineNumberHasPrefix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasPrefix(FieldLineNumber, v))
}

// LineNumberHasSuffix applies the HasSuffix predicate on the "line_number" field.
func LineNumberHasSuffix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasSuffix(FieldLineNumber, v))
}

// LineNumberIsNil applies the IsNil predicate on the "line_number" field.
func LineNumberIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldLineNumber))
}

// LineNumberNotNil applies the NotNil predicate on the "line_number" field.
func LineNumberNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldLineNumber))
}

// LineNumberEqualFold applies the EqualFold predicate on the "line_number" field.
func LineNumberEqualFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEqualFold(FieldLineNumber, v))
}

// LineNumberContainsFold applies the ContainsFold predicate on the "line_number" field.
func LineNumberContainsFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContainsFold(FieldLineNumber, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationIsNil applies the IsNil predicate on the "location" field.
func LocationIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldLocation))
}

// LocationNotNil applies the NotNil predicate on the "location" field.
func LocationNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldLocation))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContainsFold(FieldLocation, v))
}

// CapacityEQ applies the EQ predicate on the "capacity" field.
func CapacityEQ(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldCapacity, v))
}

// CapacityNEQ applies the NEQ predicate on the "capacity" field.
func CapacityNEQ(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldCapacity, v))
}

// CapacityIn applies the In predicate on the "capacity" field.
func CapacityIn(vs ...int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldCapacity, vs...))
}

// CapacityNotIn applies the NotIn predicate on the "capacity" field.
func CapacityNotIn(vs ...int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldCapacity, vs...))
}

// CapacityGT applies the GT predicate on the "capacity" field.
func CapacityGT(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldCapacity, v))
}

// CapacityGTE applies the GTE predicate on the "capacity" field.
func CapacityGTE(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldCapacity, v))
}

// CapacityLT applies the LT predicate on the "capacity" field.
func CapacityLT(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldCapacity, v))
}

// CapacityLTE applies the LTE predicate on the "capacity" field.
func CapacityLTE(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldCapacity, v))
}

// CapacityIsNil applies the IsNil predicate on the "capacity" field.
func CapacityIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldCapacity))
}

// CapacityNotNil applies the NotNil predicate on the "capacity" field.
func CapacityNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldCapacity))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldStatus, vs...))
}

// CurrentLotIDEQ applies the EQ predicate on the "current_lot_id" field.
func CurrentLotIDEQ(v uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldCurrentLotID, v))
}

// CurrentLotIDNEQ applies the NEQ predicate on the "current_lot_id" field.
func CurrentLotIDNEQ(v uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldCurrentLotID, v))
}

// CurrentLotIDIn applies the In predicate on the "current_lot_id" field.
func CurrentLotIDIn(vs ...uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldCurrentLotID, vs...))
}

// CurrentLotIDNotIn applies the NotIn predicate on the "current_lot_id" field.
func CurrentLotIDNotIn(vs ...uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldCurrentLotID, vs...))
}

// CurrentLotIDGT applies the GT predicate on the "current_lot_id" field.
func CurrentLotIDGT(v uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldCurrentLotID, v))
}

// CurrentLotIDGTE applies the GTE predicate on the "current_lot_id" field.
func CurrentLotIDGTE(v uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldCurrentLotID, v))
}

// CurrentLotIDLT applies the LT predicate on the "current_lot_id" field.
func CurrentLotIDLT(v uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldCurrentLotID, v))
}

// CurrentLotIDLTE applies the LTE predicate on the "current_lot_id" field.
func CurrentLotIDLTE(v uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldCurrentLotID, v))
}

// CurrentLotIDIsNil applies the IsNil predicate on the "current_lot_id" field.
func CurrentLotIDIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldCurrentLotID))
}

// CurrentLotIDNotNil applies the NotNil predicate on the "current_lot_id" field.
func CurrentLotIDNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldCurrentLotID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SpinningLine) predicate.SpinningLine {
	return predicate.SpinningLine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SpinningLine) predicate.SpinningLine {
	return predicate.SpinningLine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SpinningLine) predicate.SpinningLine {
	return predicate.SpinningLine(sql.NotPredicates(p))
}
