// Code generated by ent, DO NOT EDIT.

package spinningline

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldID, id))
}

// LineNumber applies equality check predicate on the "line_number" field. It's identical to LineNumberEQ.
func LineNumber(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLineNumber, v))
}

// LineName applies equality check predicate on the "line_name" field. It's identical to LineNameEQ.
func LineName(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLineName, v))
}

// PositionCount applies equality check predicate on the "position_count" field. It's identical to PositionCountEQ.
func PositionCount(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldPositionCount, v))
}

// WorkshopArea applies equality check predicate on the "workshop_area" field. It's identical to WorkshopAreaEQ.
func WorkshopArea(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldWorkshopArea, v))
}

// PlcIP applies equality check predicate on the "plc_ip" field. It's identical to PlcIPEQ.
func PlcIP(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldPlcIP, v))
}

// PlcPort applies equality check predicate on the "plc_port" field. It's identical to PlcPortEQ.
func PlcPort(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldPlcPort, v))
}

// PlcProtocol applies equality check predicate on the "plc_protocol" field. It's identical to PlcProtocolEQ.
func PlcProtocol(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldPlcProtocol, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldUpdatedAt, v))
}

// LineNumberEQ applies the EQ predicate on the "line_number" field.
func LineNumberEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLineNumber, v))
}

// LineNumberNEQ applies the NEQ predicate on the "line_number" field.
func LineNumberNEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldLineNumber, v))
}

// LineNumberIn applies the In predicate on the "line_number" field.
func LineNumberIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldLineNumber, vs...))
}

// LineNumberNotIn applies the NotIn predicate on the "line_number" field.
func LineNumberNotIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldLineNumber, vs...))
}

// LineNumberGT applies the GT predicate on the "line_number" field.
func LineNumberGT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldLineNumber, v))
}

// LineNumberGTE applies the GTE predicate on the "line_number" field.
func LineNumberGTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldLineNumber, v))
}

// LineNumberLT applies the LT predicate on the "line_number" field.
func LineNumberLT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldLineNumber, v))
}

// LineNumberLTE applies the LTE predicate on the "line_number" field.
func LineNumberLTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldLineNumber, v))
}

// LineNumberContains applies the Contains predicate on the "line_number" field.
func LineNumberContains(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContains(FieldLineNumber, v))
}

// LineNumberHasPrefix applies the HasPrefix predicate on the "line_number" field.
func LineNumberHasPrefix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasPrefix(FieldLineNumber, v))
}

// LineNumberHasSuffix applies the HasSuffix predicate on the "line_number" field.
func LineNumberHasSuffix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasSuffix(FieldLineNumber, v))
}

// LineNumberEqualFold applies the EqualFold predicate on the "line_number" field.
func LineNumberEqualFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEqualFold(FieldLineNumber, v))
}

// LineNumberContainsFold applies the ContainsFold predicate on the "line_number" field.
func LineNumberContainsFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContainsFold(FieldLineNumber, v))
}

// LineNameEQ applies the EQ predicate on the "line_name" field.
func LineNameEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldLineName, v))
}

// LineNameNEQ applies the NEQ predicate on the "line_name" field.
func LineNameNEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldLineName, v))
}

// LineNameIn applies the In predicate on the "line_name" field.
func LineNameIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldLineName, vs...))
}

// LineNameNotIn applies the NotIn predicate on the "line_name" field.
func LineNameNotIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldLineName, vs...))
}

// LineNameGT applies the GT predicate on the "line_name" field.
func LineNameGT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldLineName, v))
}

// LineNameGTE applies the GTE predicate on the "line_name" field.
func LineNameGTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldLineName, v))
}

// LineNameLT applies the LT predicate on the "line_name" field.
func LineNameLT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldLineName, v))
}

// LineNameLTE applies the LTE predicate on the "line_name" field.
func LineNameLTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldLineName, v))
}

// LineNameContains applies the Contains predicate on the "line_name" field.
func LineNameContains(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContains(FieldLineName, v))
}

// LineNameHasPrefix applies the HasPrefix predicate on the "line_name" field.
func LineNameHasPrefix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasPrefix(FieldLineName, v))
}

// LineNameHasSuffix applies the HasSuffix predicate on the "line_name" field.
func LineNameHasSuffix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasSuffix(FieldLineName, v))
}

// LineNameEqualFold applies the EqualFold predicate on the "line_name" field.
func LineNameEqualFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEqualFold(FieldLineName, v))
}

// LineNameContainsFold applies the ContainsFold predicate on the "line_name" field.
func LineNameContainsFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContainsFold(FieldLineName, v))
}

// PositionCountEQ applies the EQ predicate on the "position_count" field.
func PositionCountEQ(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldPositionCount, v))
}

// PositionCountNEQ applies the NEQ predicate on the "position_count" field.
func PositionCountNEQ(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldPositionCount, v))
}

// PositionCountIn applies the In predicate on the "position_count" field.
func PositionCountIn(vs ...int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldPositionCount, vs...))
}

// PositionCountNotIn applies the NotIn predicate on the "position_count" field.
func PositionCountNotIn(vs ...int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldPositionCount, vs...))
}

// PositionCountGT applies the GT predicate on the "position_count" field.
func PositionCountGT(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldPositionCount, v))
}

// PositionCountGTE applies the GTE predicate on the "position_count" field.
func PositionCountGTE(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldPositionCount, v))
}

// PositionCountLT applies the LT predicate on the "position_count" field.
func PositionCountLT(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldPositionCount, v))
}

// PositionCountLTE applies the LTE predicate on the "position_count" field.
func PositionCountLTE(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldPositionCount, v))
}

// WorkshopAreaEQ applies the EQ predicate on the "workshop_area" field.
func WorkshopAreaEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldWorkshopArea, v))
}

// WorkshopAreaNEQ applies the NEQ predicate on the "workshop_area" field.
func WorkshopAreaNEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldWorkshopArea, v))
}

// WorkshopAreaIn applies the In predicate on the "workshop_area" field.
func WorkshopAreaIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldWorkshopArea, vs...))
}

// WorkshopAreaNotIn applies the NotIn predicate on the "workshop_area" field.
func WorkshopAreaNotIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldWorkshopArea, vs...))
}

// WorkshopAreaGT applies the GT predicate on the "workshop_area" field.
func WorkshopAreaGT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldWorkshopArea, v))
}

// WorkshopAreaGTE applies the GTE predicate on the "workshop_area" field.
func WorkshopAreaGTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldWorkshopArea, v))
}

// WorkshopAreaLT applies the LT predicate on the "workshop_area" field.
func WorkshopAreaLT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldWorkshopArea, v))
}

// WorkshopAreaLTE applies the LTE predicate on the "workshop_area" field.
func WorkshopAreaLTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldWorkshopArea, v))
}

// WorkshopAreaContains applies the Contains predicate on the "workshop_area" field.
func WorkshopAreaContains(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContains(FieldWorkshopArea, v))
}

// WorkshopAreaHasPrefix applies the HasPrefix predicate on the "workshop_area" field.
func WorkshopAreaHasPrefix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasPrefix(FieldWorkshopArea, v))
}

// WorkshopAreaHasSuffix applies the HasSuffix predicate on the "workshop_area" field.
func WorkshopAreaHasSuffix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasSuffix(FieldWorkshopArea, v))
}

// WorkshopAreaIsNil applies the IsNil predicate on the "workshop_area" field.
func WorkshopAreaIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldWorkshopArea))
}

// WorkshopAreaNotNil applies the NotNil predicate on the "workshop_area" field.
func WorkshopAreaNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldWorkshopArea))
}

// WorkshopAreaEqualFold applies the EqualFold predicate on the "workshop_area" field.
func WorkshopAreaEqualFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEqualFold(FieldWorkshopArea, v))
}

// WorkshopAreaContainsFold applies the ContainsFold predicate on the "workshop_area" field.
func WorkshopAreaContainsFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContainsFold(FieldWorkshopArea, v))
}

// ProductTypeEQ applies the EQ predicate on the "product_type" field.
func ProductTypeEQ(v ProductType) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldProductType, v))
}

// ProductTypeNEQ applies the NEQ predicate on the "product_type" field.
func ProductTypeNEQ(v ProductType) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldProductType, v))
}

// ProductTypeIn applies the In predicate on the "product_type" field.
func ProductTypeIn(vs ...ProductType) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldProductType, vs...))
}

// ProductTypeNotIn applies the NotIn predicate on the "product_type" field.
func ProductTypeNotIn(vs ...ProductType) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldProductType, vs...))
}

// ProductTypeIsNil applies the IsNil predicate on the "product_type" field.
func ProductTypeIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldProductType))
}

// ProductTypeNotNil applies the NotNil predicate on the "product_type" field.
func ProductTypeNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldProductType))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldStatus, vs...))
}

// PlcIPEQ applies the EQ predicate on the "plc_ip" field.
func PlcIPEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldPlcIP, v))
}

// PlcIPNEQ applies the NEQ predicate on the "plc_ip" field.
func PlcIPNEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldPlcIP, v))
}

// PlcIPIn applies the In predicate on the "plc_ip" field.
func PlcIPIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldPlcIP, vs...))
}

// PlcIPNotIn applies the NotIn predicate on the "plc_ip" field.
func PlcIPNotIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldPlcIP, vs...))
}

// PlcIPGT applies the GT predicate on the "plc_ip" field.
func PlcIPGT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldPlcIP, v))
}

// PlcIPGTE applies the GTE predicate on the "plc_ip" field.
func PlcIPGTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldPlcIP, v))
}

// PlcIPLT applies the LT predicate on the "plc_ip" field.
func PlcIPLT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldPlcIP, v))
}

// PlcIPLTE applies the LTE predicate on the "plc_ip" field.
func PlcIPLTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldPlcIP, v))
}

// PlcIPContains applies the Contains predicate on the "plc_ip" field.
func PlcIPContains(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContains(FieldPlcIP, v))
}

// PlcIPHasPrefix applies the HasPrefix predicate on the "plc_ip" field.
func PlcIPHasPrefix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasPrefix(FieldPlcIP, v))
}

// PlcIPHasSuffix applies the HasSuffix predicate on the "plc_ip" field.
func PlcIPHasSuffix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasSuffix(FieldPlcIP, v))
}

// PlcIPIsNil applies the IsNil predicate on the "plc_ip" field.
func PlcIPIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldPlcIP))
}

// PlcIPNotNil applies the NotNil predicate on the "plc_ip" field.
func PlcIPNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldPlcIP))
}

// PlcIPEqualFold applies the EqualFold predicate on the "plc_ip" field.
func PlcIPEqualFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEqualFold(FieldPlcIP, v))
}

// PlcIPContainsFold applies the ContainsFold predicate on the "plc_ip" field.
func PlcIPContainsFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContainsFold(FieldPlcIP, v))
}

// PlcPortEQ applies the EQ predicate on the "plc_port" field.
func PlcPortEQ(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldPlcPort, v))
}

// PlcPortNEQ applies the NEQ predicate on the "plc_port" field.
func PlcPortNEQ(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldPlcPort, v))
}

// PlcPortIn applies the In predicate on the "plc_port" field.
func PlcPortIn(vs ...int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldPlcPort, vs...))
}

// PlcPortNotIn applies the NotIn predicate on the "plc_port" field.
func PlcPortNotIn(vs ...int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldPlcPort, vs...))
}

// PlcPortGT applies the GT predicate on the "plc_port" field.
func PlcPortGT(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldPlcPort, v))
}

// PlcPortGTE applies the GTE predicate on the "plc_port" field.
func PlcPortGTE(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldPlcPort, v))
}

// PlcPortLT applies the LT predicate on the "plc_port" field.
func PlcPortLT(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldPlcPort, v))
}

// PlcPortLTE applies the LTE predicate on the "plc_port" field.
func PlcPortLTE(v int) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldPlcPort, v))
}

// PlcPortIsNil applies the IsNil predicate on the "plc_port" field.
func PlcPortIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldPlcPort))
}

// PlcPortNotNil applies the NotNil predicate on the "plc_port" field.
func PlcPortNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldPlcPort))
}

// PlcProtocolEQ applies the EQ predicate on the "plc_protocol" field.
func PlcProtocolEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldPlcProtocol, v))
}

// PlcProtocolNEQ applies the NEQ predicate on the "plc_protocol" field.
func PlcProtocolNEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldPlcProtocol, v))
}

// PlcProtocolIn applies the In predicate on the "plc_protocol" field.
func PlcProtocolIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldPlcProtocol, vs...))
}

// PlcProtocolNotIn applies the NotIn predicate on the "plc_protocol" field.
func PlcProtocolNotIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldPlcProtocol, vs...))
}

// PlcProtocolGT applies the GT predicate on the "plc_protocol" field.
func PlcProtocolGT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldPlcProtocol, v))
}

// PlcProtocolGTE applies the GTE predicate on the "plc_protocol" field.
func PlcProtocolGTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldPlcProtocol, v))
}

// PlcProtocolLT applies the LT predicate on the "plc_protocol" field.
func PlcProtocolLT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldPlcProtocol, v))
}

// PlcProtocolLTE applies the LTE predicate on the "plc_protocol" field.
func PlcProtocolLTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldPlcProtocol, v))
}

// PlcProtocolContains applies the Contains predicate on the "plc_protocol" field.
func PlcProtocolContains(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContains(FieldPlcProtocol, v))
}

// PlcProtocolHasPrefix applies the HasPrefix predicate on the "plc_protocol" field.
func PlcProtocolHasPrefix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasPrefix(FieldPlcProtocol, v))
}

// PlcProtocolHasSuffix applies the HasSuffix predicate on the "plc_protocol" field.
func PlcProtocolHasSuffix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasSuffix(FieldPlcProtocol, v))
}

// PlcProtocolIsNil applies the IsNil predicate on the "plc_protocol" field.
func PlcProtocolIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldPlcProtocol))
}

// PlcProtocolNotNil applies the NotNil predicate on the "plc_protocol" field.
func PlcProtocolNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldPlcProtocol))
}

// PlcProtocolEqualFold applies the EqualFold predicate on the "plc_protocol" field.
func PlcProtocolEqualFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEqualFold(FieldPlcProtocol, v))
}

// PlcProtocolContainsFold applies the ContainsFold predicate on the "plc_protocol" field.
func PlcProtocolContainsFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContainsFold(FieldPlcProtocol, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SpinningLine {
	return predicate.SpinningLine(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SpinningLine) predicate.SpinningLine {
	return predicate.SpinningLine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SpinningLine) predicate.SpinningLine {
	return predicate.SpinningLine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SpinningLine) predicate.SpinningLine {
	return predicate.SpinningLine(sql.NotPredicates(p))
}
