// Code generated by ent, DO NOT EDIT.

package ent_edge

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourusername/igh-silkroad/internal/database/ent_edge/predicate"
	"github.com/yourusername/igh-silkroad/internal/database/ent_edge/synclog"
)

// SyncLogDelete is the builder for deleting a SyncLog entity.
type SyncLogDelete struct {
	config
	hooks    []Hook
	mutation *SyncLogMutation
}

// Where appends a list predicates to the SyncLogDelete builder.
func (_d *SyncLogDelete) Where(ps ...predicate.SyncLog) *SyncLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SyncLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SyncLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SyncLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(synclog.Table, sqlgraph.NewFieldSpec(synclog.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SyncLogDeleteOne is the builder for deleting a single SyncLog entity.
type SyncLogDeleteOne struct {
	_d *SyncLogDelete
}

// Where appends a list predicates to the SyncLogDelete builder.
func (_d *SyncLogDeleteOne) Where(ps ...predicate.SyncLog) *SyncLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SyncLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{synclog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SyncLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
