// Code generated by ent, DO NOT EDIT.

package ent_edge

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent_edge/synclog"
)

// SyncLogCreate is the builder for creating a SyncLog entity.
type SyncLogCreate struct {
	config
	mutation *SyncLogMutation
	hooks    []Hook
}

// SetEntityType sets the "entity_type" field.
func (_c *SyncLogCreate) SetEntityType(v synclog.EntityType) *SyncLogCreate {
	_c.mutation.SetEntityType(v)
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *SyncLogCreate) SetEntityID(v uuid.UUID) *SyncLogCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *SyncLogCreate) SetOperation(v synclog.Operation) *SyncLogCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SyncLogCreate) SetStatus(v synclog.Status) *SyncLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SyncLogCreate) SetNillableStatus(v *synclog.Status) *SyncLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *SyncLogCreate) SetRetryCount(v int) *SyncLogCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *SyncLogCreate) SetNillableRetryCount(v *int) *SyncLogCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *SyncLogCreate) SetErrorMessage(v string) *SyncLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *SyncLogCreate) SetNillableErrorMessage(v *string) *SyncLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetDataSnapshot sets the "data_snapshot" field.
func (_c *SyncLogCreate) SetDataSnapshot(v map[string]interface{}) *SyncLogCreate {
	_c.mutation.SetDataSnapshot(v)
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *SyncLogCreate) SetSyncedAt(v time.Time) *SyncLogCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *SyncLogCreate) SetNillableSyncedAt(v *time.Time) *SyncLogCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SyncLogCreate) SetCreatedAt(v time.Time) *SyncLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SyncLogCreate) SetNillableCreatedAt(v *time.Time) *SyncLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SyncLogCreate) SetUpdatedAt(v time.Time) *SyncLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SyncLogCreate) SetNillableUpdatedAt(v *time.Time) *SyncLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SyncLogCreate) SetID(v uuid.UUID) *SyncLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SyncLogCreate) SetNillableID(v *uuid.UUID) *SyncLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SyncLogMutation object of the builder.
func (_c *SyncLogCreate) Mutation() *SyncLogMutation {
	return _c.mutation
}

// Save creates the SyncLog in the database.
func (_c *SyncLogCreate) Save(ctx context.Context) (*SyncLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncLogCreate) SaveX(ctx context.Context) *SyncLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncLogCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := synclog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := synclog.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := synclog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := synclog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := synclog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncLogCreate) check() error {
	if _, ok := _c.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent_edge: missing required field "SyncLog.entity_type"`)}
	}
	if v, ok := _c.mutation.EntityType(); ok {
		if err := synclog.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent_edge: validator failed for field "SyncLog.entity_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent_edge: missing required field "SyncLog.entity_id"`)}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent_edge: missing required field "SyncLog.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := synclog.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent_edge: validator failed for field "SyncLog.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent_edge: missing required field "SyncLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := synclog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent_edge: validator failed for field "SyncLog.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent_edge: missing required field "SyncLog.retry_count"`)}
	}
	if v, ok := _c.mutation.RetryCount(); ok {
		if err := synclog.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent_edge: validator failed for field "SyncLog.retry_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent_edge: missing required field "SyncLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent_edge: missing required field "SyncLog.updated_at"`)}
	}
	return nil
}

func (_c *SyncLogCreate) sqlSave(ctx context.Context) (*SyncLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncLogCreate) createSpec() (*SyncLog, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(synclog.Table, sqlgraph.NewFieldSpec(synclog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.EntityType(); ok {
		_spec.SetField(synclog.FieldEntityType, field.TypeEnum, value)
		_node.EntityType = value
	}
	if value, ok := _c.mutation.EntityID(); ok {
		_spec.SetField(synclog.FieldEntityID, field.TypeUUID, value)
		_node.EntityID = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(synclog.FieldOperation, field.TypeEnum, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(synclog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(synclog.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(synclog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.DataSnapshot(); ok {
		_spec.SetField(synclog.FieldDataSnapshot, field.TypeJSON, value)
		_node.DataSnapshot = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(synclog.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(synclog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(synclog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SyncLogCreateBulk is the builder for creating many SyncLog entities in bulk.
type SyncLogCreateBulk struct {
	config
	err      error
	builders []*SyncLogCreate
}

// Save creates the SyncLog entities in the database.
func (_c *SyncLogCreateBulk) Save(ctx context.Context) ([]*SyncLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncLogCreateBulk) SaveX(ctx context.Context) []*SyncLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
