// Code generated by ent, DO NOT EDIT.

package order

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldID, id))
}

// OrderNumber applies equality check predicate on the "order_number" field. It's identical to OrderNumberEQ.
func OrderNumber(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOrderNumber, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProjectID, v))
}

// ProductSpec applies equality check predicate on the "product_spec" field. It's identical to ProductSpecEQ.
func ProductSpec(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProductSpec, v))
}

// TargetQuantity applies equality check predicate on the "target_quantity" field. It's identical to TargetQuantityEQ.
func TargetQuantity(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTargetQuantity, v))
}

// ActualQuantity applies equality check predicate on the "actual_quantity" field. It's identical to ActualQuantityEQ.
func ActualQuantity(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldActualQuantity, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPriority, v))
}

// DeliveryDate applies equality check predicate on the "delivery_date" field. It's identical to DeliveryDateEQ.
func DeliveryDate(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveryDate, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNumberEQ applies the EQ predicate on the "order_number" field.
func OrderNumberEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOrderNumber, v))
}

// OrderNumberNEQ applies the NEQ predicate on the "order_number" field.
func OrderNumberNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldOrderNumber, v))
}

// OrderNumberIn applies the In predicate on the "order_number" field.
func OrderNumberIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldOrderNumber, vs...))
}

// OrderNumberNotIn applies the NotIn predicate on the "order_number" field.
func OrderNumberNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldOrderNumber, vs...))
}

// OrderNumberGT applies the GT predicate on the "order_number" field.
func OrderNumberGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldOrderNumber, v))
}

// OrderNumberGTE applies the GTE predicate on the "order_number" field.
func OrderNumberGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldOrderNumber, v))
}

// OrderNumberLT applies the LT predicate on the "order_number" field.
func OrderNumberLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldOrderNumber, v))
}

// OrderNumberLTE applies the LTE predicate on the "order_number" field.
func OrderNumberLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldOrderNumber, v))
}

// OrderNumberContains applies the Contains predicate on the "order_number" field.
func OrderNumberContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldOrderNumber, v))
}

// OrderNumberHasPrefix applies the HasPrefix predicate on the "order_number" field.
func OrderNumberHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldOrderNumber, v))
}

// OrderNumberHasSuffix applies the HasSuffix predicate on the "order_number" field.
func OrderNumberHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldOrderNumber, v))
}

// OrderNumberEqualFold applies the EqualFold predicate on the "order_number" field.
func OrderNumberEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldOrderNumber, v))
}

// OrderNumberContainsFold applies the ContainsFold predicate on the "order_number" field.
func OrderNumberContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldOrderNumber, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDIsNil applies the IsNil predicate on the "project_id" field.
func ProjectIDIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldProjectID))
}

// ProjectIDNotNil applies the NotNil predicate on the "project_id" field.
func ProjectIDNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldProjectID))
}

// ProductTypeEQ applies the EQ predicate on the "product_type" field.
func ProductTypeEQ(v ProductType) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProductType, v))
}

// ProductTypeNEQ applies the NEQ predicate on the "product_type" field.
func ProductTypeNEQ(v ProductType) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldProductType, v))
}

// ProductTypeIn applies the In predicate on the "product_type" field.
func ProductTypeIn(vs ...ProductType) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldProductType, vs...))
}

// ProductTypeNotIn applies the NotIn predicate on the "product_type" field.
func ProductTypeNotIn(vs ...ProductType) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldProductType, vs...))
}

// ProductSpecEQ applies the EQ predicate on the "product_spec" field.
func ProductSpecEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldProductSpec, v))
}

// ProductSpecNEQ applies the NEQ predicate on the "product_spec" field.
func ProductSpecNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldProductSpec, v))
}

// ProductSpecIn applies the In predicate on the "product_spec" field.
func ProductSpecIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldProductSpec, vs...))
}

// ProductSpecNotIn applies the NotIn predicate on the "product_spec" field.
func ProductSpecNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldProductSpec, vs...))
}

// ProductSpecGT applies the GT predicate on the "product_spec" field.
func ProductSpecGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldProductSpec, v))
}

// ProductSpecGTE applies the GTE predicate on the "product_spec" field.
func ProductSpecGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldProductSpec, v))
}

// ProductSpecLT applies the LT predicate on the "product_spec" field.
func ProductSpecLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldProductSpec, v))
}

// ProductSpecLTE applies the LTE predicate on the "product_spec" field.
func ProductSpecLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldProductSpec, v))
}

// ProductSpecContains applies the Contains predicate on the "product_spec" field.
func ProductSpecContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldProductSpec, v))
}

// ProductSpecHasPrefix applies the HasPrefix predicate on the "product_spec" field.
func ProductSpecHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldProductSpec, v))
}

// ProductSpecHasSuffix applies the HasSuffix predicate on the "product_spec" field.
func ProductSpecHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldProductSpec, v))
}

// ProductSpecIsNil applies the IsNil predicate on the "product_spec" field.
func ProductSpecIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldProductSpec))
}

// ProductSpecNotNil applies the NotNil predicate on the "product_spec" field.
func ProductSpecNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldProductSpec))
}

// ProductSpecEqualFold applies the EqualFold predicate on the "product_spec" field.
func ProductSpecEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldProductSpec, v))
}

// ProductSpecContainsFold applies the ContainsFold predicate on the "product_spec" field.
func ProductSpecContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldProductSpec, v))
}

// TargetQuantityEQ applies the EQ predicate on the "target_quantity" field.
func TargetQuantityEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTargetQuantity, v))
}

// TargetQuantityNEQ applies the NEQ predicate on the "target_quantity" field.
func TargetQuantityNEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldTargetQuantity, v))
}

// TargetQuantityIn applies the In predicate on the "target_quantity" field.
func TargetQuantityIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldTargetQuantity, vs...))
}

// TargetQuantityNotIn applies the NotIn predicate on the "target_quantity" field.
func TargetQuantityNotIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldTargetQuantity, vs...))
}

// TargetQuantityGT applies the GT predicate on the "target_quantity" field.
func TargetQuantityGT(v int) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldTargetQuantity, v))
}

// TargetQuantityGTE applies the GTE predicate on the "target_quantity" field.
func TargetQuantityGTE(v int) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldTargetQuantity, v))
}

// TargetQuantityLT applies the LT predicate on the "target_quantity" field.
func TargetQuantityLT(v int) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldTargetQuantity, v))
}

// TargetQuantityLTE applies the LTE predicate on the "target_quantity" field.
func TargetQuantityLTE(v int) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldTargetQuantity, v))
}

// ActualQuantityEQ applies the EQ predicate on the "actual_quantity" field.
func ActualQuantityEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldActualQuantity, v))
}

// ActualQuantityNEQ applies the NEQ predicate on the "actual_quantity" field.
func ActualQuantityNEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldActualQuantity, v))
}

// ActualQuantityIn applies the In predicate on the "actual_quantity" field.
func ActualQuantityIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldActualQuantity, vs...))
}

// ActualQuantityNotIn applies the NotIn predicate on the "actual_quantity" field.
func ActualQuantityNotIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldActualQuantity, vs...))
}

// ActualQuantityGT applies the GT predicate on the "actual_quantity" field.
func ActualQuantityGT(v int) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldActualQuantity, v))
}

// ActualQuantityGTE applies the GTE predicate on the "actual_quantity" field.
func ActualQuantityGTE(v int) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldActualQuantity, v))
}

// ActualQuantityLT applies the LT predicate on the "actual_quantity" field.
func ActualQuantityLT(v int) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldActualQuantity, v))
}

// ActualQuantityLTE applies the LTE predicate on the "actual_quantity" field.
func ActualQuantityLTE(v int) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldActualQuantity, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldStatus, vs...))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldPriority, v))
}

// DeliveryDateEQ applies the EQ predicate on the "delivery_date" field.
func DeliveryDateEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveryDate, v))
}

// DeliveryDateNEQ applies the NEQ predicate on the "delivery_date" field.
func DeliveryDateNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldDeliveryDate, v))
}

// DeliveryDateIn applies the In predicate on the "delivery_date" field.
func DeliveryDateIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldDeliveryDate, vs...))
}

// DeliveryDateNotIn applies the NotIn predicate on the "delivery_date" field.
func DeliveryDateNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldDeliveryDate, vs...))
}

// DeliveryDateGT applies the GT predicate on the "delivery_date" field.
func DeliveryDateGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldDeliveryDate, v))
}

// DeliveryDateGTE applies the GTE predicate on the "delivery_date" field.
func DeliveryDateGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldDeliveryDate, v))
}

// DeliveryDateLT applies the LT predicate on the "delivery_date" field.
func DeliveryDateLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldDeliveryDate, v))
}

// DeliveryDateLTE applies the LTE predicate on the "delivery_date" field.
func DeliveryDateLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldDeliveryDate, v))
}

// DeliveryDateIsNil applies the IsNil predicate on the "delivery_date" field.
func DeliveryDateIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldDeliveryDate))
}

// DeliveryDateNotNil applies the NotNil predicate on the "delivery_date" field.
func DeliveryDateNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldDeliveryDate))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLots applies the HasEdge predicate on the "lots" edge.
func HasLots() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LotsTable, LotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLotsWith applies the HasEdge predicate on the "lots" edge with a given conditions (other predicates).
func HasLotsWith(preds ...predicate.Lot) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newLotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Order) predicate.Order {
	return predicate.Order(sql.NotPredicates(p))
}
