// Code generated by ent, DO NOT EDIT.

package module

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the module type in the database.
	Label = "module"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModuleNumber holds the string denoting the module_number field in the database.
	FieldModuleNumber = "module_number"
	// FieldBarrel1ID holds the string denoting the barrel1_id field in the database.
	FieldBarrel1ID = "barrel1_id"
	// FieldBarrel2ID holds the string denoting the barrel2_id field in the database.
	FieldBarrel2ID = "barrel2_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRfid holds the string denoting the rfid field in the database.
	FieldRfid = "rfid"
	// FieldCurrentLocation holds the string denoting the current_location field in the database.
	FieldCurrentLocation = "current_location"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the module in the database.
	Table = "modules"
)

// Columns holds all SQL columns for module fields.
var Columns = []string{
	FieldID,
	FieldModuleNumber,
	FieldBarrel1ID,
	FieldBarrel2ID,
	FieldStatus,
	FieldRfid,
	FieldCurrentLocation,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModuleNumberValidator is a validator for the "module_number" field. It is called by the builders before save.
	ModuleNumberValidator func(string) error
	// RfidValidator is a validator for the "rfid" field. It is called by the builders before save.
	RfidValidator func(string) error
	// CurrentLocationValidator is a validator for the "current_location" field. It is called by the builders before save.
	CurrentLocationValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusIdle is the default value of the Status enum.
const DefaultStatus = StatusIdle

// Status values.
const (
	StatusLoading      Status = "loading"
	StatusTransporting Status = "transporting"
	StatusSorting      Status = "sorting"
	StatusWarehouse    Status = "warehouse"
	StatusIdle         Status = "idle"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusLoading, StatusTransporting, StatusSorting, StatusWarehouse, StatusIdle:
		return nil
	default:
		return fmt.Errorf("module: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Module queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModuleNumber orders the results by the module_number field.
func ByModuleNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModuleNumber, opts...).ToFunc()
}

// ByBarrel1ID orders the results by the barrel1_id field.
func ByBarrel1ID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBarrel1ID, opts...).ToFunc()
}

// ByBarrel2ID orders the results by the barrel2_id field.
func ByBarrel2ID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBarrel2ID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRfid orders the results by the rfid field.
func ByRfid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRfid, opts...).ToFunc()
}

// ByCurrentLocation orders the results by the current_location field.
func ByCurrentLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentLocation, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
