// Code generated by ent, DO NOT EDIT.

package barrel

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the barrel type in the database.
	Label = "barrel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBarrelNumber holds the string denoting the barrel_number field in the database.
	FieldBarrelNumber = "barrel_number"
	// FieldLotID holds the string denoting the lot_id field in the database.
	FieldLotID = "lot_id"
	// FieldCapacity holds the string denoting the capacity field in the database.
	FieldCapacity = "capacity"
	// FieldCurrentCount holds the string denoting the current_count field in the database.
	FieldCurrentCount = "current_count"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFilledAt holds the string denoting the filled_at field in the database.
	FieldFilledAt = "filled_at"
	// FieldSyncStatus holds the string denoting the sync_status field in the database.
	FieldSyncStatus = "sync_status"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// FieldSyncRetryCount holds the string denoting the sync_retry_count field in the database.
	FieldSyncRetryCount = "sync_retry_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeLot holds the string denoting the lot edge name in mutations.
	EdgeLot = "lot"
	// EdgeBobbins holds the string denoting the bobbins edge name in mutations.
	EdgeBobbins = "bobbins"
	// Table holds the table name of the barrel in the database.
	Table = "barrels"
	// LotTable is the table that holds the lot relation/edge.
	LotTable = "barrels"
	// LotInverseTable is the table name for the Lot entity.
	// It exists in this package in order to avoid circular dependency with the "lot" package.
	LotInverseTable = "lots"
	// LotColumn is the table column denoting the lot relation/edge.
	LotColumn = "lot_id"
	// BobbinsTable is the table that holds the bobbins relation/edge.
	BobbinsTable = "bobbins"
	// BobbinsInverseTable is the table name for the Bobbin entity.
	// It exists in this package in order to avoid circular dependency with the "bobbin" package.
	BobbinsInverseTable = "bobbins"
	// BobbinsColumn is the table column denoting the bobbins relation/edge.
	BobbinsColumn = "barrel_id"
)

// Columns holds all SQL columns for barrel fields.
var Columns = []string{
	FieldID,
	FieldBarrelNumber,
	FieldLotID,
	FieldCapacity,
	FieldCurrentCount,
	FieldStatus,
	FieldFilledAt,
	FieldSyncStatus,
	FieldSyncedAt,
	FieldSyncRetryCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BarrelNumberValidator is a validator for the "barrel_number" field. It is called by the builders before save.
	BarrelNumberValidator func(string) error
	// DefaultCapacity holds the default value on creation for the "capacity" field.
	DefaultCapacity int
	// CapacityValidator is a validator for the "capacity" field. It is called by the builders before save.
	CapacityValidator func(int) error
	// DefaultCurrentCount holds the default value on creation for the "current_count" field.
	DefaultCurrentCount int
	// CurrentCountValidator is a validator for the "current_count" field. It is called by the builders before save.
	CurrentCountValidator func(int) error
	// DefaultSyncRetryCount holds the default value on creation for the "sync_retry_count" field.
	DefaultSyncRetryCount int
	// SyncRetryCountValidator is a validator for the "sync_retry_count" field. It is called by the builders before save.
	SyncRetryCountValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive Status = "active"
	StatusFull   Status = "full"
	StatusSorted Status = "sorted"
	StatusPacked Status = "packed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusFull, StatusSorted, StatusPacked:
		return nil
	default:
		return fmt.Errorf("barrel: invalid enum value for status field: %q", s)
	}
}

// SyncStatus defines the type for the "sync_status" enum field.
type SyncStatus string

// SyncStatusPending is the default value of the SyncStatus enum.
const DefaultSyncStatus = SyncStatusPending

// SyncStatus values.
const (
	SyncStatusPending SyncStatus = "pending"
	SyncStatusSynced  SyncStatus = "synced"
	SyncStatusFailed  SyncStatus = "failed"
)

func (ss SyncStatus) String() string {
	return string(ss)
}

// SyncStatusValidator is a validator for the "sync_status" field enum values. It is called by the builders before save.
func SyncStatusValidator(ss SyncStatus) error {
	switch ss {
	case SyncStatusPending, SyncStatusSynced, SyncStatusFailed:
		return nil
	default:
		return fmt.Errorf("barrel: invalid enum value for sync_status field: %q", ss)
	}
}

// OrderOption defines the ordering options for the Barrel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBarrelNumber orders the results by the barrel_number field.
func ByBarrelNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBarrelNumber, opts...).ToFunc()
}

// ByLotID orders the results by the lot_id field.
func ByLotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLotID, opts...).ToFunc()
}

// ByCapacity orders the results by the capacity field.
func ByCapacity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapacity, opts...).ToFunc()
}

// ByCurrentCount orders the results by the current_count field.
func ByCurrentCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentCount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFilledAt orders the results by the filled_at field.
func ByFilledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilledAt, opts...).ToFunc()
}

// BySyncStatus orders the results by the sync_status field.
func BySyncStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncStatus, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// BySyncRetryCount orders the results by the sync_retry_count field.
func BySyncRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncRetryCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLotField orders the results by lot field.
func ByLotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLotStep(), sql.OrderByField(field, opts...))
	}
}

// ByBobbinsCount orders the results by bobbins count.
func ByBobbinsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBobbinsStep(), opts...)
	}
}

// ByBobbins orders the results by bobbins terms.
func ByBobbins(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBobbinsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LotTable, LotColumn),
	)
}
func newBobbinsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BobbinsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BobbinsTable, BobbinsColumn),
	)
}
