// Code generated by ent, DO NOT EDIT.

package pallet

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/yourusername/igh-silkroad/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldID, id))
}

// PalletCode applies equality check predicate on the "pallet_code" field. It's identical to PalletCodeEQ.
func PalletCode(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldPalletCode, v))
}

// EdgeID applies equality check predicate on the "edge_id" field. It's identical to EdgeIDEQ.
func EdgeID(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldEdgeID, v))
}

// LotID applies equality check predicate on the "lot_id" field. It's identical to LotIDEQ.
func LotID(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldLotID, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldLevel, v))
}

// BobbinsCount applies equality check predicate on the "bobbins_count" field. It's identical to BobbinsCountEQ.
func BobbinsCount(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldBobbinsCount, v))
}

// NetWeight applies equality check predicate on the "net_weight" field. It's identical to NetWeightEQ.
func NetWeight(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldNetWeight, v))
}

// GrossWeight applies equality check predicate on the "gross_weight" field. It's identical to GrossWeightEQ.
func GrossWeight(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldGrossWeight, v))
}

// TareWeight applies equality check predicate on the "tare_weight" field. It's identical to TareWeightEQ.
func TareWeight(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldTareWeight, v))
}

// PalletizerID applies equality check predicate on the "palletizer_id" field. It's identical to PalletizerIDEQ.
func PalletizerID(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldPalletizerID, v))
}

// Printed applies equality check predicate on the "printed" field. It's identical to PrintedEQ.
func Printed(v bool) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldPrinted, v))
}

// PrintedAt applies equality check predicate on the "printed_at" field. It's identical to PrintedAtEQ.
func PrintedAt(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldPrintedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldCompletedAt, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncRetryCount applies equality check predicate on the "sync_retry_count" field. It's identical to SyncRetryCountEQ.
func SyncRetryCount(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldSyncRetryCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// PalletCodeEQ applies the EQ predicate on the "pallet_code" field.
func PalletCodeEQ(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldPalletCode, v))
}

// PalletCodeNEQ applies the NEQ predicate on the "pallet_code" field.
func PalletCodeNEQ(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldPalletCode, v))
}

// PalletCodeIn applies the In predicate on the "pallet_code" field.
func PalletCodeIn(vs ...string) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldPalletCode, vs...))
}

// PalletCodeNotIn applies the NotIn predicate on the "pallet_code" field.
func PalletCodeNotIn(vs ...string) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldPalletCode, vs...))
}

// PalletCodeGT applies the GT predicate on the "pallet_code" field.
func PalletCodeGT(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldPalletCode, v))
}

// PalletCodeGTE applies the GTE predicate on the "pallet_code" field.
func PalletCodeGTE(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldPalletCode, v))
}

// PalletCodeLT applies the LT predicate on the "pallet_code" field.
func PalletCodeLT(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldPalletCode, v))
}

// PalletCodeLTE applies the LTE predicate on the "pallet_code" field.
func PalletCodeLTE(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldPalletCode, v))
}

// PalletCodeContains applies the Contains predicate on the "pallet_code" field.
func PalletCodeContains(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldContains(FieldPalletCode, v))
}

// PalletCodeHasPrefix applies the HasPrefix predicate on the "pallet_code" field.
func PalletCodeHasPrefix(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldHasPrefix(FieldPalletCode, v))
}

// PalletCodeHasSuffix applies the HasSuffix predicate on the "pallet_code" field.
func PalletCodeHasSuffix(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldHasSuffix(FieldPalletCode, v))
}

// PalletCodeEqualFold applies the EqualFold predicate on the "pallet_code" field.
func PalletCodeEqualFold(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldEqualFold(FieldPalletCode, v))
}

// PalletCodeContainsFold applies the ContainsFold predicate on the "pallet_code" field.
func PalletCodeContainsFold(v string) predicate.Pallet {
	return predicate.Pallet(sql.FieldContainsFold(FieldPalletCode, v))
}

// EdgeIDEQ applies the EQ predicate on the "edge_id" field.
func EdgeIDEQ(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldEdgeID, v))
}

// EdgeIDNEQ applies the NEQ predicate on the "edge_id" field.
func EdgeIDNEQ(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldEdgeID, v))
}

// EdgeIDIn applies the In predicate on the "edge_id" field.
func EdgeIDIn(vs ...uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldEdgeID, vs...))
}

// EdgeIDNotIn applies the NotIn predicate on the "edge_id" field.
func EdgeIDNotIn(vs ...uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldEdgeID, vs...))
}

// EdgeIDGT applies the GT predicate on the "edge_id" field.
func EdgeIDGT(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldEdgeID, v))
}

// EdgeIDGTE applies the GTE predicate on the "edge_id" field.
func EdgeIDGTE(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldEdgeID, v))
}

// EdgeIDLT applies the LT predicate on the "edge_id" field.
func EdgeIDLT(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldEdgeID, v))
}

// EdgeIDLTE applies the LTE predicate on the "edge_id" field.
func EdgeIDLTE(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldEdgeID, v))
}

// EdgeIDIsNil applies the IsNil predicate on the "edge_id" field.
func EdgeIDIsNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldIsNull(FieldEdgeID))
}

// EdgeIDNotNil applies the NotNil predicate on the "edge_id" field.
func EdgeIDNotNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldNotNull(FieldEdgeID))
}

// LotIDEQ applies the EQ predicate on the "lot_id" field.
func LotIDEQ(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldLotID, v))
}

// LotIDNEQ applies the NEQ predicate on the "lot_id" field.
func LotIDNEQ(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldLotID, v))
}

// LotIDIn applies the In predicate on the "lot_id" field.
func LotIDIn(vs ...uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldLotID, vs...))
}

// LotIDNotIn applies the NotIn predicate on the "lot_id" field.
func LotIDNotIn(vs ...uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldLotID, vs...))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...int) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...int) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldLevel, v))
}

// BobbinsCountEQ applies the EQ predicate on the "bobbins_count" field.
func BobbinsCountEQ(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldBobbinsCount, v))
}

// BobbinsCountNEQ applies the NEQ predicate on the "bobbins_count" field.
func BobbinsCountNEQ(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldBobbinsCount, v))
}

// BobbinsCountIn applies the In predicate on the "bobbins_count" field.
func BobbinsCountIn(vs ...int) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldBobbinsCount, vs...))
}

// BobbinsCountNotIn applies the NotIn predicate on the "bobbins_count" field.
func BobbinsCountNotIn(vs ...int) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldBobbinsCount, vs...))
}

// BobbinsCountGT applies the GT predicate on the "bobbins_count" field.
func BobbinsCountGT(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldBobbinsCount, v))
}

// BobbinsCountGTE applies the GTE predicate on the "bobbins_count" field.
func BobbinsCountGTE(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldBobbinsCount, v))
}

// BobbinsCountLT applies the LT predicate on the "bobbins_count" field.
func BobbinsCountLT(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldBobbinsCount, v))
}

// BobbinsCountLTE applies the LTE predicate on the "bobbins_count" field.
func BobbinsCountLTE(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldBobbinsCount, v))
}

// NetWeightEQ applies the EQ predicate on the "net_weight" field.
func NetWeightEQ(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldNetWeight, v))
}

// NetWeightNEQ applies the NEQ predicate on the "net_weight" field.
func NetWeightNEQ(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldNetWeight, v))
}

// NetWeightIn applies the In predicate on the "net_weight" field.
func NetWeightIn(vs ...float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldNetWeight, vs...))
}

// NetWeightNotIn applies the NotIn predicate on the "net_weight" field.
func NetWeightNotIn(vs ...float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldNetWeight, vs...))
}

// NetWeightGT applies the GT predicate on the "net_weight" field.
func NetWeightGT(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldNetWeight, v))
}

// NetWeightGTE applies the GTE predicate on the "net_weight" field.
func NetWeightGTE(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldNetWeight, v))
}

// NetWeightLT applies the LT predicate on the "net_weight" field.
func NetWeightLT(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldNetWeight, v))
}

// NetWeightLTE applies the LTE predicate on the "net_weight" field.
func NetWeightLTE(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldNetWeight, v))
}

// NetWeightIsNil applies the IsNil predicate on the "net_weight" field.
func NetWeightIsNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldIsNull(FieldNetWeight))
}

// NetWeightNotNil applies the NotNil predicate on the "net_weight" field.
func NetWeightNotNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldNotNull(FieldNetWeight))
}

// GrossWeightEQ applies the EQ predicate on the "gross_weight" field.
func GrossWeightEQ(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldGrossWeight, v))
}

// GrossWeightNEQ applies the NEQ predicate on the "gross_weight" field.
func GrossWeightNEQ(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldGrossWeight, v))
}

// GrossWeightIn applies the In predicate on the "gross_weight" field.
func GrossWeightIn(vs ...float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldGrossWeight, vs...))
}

// GrossWeightNotIn applies the NotIn predicate on the "gross_weight" field.
func GrossWeightNotIn(vs ...float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldGrossWeight, vs...))
}

// GrossWeightGT applies the GT predicate on the "gross_weight" field.
func GrossWeightGT(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldGrossWeight, v))
}

// GrossWeightGTE applies the GTE predicate on the "gross_weight" field.
func GrossWeightGTE(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldGrossWeight, v))
}

// GrossWeightLT applies the LT predicate on the "gross_weight" field.
func GrossWeightLT(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldGrossWeight, v))
}

// GrossWeightLTE applies the LTE predicate on the "gross_weight" field.
func GrossWeightLTE(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldGrossWeight, v))
}

// GrossWeightIsNil applies the IsNil predicate on the "gross_weight" field.
func GrossWeightIsNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldIsNull(FieldGrossWeight))
}

// GrossWeightNotNil applies the NotNil predicate on the "gross_weight" field.
func GrossWeightNotNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldNotNull(FieldGrossWeight))
}

// TareWeightEQ applies the EQ predicate on the "tare_weight" field.
func TareWeightEQ(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldTareWeight, v))
}

// TareWeightNEQ applies the NEQ predicate on the "tare_weight" field.
func TareWeightNEQ(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldTareWeight, v))
}

// TareWeightIn applies the In predicate on the "tare_weight" field.
func TareWeightIn(vs ...float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldTareWeight, vs...))
}

// TareWeightNotIn applies the NotIn predicate on the "tare_weight" field.
func TareWeightNotIn(vs ...float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldTareWeight, vs...))
}

// TareWeightGT applies the GT predicate on the "tare_weight" field.
func TareWeightGT(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldTareWeight, v))
}

// TareWeightGTE applies the GTE predicate on the "tare_weight" field.
func TareWeightGTE(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldTareWeight, v))
}

// TareWeightLT applies the LT predicate on the "tare_weight" field.
func TareWeightLT(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldTareWeight, v))
}

// TareWeightLTE applies the LTE predicate on the "tare_weight" field.
func TareWeightLTE(v float64) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldTareWeight, v))
}

// TareWeightIsNil applies the IsNil predicate on the "tare_weight" field.
func TareWeightIsNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldIsNull(FieldTareWeight))
}

// TareWeightNotNil applies the NotNil predicate on the "tare_weight" field.
func TareWeightNotNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldNotNull(FieldTareWeight))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldStatus, vs...))
}

// PalletizerIDEQ applies the EQ predicate on the "palletizer_id" field.
func PalletizerIDEQ(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldPalletizerID, v))
}

// PalletizerIDNEQ applies the NEQ predicate on the "palletizer_id" field.
func PalletizerIDNEQ(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldPalletizerID, v))
}

// PalletizerIDIn applies the In predicate on the "palletizer_id" field.
func PalletizerIDIn(vs ...uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldPalletizerID, vs...))
}

// PalletizerIDNotIn applies the NotIn predicate on the "palletizer_id" field.
func PalletizerIDNotIn(vs ...uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldPalletizerID, vs...))
}

// PalletizerIDGT applies the GT predicate on the "palletizer_id" field.
func PalletizerIDGT(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldPalletizerID, v))
}

// PalletizerIDGTE applies the GTE predicate on the "palletizer_id" field.
func PalletizerIDGTE(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldPalletizerID, v))
}

// PalletizerIDLT applies the LT predicate on the "palletizer_id" field.
func PalletizerIDLT(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldPalletizerID, v))
}

// PalletizerIDLTE applies the LTE predicate on the "palletizer_id" field.
func PalletizerIDLTE(v uuid.UUID) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldPalletizerID, v))
}

// PalletizerIDIsNil applies the IsNil predicate on the "palletizer_id" field.
func PalletizerIDIsNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldIsNull(FieldPalletizerID))
}

// PalletizerIDNotNil applies the NotNil predicate on the "palletizer_id" field.
func PalletizerIDNotNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldNotNull(FieldPalletizerID))
}

// PrintedEQ applies the EQ predicate on the "printed" field.
func PrintedEQ(v bool) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldPrinted, v))
}

// PrintedNEQ applies the NEQ predicate on the "printed" field.
func PrintedNEQ(v bool) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldPrinted, v))
}

// PrintedAtEQ applies the EQ predicate on the "printed_at" field.
func PrintedAtEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldPrintedAt, v))
}

// PrintedAtNEQ applies the NEQ predicate on the "printed_at" field.
func PrintedAtNEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldPrintedAt, v))
}

// PrintedAtIn applies the In predicate on the "printed_at" field.
func PrintedAtIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldPrintedAt, vs...))
}

// PrintedAtNotIn applies the NotIn predicate on the "printed_at" field.
func PrintedAtNotIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldPrintedAt, vs...))
}

// PrintedAtGT applies the GT predicate on the "printed_at" field.
func PrintedAtGT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldPrintedAt, v))
}

// PrintedAtGTE applies the GTE predicate on the "printed_at" field.
func PrintedAtGTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldPrintedAt, v))
}

// PrintedAtLT applies the LT predicate on the "printed_at" field.
func PrintedAtLT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldPrintedAt, v))
}

// PrintedAtLTE applies the LTE predicate on the "printed_at" field.
func PrintedAtLTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldPrintedAt, v))
}

// PrintedAtIsNil applies the IsNil predicate on the "printed_at" field.
func PrintedAtIsNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldIsNull(FieldPrintedAt))
}

// PrintedAtNotNil applies the NotNil predicate on the "printed_at" field.
func PrintedAtNotNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldNotNull(FieldPrintedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldNotNull(FieldCompletedAt))
}

// SyncStatusEQ applies the EQ predicate on the "sync_status" field.
func SyncStatusEQ(v SyncStatus) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldSyncStatus, v))
}

// SyncStatusNEQ applies the NEQ predicate on the "sync_status" field.
func SyncStatusNEQ(v SyncStatus) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldSyncStatus, v))
}

// SyncStatusIn applies the In predicate on the "sync_status" field.
func SyncStatusIn(vs ...SyncStatus) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldSyncStatus, vs...))
}

// SyncStatusNotIn applies the NotIn predicate on the "sync_status" field.
func SyncStatusNotIn(vs ...SyncStatus) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldSyncStatus, vs...))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldSyncedAt, v))
}

// SyncedAtIsNil applies the IsNil predicate on the "synced_at" field.
func SyncedAtIsNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldIsNull(FieldSyncedAt))
}

// SyncedAtNotNil applies the NotNil predicate on the "synced_at" field.
func SyncedAtNotNil() predicate.Pallet {
	return predicate.Pallet(sql.FieldNotNull(FieldSyncedAt))
}

// SyncRetryCountEQ applies the EQ predicate on the "sync_retry_count" field.
func SyncRetryCountEQ(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldSyncRetryCount, v))
}

// SyncRetryCountNEQ applies the NEQ predicate on the "sync_retry_count" field.
func SyncRetryCountNEQ(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldSyncRetryCount, v))
}

// SyncRetryCountIn applies the In predicate on the "sync_retry_count" field.
func SyncRetryCountIn(vs ...int) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldSyncRetryCount, vs...))
}

// SyncRetryCountNotIn applies the NotIn predicate on the "sync_retry_count" field.
func SyncRetryCountNotIn(vs ...int) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldSyncRetryCount, vs...))
}

// SyncRetryCountGT applies the GT predicate on the "sync_retry_count" field.
func SyncRetryCountGT(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldSyncRetryCount, v))
}

// SyncRetryCountGTE applies the GTE predicate on the "sync_retry_count" field.
func SyncRetryCountGTE(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldSyncRetryCount, v))
}

// SyncRetryCountLT applies the LT predicate on the "sync_retry_count" field.
func SyncRetryCountLT(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldSyncRetryCount, v))
}

// SyncRetryCountLTE applies the LTE predicate on the "sync_retry_count" field.
func SyncRetryCountLTE(v int) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldSyncRetryCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Pallet {
	return predicate.Pallet(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasLot applies the HasEdge predicate on the "lot" edge.
func HasLot() predicate.Pallet {
	return predicate.Pallet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LotTable, LotColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLotWith applies the HasEdge predicate on the "lot" edge with a given conditions (other predicates).
func HasLotWith(preds ...predicate.Lot) predicate.Pallet {
	return predicate.Pallet(func(s *sql.Selector) {
		step := newLotStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBobbins applies the HasEdge predicate on the "bobbins" edge.
func HasBobbins() predicate.Pallet {
	return predicate.Pallet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BobbinsTable, BobbinsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBobbinsWith applies the HasEdge predicate on the "bobbins" edge with a given conditions (other predicates).
func HasBobbinsWith(preds ...predicate.Bobbin) predicate.Pallet {
	return predicate.Pallet(func(s *sql.Selector) {
		step := newBobbinsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Pallet) predicate.Pallet {
	return predicate.Pallet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Pallet) predicate.Pallet {
	return predicate.Pallet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pallet) predicate.Pallet {
	return predicate.Pallet(sql.NotPredicates(p))
}
