// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bobbin is the predicate function for bobbin builders.
type Bobbin func(*sql.Selector)

// Lot is the predicate function for lot builders.
type Lot func(*sql.Selector)

// SyncLog is the predicate function for synclog builders.
type SyncLog func(*sql.Selector)
